### ISSUE TITLE
Tabs in windows/containers

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#102]
**Is your feature request related to a problem? Please describe.**
Several related sets of content need to be shown in separate windows/sections, or hacked to mimic the position.

**Describe the solution you'd like**
The option to group a collection of windows/containers in a single window/container and select a button (tab) to navigate between them. 

**Additional context**
Your comment about tabs, from #75 :
> Yeah, I've thought about doing 'proper' tabs for windows, the main thing I'm waiting on a bit there is the eventual proper release of Pygame 2 as I have hopes it'll allow me to speed up and simplify my existing drawing code and make things like the rounded corners more viable to have everywhere (if you haven't noticed if you add a bunch of rounded corners to everything in a complicated UI thing it eventually can take about half a second to draw things which feels unresponsive). With rounded corners on a tab you want a surprisingly tricky shape to dynamically draw where the 'exposed' edge is rounded in the normal fashion and the 'connecting' edge is has curves that go the other way, all of which means it will take longer to put together on the fly.

**Comment by t0a5ted** [comment]
This.

**Comment by LondonClass** [comment]
need this

**Comment by LondonClass** [comment]
[tab.zip](https://github.com/MyreMylar/pygame_gui/files/14227354/tab.zip)
I am working on this aspect. This is an example of using buttons to switch between panels. May I ask if you have any suggestions?
