### ISSUE TITLE
Button with pressed state (like a checkbox)

### ISSUE THREAD

**Issue by void4** [MyreMylar/pygame_gui#107]
**Is your feature request related to a problem? Please describe.**
Sometimes, mouse clicks should lead to a different behavior in a game as long as a button is selected. Say, a "recruit" button that enables unit placement until it is clicked on again, or the mouse is right clicked.

**Describe the solution you'd like**
The button should maintain its pressed state until it is clicked again.

Edit: I suppose this can also be implemented externally with
```python

selection = None

# The following in the mainloop
for event in pygame.event.get():
  if event.type == pygame.USEREVENT:
    if event.user_type == pygame_gui.UI_BUTTON_PRESSED:
      if selection:
        selection = None
      else:
        selection = event.ui_element
```

though a checkbox would be nice

(This library is really great btw)

**Comment by MyreMylar** [comment]
I use select() & unselect() for this sort of idea, called on the button. So using your example:

    for event in pygame.event.get():
        if event.type == pygame.USEREVENT:
            if event.user_type == pygame_gui.UI_BUTTON_PRESSED:
                 if event,ui_element.is_selected:
                     event.ui_element.unselect()
                 else:
                     event.ui_element.select()

Does that cover what you are after? It's how the toggle buttons work in the UISelectionList

**Comment by void4** [comment]
That works beautifully! 
![image](https://user-images.githubusercontent.com/11392207/80632760-0262b580-8a58-11ea-947e-a96ae75ae303.png)
Combined with some more code that unselects all other buttons, I can achieve a RadioButton-like behavior with this (although I might use the UISelectionList for this, too)

Thank you!
