### ISSUE TITLE
horizontal scroll bar

### ISSUE THREAD

**Issue by flowmeadow** [MyreMylar/pygame_gui#110]
**Is your feature request related to a problem? Please describe.**
Hey there,
to be honest, I did not start coding with pygame_gui yet. But while looking for the possibilities, I mentioned that a horizontal scroll bar is missing (also a vertical slider). This is not a big deal, but leads to a gui redesign of my current project.

**Describe the solution you'd like**
A gui element that allows scrolling of a region in horizontal direction. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by MyreMylar** [comment]
There is a horizontal scroll bar from version 0.5.5, see docs here:

https://pygame-gui.readthedocs.io/en/latest/theme_reference/theme_horizontal_scroll_bar.html
