### ISSUE TITLE
ModuleNotFoundError: No module named 'pygame_gui'

### ISSUE THREAD

**Issue by atlas75** [MyreMylar/pygame_gui#112]
**Describe the bug**
Python can't find Pygame gui, even if i didn't get any error message after the install with the command.

**To Reproduce**
Steps to reproduce the behaviour:
1. python -m pip install pygame_gui

**Expected behaviour**
ModuleNotFoundError: No module named 'pygame_gui' appears when i try to use "import pygame_gui"

**Screenshots**
<img width="932" alt="code" src="https://user-images.githubusercontent.com/65235738/81707373-e5bf7800-9470-11ea-925a-7ab54e5f3ea2.PNG">
<img width="483" alt="install" src="https://user-images.githubusercontent.com/65235738/81707389-e952ff00-9470-11ea-9541-ff23ffbccd69.PNG">

**Platform and software (please complete the following information):**
 - OS: Windows 10
 - Pygame GUI version 0.5.6
 - Pygame version 1.9.6
 - Python IDE : Spyder
 - Python version 3.7 

**Additional context**
I unzipped the pygame_gui-master and pygame_gui-0.5.6 in the same folder as the IDE but it did'nt do anything. They are also still in the Download folder.

**Comment by MyreMylar** [comment]
Perhaps you have multiple versions of python installed.

What happens when you type:

`python --version` 

in powershell.

And is it different to what happens when you run:

    import sys
    print(sys.version)

in Spyder.

If you only have two versions you may be able to just use:

`python3 -m pip install pygame_gui`

**Comment by atlas75** [comment]
Thank you for your quick answer!

When I run python --version in powershell nothing happens.
When i run import sys in Spyder, I got "3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]".

I tried to use python3 -m pip install pygame_gui but istill get the ModuleNotFoundError.

**Comment by MyreMylar** [comment]
The fact that you aren't getting any version information in powershell suggests that you don't have python in your windows PATH environment variable.

If you type `path` into your windows 10 search bar it should let you edit your environment variables.

For example, mine look like this for Python 3.8:

![image](https://user-images.githubusercontent.com/13382426/81714904-801ebc00-946f-11ea-81d7-4e046be7df17.png)

Your 3.7 python.exe will likely be in a similar place. Don't forget to also set the path to the Scripts folder.

**Comment by atlas75** [comment]
Even when I edit the path, I still don't get any version information. 
I tried to use pip.exe, pip3.exe and pip3.7.exe and nothing happend.
And when I try  "pip.exe install pygame_gui" I have an error message that pip is not recognized as an internal or external command, operable program or batch file.

**Comment by MyreMylar** [comment]
You may need to reboot your computer after adding the path.

**Comment by MyreMylar** [comment]
This is what it should look like when you have it setup correctly:

![image](https://user-images.githubusercontent.com/13382426/81721603-0e973b80-9478-11ea-9310-33e9984b894f.png)
