### ISSUE TITLE
DropdownMenu - Selecting an option can trigger elements under that option

### ISSUE THREAD

**Issue by alverndbl** [MyreMylar/pygame_gui#114]
**Describe the bug**
If the option list of the dropdownMenu is above another, when you select an option you can have both of the dropdownMenus open at the same time.

**To Reproduce**
Steps to reproduce the behaviour:
1. open general_ui_test_app.py from the examples
2. change the name of **self.test_drop_down** so it doen't trigger the event
2. add another dropdownMenu:
`        self.test_drop_down3 = UIDropDownMenu(['640x480', '800x600', '1024x768'],
                                              current_resolution_string,
                                              pygame.Rect((int(self.options.resolution[0] / 2),
                                                           int(self.options.resolution[1] * 0.3 - 50)),
                                                          (200, 25)),
                                              self.ui_manager)`
3. Click 800x600 on the lower dropdown

![image](https://user-images.githubusercontent.com/58402573/83290326-c6ea1100-a1e6-11ea-8bbe-43778334ec60.png)

Btw thank you for all the work, pygame_gui it's really nice.

**Comment by MyreMylar** [comment]
Thanks for the report! I know why it works this way (it's the way I programmed it). I'll ponder if I can make it better.

**Comment by MyreMylar** [comment]
This should now be fixed in 0.5.7.
