### ISSUE TITLE
Children buttons of a panel are rendered when they don't fit

### ISSUE THREAD

**Issue by ylenard** [MyreMylar/pygame_gui#120]
**Describe the bug**
When the UI rect is smaller than it's border width + shadow width, it children elements are rendered when they shouldn't. Specifically only parts of the children elements are rendered.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a UI panel with border width 1 and shadow width 15
2. Make the UI panel width < 32
3. Add a button to it positioned at (0, 0)

**Expected behaviour**
The button is not rendered

**Screenshots**
Here's how its rendered with panel size < border width + shadow width by 1 point.
Don't mind the dark gray text. The vertical dark line is the shadow / border of a UIPanel. The white texts are children of the panel - UIButtons. They are centered. As you can see part of them is rendered.

![screenshot 1](https://user-images.githubusercontent.com/66242747/83622146-e3dc6680-a58f-11ea-8ff9-edd0a42ef6d9.jpg)

Here's how its rendered with panel size = border width + shadow width. That's also what I believe it should look like:

![screenshot 2](https://user-images.githubusercontent.com/66242747/83622418-3b7ad200-a590-11ea-9ebc-7813ee0732e5.jpg)

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.5.6
 - Pygame version 2.0.0 dev 8

**Comment by MyreMylar** [comment]
Probably an error in how I'm calculating the clipping when something overlaps the borders of it's container on both sides.

Not quite sure what you are trying to do here, but if it's exposing weird edge case bugs then it works for me!

**Comment by MyreMylar** [comment]
I tried this:

    import pygame
    from pygame_gui import UIManager
    from pygame_gui.elements import UIPanel
    from pygame_gui.elements import UIButton
    
    pygame.init()
    
    test_surface = pygame.display.set_mode((300, 300), 0, 32)
    test_surface.fill(pygame.Color(128, 128, 128, 255))
    manager = UIManager((300, 300), theme_path='data/test_theme.json')
    panel = UIPanel(relative_rect=pygame.Rect(50, 50, 30, 200),
                              starting_layer_height=1, manager=manager)
    button = UIButton(relative_rect=pygame.Rect(0, 0, 150, 30), text="Test", manager=manager,
                      container=panel)
    
    manager.draw_ui(test_surface)
    
    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
        pygame.display.update()

And this theme file:

    {
        "panel":
        {
            "misc":
            {
                "shadow_width": "15",
                "border_width": "1"
            }
        }
    }


But couldn't seem to reproduce this issue on 0.5.6, or the current master branch. What am I doing wrong?

My output looks like this:

![image](https://user-images.githubusercontent.com/13382426/83632487-45ec9a00-a597-11ea-9c36-c92b05e9222c.png)

**Comment by ylenard** [comment]
I got it! Try this:
```

import pygame
from pygame_gui import UIManager
from pygame_gui.elements import UIPanel
from pygame_gui.elements import UIButton

pygame.init()

test_surface = pygame.display.set_mode((300, 300), 0, 32)
test_surface.fill(pygame.Color(128, 128, 128, 255))
manager = UIManager((300, 300), theme_path='data/test_theme.json')
panel = UIPanel(relative_rect=pygame.Rect(50, 50, 30, 200),
                          starting_layer_height=1, manager=manager)
button = UIButton(relative_rect=pygame.Rect(-75, 0, 150, 30), text="Test", manager=manager,
                  container=panel)

manager.draw_ui(test_surface)

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
    pygame.display.update()
```

 Negative x-coordinate of the position of the button was needed. So my centering code was the reason I even came upon this. 

I'm sorry for the incomplete report.

**Comment by MyreMylar** [comment]
I had a tinker around with it and for a while I could reproduce - until I downgraded back to 2.0.0.dev8.

It seems this bug vanishes when you upgrade pygame to 2.0.0.dev10 so that's handy. However it does still exist on the old rendering path using pygame 1.9.6 so I still want to squish it.

**Comment by MyreMylar** [comment]
The above PR should have squished this in pre-dev10 versions of pygame as well.

**Comment by ylenard** [comment]
It has. Closing.
