### ISSUE TITLE
Text alignment for UILabel

### ISSUE THREAD

**Issue by ylenard** [MyreMylar/pygame_gui#122]
**Is your feature request related to a problem? Please describe.**
It would simply be useful for aligning the text used to describe input fields.

**Describe the solution you'd like**
I'd like to be able to set `text_horiz_alignment`, `text_vert_alignment`, `text_horiz_alignment_padding`, `text_vert_alignment_padding` in the theme of a UILabel just like it's possible for a UIButton.

**Describe alternatives you've considered**
It can be done manually, but it would be a nice QoL improvement.

**Comment by karx1** [comment]
While you're waiting for 0.6.0, see #137
