### ISSUE TITLE
UIDropDownMenu bug, related to the new focus mechanism

### ISSUE THREAD

**Issue by ylenard** [MyreMylar/pygame_gui#126]
**Describe the bug**
I believe I found a bug in the UIDropDownMenu (on the current master). The menu won't expand when the options list is bigger than expansion_height_limit.
For example - this will bug out:

```
import pygame
from pygame_gui import UIManager
from pygame_gui.elements import UIDropDownMenu

pygame.init()

test_surface = pygame.display.set_mode((800, 600), 0, 32)
test_surface.fill(pygame.Color(128, 128, 128, 255))

manager = UIManager((800, 600))

options_list = [f"option {x}" for x in range(20)]
dropdown = UIDropDownMenu(options_list, "option 0", relative_rect=pygame.Rect(50, 50, 400, 50),
                          manager=manager, expansion_height_limit=100)

running = True
time = 0.0
while running:
    test_surface.fill(pygame.Color(128, 128, 128, 255))
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        manager.process_events(event)

    manager.update(0.001)
    time += 0.001
    manager.draw_ui(test_surface)
    pygame.display.update()
```
but if you change the options_list to:
`options_list = [f"option {x}" for x in range(3)]`
it won't.

After some not so short investigation (I thought it was due to my code) it turned out that the unfocus() method of UIDropDownMenu is called immediately after it changes it's state to "expanded". I can see that some UIButton is stealing the focus, but I couldn't figure out what UIButton it is, so I got stuck in my investigation.

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version: 2.0.0. dev 10
 - Pygame version: current master

If that's not the correct place to report bugs in the unreleased version, than please point me in the right direction.

**Comment by MyreMylar** [comment]
It's fine to report bugs for _any_ version here, so long as we know what version we're dealing with so it can be tracked down. 

In fact, it is preferable to catch bugs in master before a release to the general public.

**Comment by ylenard** [comment]
Great, it works! So I'll go ahead and close the issue.
