### ISSUE TITLE
Slider with Constraints

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#130]
**Is your feature request related to a problem? Please describe.**
Limiting selection of a value to a range. 

**Describe the solution you'd like**
I want to be able to select a value between two pre-set bounds. 

**Describe alternatives you've considered**
Adding input validation to an input box.

**Comment by MyreMylar** [comment]
Doesn't the slider already work like this?

See `value_range`:

https://github.com/MyreMylar/pygame_gui/blob/43807e714997241ac33bce22d78328731449587f/pygame_gui/elements/ui_horizontal_slider.py#L15-L40

Or do you mean something different?

**Comment by Snayff** [comment]
Nope, that's exactly what I meant! Sorry, buddy. I must have missed it in the docs.
