### ISSUE TITLE
UIScrollingContainer, scroll bar disappear right after clicking

### ISSUE THREAD

**Issue by sakuya9t** [MyreMylar/pygame_gui#132]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a UIScrollingContainer, bind a UIVerticalScrollBar to it
2. click on down arrow of UIVerticalScrollBar
3. the scroll bar disappears

**Expected behaviour**
the scroll bar doesn't disappear, the container scrolls down a little bit.

**Screenshots**

**Additional context**
ui_scrolling_container.py:74
ui_scrolling_container.py:89
Because both view_rect  and scrollable_rect are initialized to the same size, self.scrolling_height is always the component height. As a result, _check_scroll_bars_and_adjust function will always return false.

**Comment by MyreMylar** [comment]
This container isn't explained particularly well yet, but the basic idea of it is that the scrollbars are supposed to vanish when the `view_rect` and the `scrollable_rect` are the same size. To use it right now you have to use the method `set_scrollable_area_dimensions()` yourself, something like this:

        self.scrolling_container = UIScrollingContainer(relative_rect=container_rect,
                                                        manager=self.ui_manager,
                                                        container=self,
                                                        anchors={'left': 'left',
                                                                 'right': 'right',
                                                                 'top': 'top',
                                                                 'bottom': 'bottom'})

        self.scrolling_container.set_scrollable_area_dimensions((image.get_width() + 20,
                                                                 image.get_height() + 20))


That said, it sounds odd that a scrollbar appears when you initialise it without setting the scrollable area - I would expect it to behave like a normal container when the dimensions of both areas was the same. I'll investigate it a bit.

**Comment by sakuya9t** [comment]
Thank you this works for me. But I suggest we can have two optional parameters on UIScrollingContainer, which indicate the scrollable area size.

In addition, if we want to adjust the scrollable area size according to the children components, we could calculate the inner area size and set it there. That would be great.
