### ISSUE TITLE
Wrap text in UILabel

### ISSUE THREAD

**Issue by karx1** [MyreMylar/pygame_gui#137]
**Is your feature request related to a problem? Please describe.**
Currently, when the char limit is exceeded, text is just hung off the side.

**Describe the solution you'd like**
Text is wrapped when char limit is exceeded

**Describe alternatives you've considered**
I could manually do it with the Python textwrap module and whatever sequence you use to make a new line in a UILabel, but I don't know what that sequence is

**Comment by karx1** [comment]
Or, if you could just tell me how to get a new line in a UILabel I'll close this issue and do it myself with textwrap

**Comment by MyreMylar** [comment]
Have you tried the UITextBox?

https://pygame-gui.readthedocs.io/en/latest/theme_reference/theme_text_box.html

It is essentially a UILabel but with word wrapping, though there are a few feature disparities between the two that I hope to eliminate in the next text refactor.

**Comment by karx1** [comment]
@MyreMylar thanks! I'm looking into the UITextBox. Is there a way to dynamically update the UITextBox text? When I use `set_text(text)` PyCharm tells me that UITextBox has no attribute set_text.

**Comment by karx1** [comment]
Maybe I could manually set the `box.html_text` attribute?

**Comment by MyreMylar** [comment]
The text box isn't the fastest for changing the text in the box at the minute, that's one of the things I hope to improve in the big text refactor in version 0.6.0.

That said I think if you change what is in `box.html_text` and then call `box.rebuild` it should work.

If you are trying to build something like a console, or terminal then there are a couple of other issues complaining about difficulties with that and it is one of the target examples for 0.6.0.

**Comment by karx1** [comment]
Cool, that seems to work. Do you have an ETA for 0.6.0?

**Comment by MyreMylar** [comment]
> Do you have an ETA for 0.6.0?

Nope. Other than it is currently planned to be the release after 0.5.7 (which is the next one - we are on 0.5.6 publicly right now). Then again I didn't intend to do 0.5.7 really, I just got pulled into a rabbit hole chasing some bugs and issue reports and suddenly there was a bunch of new code that needs releasing.

I'll tentatively estimate 'this year' but it could be a lot sooner or later in the year depending on how things shake out with the pandemic/other projects/etc

**Comment by MyreMylar** [comment]
You can look at the project board for 0.6.0 here:

https://github.com/MyreMylar/pygame_gui/projects/2

But it's not very exciting yet because nothing has started.
