### ISSUE TITLE
Button updates time itself

### ISSUE THREAD

**Issue by Ztaoxx** [MyreMylar/pygame_gui#139]
**Describe the bug**
i'm working on Clicker Game and cash is adding once in a second by pygame.event.set_timer(), unlikely, when i hover or click on Button created by Gui it update cash by itself, and have no clue why it does like that

**To Reproduce**
Steps to reproduce the behaviour:
1. 
2.
3.

**Expected behaviour**
The button would not update time itself.

**Screenshots**

added a video:
https://streamable.com/k74j7h

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version Newest One
 - Pygame version Newest on

**Additional context**

**Comment by MyreMylar** [comment]
You haven't provided any code or way I can reproduce this so I'll have to guess what is going on from the video.

I'm assuming you are using `pygame.time.set_timer()` to generate events with the type `pygame.USEREVENT` with no other data? 

pygame_gui also generates events with that event code, so you'll need to distinguish between the pygame_gui events and your clicker events. for pygame_gui I have a second parameter on the  event called `user_type` which lets be distinguish between button presses, hover events etc. You could use this exact same parameter name, or perhaps one of your own (e.g. `game_event`) to distinguish your own events.

**Comment by Ztaoxx** [comment]
Forgot about code, sorry.
Providing one:
https://pastebin.com/u/Akushima

all files here are in my code

**Comment by MyreMylar** [comment]
Have you solved you error now? I can see in the code where you define all your events to be the same thing here:

```
    add_cash = pygame.USEREVENT
    button_test = pygame.USEREVENT
```

The easiest fix is to instead do:

```
    add_cash = pygame.USEREVENT + 1
    button_test = pygame.USEREVENT + 2
```

**Comment by Ztaoxx** [comment]
Okay, gonna check it in a while and will say if it works

**Comment by Ztaoxx** [comment]
Oh, One more question, any idea why user_type gives me Attribute error?

**Comment by MyreMylar** [comment]
> Oh, One more question, any idea why user_type gives me Attribute error?

It only exists by default on the pygame_gui events so if you manually create other events that use the type pygame.USEREVENT then they won't have it. If you have got rid of all other events using pygame.USEREVENT then it should be fine to check it after checking _first_ that the event's type is pygame.USEREVENT.

So it would go:

```
for event in pygame.event.get()
    if event.type == pygame.USEREVENT:
        # Assuming only pygame_gui events are now using the pygame event type
        if event.user_type == pygame_gui.UI_BUTTON_PRESSED:
             # check which button is pressed here
             if event.ui_element == test_button:
                 # do something when this button is pressed
```

This is documented here:
https://pygame-gui.readthedocs.io/en/latest/events.html
