### ISSUE TITLE
AttributeError: 'Buttons' object has no attribute 'redraw'

### ISSUE THREAD

**Issue by Ztaoxx** [MyreMylar/pygame_gui#140]
**Describe the bug**
AttributeError: 'Buttons' object has no attribute 'redraw'

**To Reproduce**
Steps to reproduce the behaviour:
1. While button is pressed, gain +1 Qty.
2. On hovered show tooltip how much Qty does button have
3. Update tooltip

**Expected behaviour**
Update tooltip to see proper number of Quanities.
Tried to use redraw() functions but got Attriibute Error:

**Screenshots**
Video:
https://streamable.com/iaq9g9

**Platform and software (please complete the following information):**
 - OS: Windows 10
 - Pygame GUI version Newest one.
 - Pygame version Newest one.

**Additional context**
Code:
https://pastebin.com/cBSXJEJ4

**Comment by MyreMylar** [comment]
Updating the tool tips dynamically while hovering them is not a well supported feature right now.

Here is how to do it in a window I think:

```
def dynamic_tool_tip_set_text(button, new_text):
    button.tool_tip_text = new_text
    if button.tool_tip is not None:    
        button.tool_tip.text_block.html_text = button.tool_tip_text
        button.tool_tip.text_block.rebuild()
        button.tool_tip.set_dimensions(button.tool_tip.text_block.rect.size)
```

**Comment by Ztaoxx** [comment]
Hey, i was working so couldn't check it, but it didnt't work,but figured it somehow alone by button.tool_tip_text = next_text
so i just made something like that:
    def update_text(self):
        self.cost = float(round(self.cost,2))
        self.qty = float(round(self.qty,2))
        self.draw.tool_tip_text = 'Cost: {}, Qty: {}'.format(self.cost, self.qty)
and it work as it should, thank u so much 4 ur help. Keep up your good work.
Have a great night! :)
