### ISSUE TITLE
UIButton not visible, but registering mouse click

### ISSUE THREAD

**Issue by DeVitoC** [MyreMylar/pygame_gui#144]
**Describe the bug**
I am attempting to use Pygame_GUI to add buttons to a Game of Life program. While my app is a little more spread out than the example in the Getting Started Guide, I am pretty confident I have put all the elements in the correct places. I have also loaded a color theme to ensure that it should be different color than the background and have changed the color of my background to try to see the button. At this point, each line related to Pygame_GUI is exactly the same as in the start guide, except for loading a different theme, and placing the button in a different location on the screen. 

**To Reproduce**
Steps to reproduce the behaviour:
1. I started with a Pygame project that was working, set up as a class
2. I followed the Pygame_GUI Getting Started Guide
3. 

**Expected behaviour**
I expected to see a button with the text "Hello World"

**Screenshots**
![Screen Shot 2020-06-23 at 8 47 05 PM](https://user-images.githubusercontent.com/59913648/85483531-f8aa8980-b592-11ea-8165-323ca223a7ab.png)
![Screen Shot 2020-06-23 at 8 47 24 PM](https://user-images.githubusercontent.com/59913648/85483533-f9dbb680-b592-11ea-8870-ba44482a31fa.png)
![Screen Shot 2020-06-23 at 8 47 55 PM](https://user-images.githubusercontent.com/59913648/85483534-f9dbb680-b592-11ea-82c2-dc74245ea5b9.png)
![Screen Shot 2020-06-23 at 8 48 12 PM](https://user-images.githubusercontent.com/59913648/85483535-fa744d00-b592-11ea-91b2-b166bfdf4737.png)

**Platform and software (please complete the following information):**
 - OS: [e.g. Windows, Linux, Mac] Mac OSX 10.15.5
 - Pygame GUI version [e.g. 0.4.0] 0.5.6
 - Pygame version [e.g. 1.9.6] 2.0.0

**Additional context**

**Comment by MyreMylar** [comment]
Nothing immediately jumps out from the screen shots.

A couple of questions:

- Is your code uploaded anywhere on the internet so I could quickly try it out? 
- Does the basic code from the getting started guide work on it's own unchanged?

**Comment by DeVitoC** [comment]
So, I thought I had everything in the right places, and had commented it out to try something else. Going back to uncomment them to push them to github, I realized that I was calling my draw_board method after setting this, and the first line of my draw_board method clears the screen first.... I apologize for thinking this was a bug. It's simply me putting it in the wrong place. Placing the call to setup the buttons in the draw_board method instead of before it works fine now.
