### ISSUE TITLE
Inner Element Forced to Draw Outside of Outer Element

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#146]
**Describe the bug**
When a `ui_element` is contained inside another one the left-most border of the inner element is drawn 1 pixel across. This creates a double line and ensures that if the inner element has the same width as the outer it will exceed the right side by 1 pixel.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Create UI Panel class
2. Inside that create a UITextbox using `container=self.get_container()`
3.

**Expected behaviour**
Position of draw should match, including if it is covered by the outer border. So, if the inner element should draw at `x=0` then you should not see the border of the inner element, you should only see the border of the outer.

**Screenshots**
https://i.imgur.com/BLUaqQZ.png (zoomed in)
https://i.imgur.com/tX4aHm5.png (example one)
https://i.imgur.com/jUsa9Mb.png (example two)

**Platform and software (please complete the following information):**
 - OS: Windows 10 64bit
 - Pygame GUI version: 0.5.7
 - Pygame version: 2.0.0.dev 10

**Comment by MyreMylar** [comment]
At a guess that's likely to be the 'shadow_width', I think you should be able to theme it to zero for the text box.

**Comment by Snayff** [comment]
Sorry for the delay on this, I checked your suggestion but forgot to feedback. Setting `shadow_width` or `border_width` to 0 didn't help.

**Comment by MyreMylar** [comment]
Works for me. 

Here's the theme file:

```
{
    "panel.text_box": {
        "misc": {
            "shape": "rectangle",
            "shape_corner_radius": "0",
            "border_width": "0",
            "shadow_width": "0",
            "padding": "10,10"
        }
    }
}
```

And here's the code I was using:

```
import pygame

from pygame.rect import Rect
from pygame.color import Color
from pygame.surface import Surface

from pygame_gui import UIManager
from pygame_gui.elements import UIPanel
from pygame_gui.elements import UITextBox


pygame.init()

display_surface = pygame.display.set_mode((800, 600))

ui_manager = UIManager((800, 600), 'data/themes/test_theme.json')

background = Surface((800, 600), depth=32)
background.fill(Color("#FFFFFF"))

panel = UIPanel(Rect(50, 50, 400, 500),
                starting_layer_height=4,
                manager=ui_manager)

text_box = UITextBox(
        html_text="On the other hand, we denounce with righteous indignation and "
                  "dislike men who are so beguiled and demoralized by the charms "
                  "of pleasure of the moment, so blinded by desire, that they cannot "
                  "foresee the pain and trouble that are bound to ensue; and equal "
                  "blame belongs to those who fail in their duty through weakness of "
                  "will, which is the same as saying through shrinking from toil and "
                  "pain. These cases are perfectly simple and easy to distinguish. "
                  "In a free hour, when our power of choice is untrammelled and when "
                  "nothing prevents our being able to do what we like best, "
                  "every pleasure is to be welcomed and every pain avoided. But "
                  "in certain circumstances and owing to the claims of duty or the "
                  "obligations of business it will frequently occur that pleasures "
                  "have to be repudiated and annoyances accepted. The wise man therefore "
                  "always holds in these matters to this principle of selection: he "
                  "rejects pleasures to secure other greater pleasures, or else he "
                  "endures pains to avoid worse pains",
        relative_rect=pygame.Rect(0, 0, 400, -1),
        container=panel,
        manager=ui_manager)

is_running = True

while is_running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            is_running = False

        ui_manager.process_events(event)

    display_surface.blit(background, (0, 0))

    ui_manager.update(0.01)
    ui_manager.draw_ui(window_surface=display_surface)

    pygame.display.update()

```

And how it looks:

![image](https://user-images.githubusercontent.com/13382426/88674349-9db00900-d0e1-11ea-8b98-971f5d0e568a.png)

**Comment by Snayff** [comment]
Finally sorted it. `text_box` was listed in `combined_element_ids` but the `text_box` in theme.json wasnt being picked up for some reason. Removing the `object_id` assignment allowed it to be picked up and then what you suggested worked perfectly.
