### ISSUE TITLE
Typing Error with Container

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#147]
**Describe the bug**
Typing warning. `Expected type 'Optional[IContainerLikeInterface]', got 'IUIContainerInterface' instead` on `container=self.get_container()`.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Create UIImage (or UITextbox) with `container=self.get_container()`

**Platform and software (please complete the following information):**
- OS: Windows 10 64bit
- Pygame GUI version: 0.5.7
- Pygame version: 2.0.0.dev 10

**Comment by MyreMylar** [comment]
Is there a bit more code context than what you posted above? I'm fairly sure you can stick images and text boxes inside panels and windows. 

What exactly are you trying to do?

**Comment by Snayff** [comment]
Sorry mate, here're two uses. Both of these throw a typing error on the `container` argument, as detailed above. 
```
class TileInfo(UIPanel):
    def __init__(self, rect: pygame.Rect, manager: UIManager):
     ui_image = UIImage(relative_rect=image_rect, image_surface=image, manager=self.ui_manager, container=self.get_container())
    ui_text = UITextBox(html_text=text, relative_rect=rect, manager=self.ui_manager,
                              wrap_to_height=True, layer_starting_height=1,
                              container=self.get_container())

```

**Comment by Snayff** [comment]
Can I give any more info on this that would help?

**Comment by MyreMylar** [comment]
I believe you just need to change it to something like this:

```
class TileInfo(UIPanel):
    def __init__(self, rect: pygame.Rect, manager: UIManager):
        super().__init__(relative_rect=rect, starting_layer_height=1, manager=manager)
        
        ui_image = UIImage(relative_rect=image_rect,
                           image_surface=image,
                           manager=self.ui_manager,
                           container=self)
        ui_text = UITextBox(html_text=text, relative_rect=rect, manager=self.ui_manager,
                            wrap_to_height=True, layer_starting_height=1,
                            container=self)
```

If I understand your intent correctly. At some point the container interface was changed to be more natural so you don't need to call `get_container()` from objects that are already container-like such as panels and windows. Not sure if you had skipped the `super().__init__()` call in your posted code or not.

**Comment by Snayff** [comment]
Spot on, thanks mate. All my assignments to `container` were`self.get_container()` and amending to just `self` removed the typing error without any issues.
