### ISSUE TITLE
Right/Middle Click UI Event

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#148]
**Is your feature request related to a problem? Please describe.**
Currently no way  to catch when a user  clicks a UI button with a mouse button other than left. 

**Describe the solution you'd like**
Create other events for right/middle mouse or add an input param to UI_BUTTON_PRESSED event.

**Additional context**
Not sure how this will work with other devices, such as gamepad or keyboard.

**Comment by MyreMylar** [comment]
I think this is probably reasonable, 'buttons' as originally conceived have grown in scope to also encompass things like icons which have a right click function even if things like 'OK' and 'Cancel' buttons normally don't. I may add it as a non-default option to let people choose whether to pass right clicks to the UI or reserve them entirely for their own nefarious purposes.
