### ISSUE TITLE
Drop Down Menu expansion_height_limit is limited.

### ISSUE THREAD

**Issue by jordan-gleeson** [MyreMylar/pygame_gui#151]
**Describe the bug**
The UIDropDownMenu element has a field called expansion_height_limit, that by default, seems to be a function of how many objects are in options_list. As quoted in the doc: "defaults to the container bounds". My problem is that I can't seem to expand past the default limit. I can make it smaller with no issues, but never larger. I require this as I have increased "list_item_height" in the theme, but the default "container bounds" is smaller than my UISelectionList total height.

**Expected behaviour**
Setting expansion_height_limit in UIDropDownMenu to a large number should increase the available size for options in the drop down menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/1331419/87529365-428a1980-c6d2-11ea-9aa0-8c033361e069.png)
(This is when the expansion_height_limit is set to 150, which should result in a much larger box)

**Platform and software (please complete the following information):**
 - OS: Windows 10
 - Pygame GUI version 0.5.6
 - Pygame version 1.9.6

**Comment by MyreMylar** [comment]
Does this mean you have your drop down stuck in a small container for some reason? I think that will be your main problem as elements are always clipped to their containers to stop things like elements overlapping the edges of windows. 

To make your drop down longer you will need to expand the container it is inside of.

**Comment by jordan-gleeson** [comment]
The drop down's container is not specified, left at default. It also expands somewhat depending on how many items on the list so it doesn't seem like a container limitation. Some more examples where list_item_height is 25 and the only parameter I'm changing is the length of the options_list.
![image](https://user-images.githubusercontent.com/1331419/87610187-02fe1480-c748-11ea-9f86-7f78203ceee6.png)
![image](https://user-images.githubusercontent.com/1331419/87610197-10b39a00-c748-11ea-9450-f32228bea886.png)
![image](https://user-images.githubusercontent.com/1331419/87610222-1e691f80-c748-11ea-8e66-b79e3c9bdf23.png)
![image](https://user-images.githubusercontent.com/1331419/87610234-2cb73b80-c748-11ea-83c2-53bfda747f92.png)

So as you can see, the size is expanding with each new option, but it is still hitting a maximum as expansion_height_limit is set to a large number in all of these screenshots.

**Comment by MyreMylar** [comment]
Ah hang on, you are still on 0.5.6. I think this is a bug that was fixed with the round of changes to drop downs in 0.5.7. I would try updating to 0.5.7 and see if it works correctly.

**Comment by jordan-gleeson** [comment]
Ah perfect. Thankyou!
