### ISSUE TITLE
Where did the manager.load_theme() go?

### ISSUE THREAD

**Issue by jackiboi307** [MyreMylar/pygame_gui#157]
In the docs, in the theme guide, there's a tutorial on how to split themes into multiple files with the load_theme() method.
But it appears to not even exist, and it isn't listed in the docs for the UIManager class either.
Please bring it back, i need it!

**Comment by MyreMylar** [comment]
It exists, its just in the UIAppearanceTheme class. Here:

https://github.com/MyreMylar/pygame_gui/blob/bc2f1eb5309382ba46efdd04f2f8c1b65ca8275b/pygame_gui/core/ui_appearance_theme.py#L635

You can grab the theme class from the UIManager with `get_theme()`

**Comment by jackiboi307** [comment]
Thanks!

**Comment by jackiboi307** [comment]
When i do load_theme(path) as the docs says, it appears that path is passed to the self parameter.
And when i do file_path=path, then i get an error saying:
`TypeError: load_theme() missing 1 required positional argument: 'self'
`
