### ISSUE TITLE
Text in UI Elements Doesnt Upscale Well

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#158]
**Describe the bug**
When scaling the pygame main surface the text on the UI elements (label, textbox, button) becomes fuzzy.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Create main surface at base resolution. 
2. Create UI Textbox (or label or button)
3. Blit to main surface.
4. Scale main surface ( `pygame.transform.scale(main_surface, (self._desired_width, self._desired_height))` )

**Expected behaviour**

**Screenshots**
No scaling (top text is pygame.font render, bottom is UI TextBox):
![image](https://user-images.githubusercontent.com/23128268/94735500-c6af7d00-0362-11eb-8328-b4a88ae59f7d.png)

Upscaled  (top text is pygame.font render, bottom is UI TextBox):
![image](https://user-images.githubusercontent.com/23128268/94735444-aed7f900-0362-11eb-93d9-ccf7b9d4731c.png)

Upscaled again, with bigger font for ui element:
![image](https://user-images.githubusercontent.com/23128268/94736050-8a305100-0363-11eb-92b5-4ba2b1f82e40.png)

**Platform and software (please complete the following information):**
OS = Windows
pygame = "2.0.0dev10"
pygame-gui = "^0.5.6"

**Additional context**
Base resolution: 640x320
Upscaled resolution: 1280x640

**Comment by MyreMylar** [comment]
Don't think there is much I can do about that from my end. I assume the pygame rendered font font looks better scaled up with `transform.scale()` because it is not anti-aliased and already in a blocky style. I will try to add an option to disable anti-aliasing when loading fonts but that will also change how it looks after scaling.

Things you could try:

 - Drawing the UI _after_ scaling. As in you scale up the game world and then draw the UI elements at the native frame rate. Depending on how complex the UI is and what you are using it for this might work OK.
 - Changing to use a blocky font.
 - Switching to using `pygame.transform.smoothscale()` This will scale the screen with some anti-aliasing applied and may look a bit better.

**Comment by Snayff** [comment]
Good suggestions, cheers buddy. I'll give it a go. I think your first suggestion is probably the "right" way forward, but might be finicky.

**Comment by MyreMylar** [comment]
You could also experiment with the SCALED flag to `set_mode()` which does some amount of upscaling for you for 'free' (it uses hardware acceleration) - though it is less in your control.

**Comment by Snayff** [comment]
Tried drawing the gui after the scaling but because I am using a UIImage and the image inside that doesn't scale that doesn't quite work. Adding  `SCALED` to `set_mode()` resizes everything fairly well, *except* for the text in the pygame-gui elements, which goes fuzzy again. 

Weirdly, my attempts to resize the surface before passing to the UIImage mentioned before *does* scale but seemingly moves the surface within the UIImage, i.e. drawing from a position other than the `(0,0)` specified in the `relative_rect`. I tried scaling the UIImage with set dimensions, which didn't work as intended (can't remember why, unfortunately) but because this is for my camera it isn't ideal, anyway. 

This is definitely something for me to solve my end, I just wanted to share the feedback in case it helps. :)

**Comment by Snayff** [comment]
OK, @MyreMylar, would you mind taking a look to see if I am missing something with how I am using the [UI Manager](https://github.com/Snayff/notquiteparadise/blob/feature/ui_render_step/scripts/engine/ui/manager.py#L113) or the [UIImage](https://github.com/Snayff/notquiteparadise/blob/feature/ui_render_step/scripts/engine/ui/elements/camera.py#L302)? I've written up the details [here](https://github.com/Snayff/notquiteparadise/issues/111). The surface in the UI Image appears to move left during the scaling but I only specify `(0, 0)` as the xy for the relative rect. I've even tried creating a new `UIImage` every frame, but that's the same result.

**Comment by MyreMylar** [comment]
Have you tried just calling `set_dimensions()` on your UIImage? that should make sure the Rects and the image are all the same size.

**Comment by Snayff** [comment]
Yeah, but I tried again to be sure and it actually renders **nothing** ! 
![image](https://user-images.githubusercontent.com/23128268/95660449-e93e5480-0b1f-11eb-8626-ffa824439c63.png)

```
    def _update_game_map(self):
        """
        Update the game map to show the current tiles and entities
        """
        # create new surface for the game map
        map_width = self._base_width
        map_height = self._base_height
        map_surf = Surface((map_width, map_height), SRCALPHA)

        # draw tiles
        for tile in self.current_tiles:
            self._draw_surface(tile.sprite, map_surf, (tile.x, tile.y))

        # draw entities
        from scripts.engine.core import queries

        for entity, (pos, aesthetic) in queries.position_and_aesthetic:
            # if part of entity in camera view
            for offset in pos.offsets:
                src_area = Rect(offset[0] * TILE_SIZE, offset[1] * TILE_SIZE, TILE_SIZE, TILE_SIZE)
                position = (pos.x + offset[0], pos.y + offset[1])
                draw_position = (aesthetic.draw_x + offset[0], aesthetic.draw_y + offset[1])
                if self.is_in_camera_view(position):
                    tile = world.get_tile(position)
                    if tile.is_visible or self.ignore_fov:
                        self._draw_surface(aesthetic.current_sprite, map_surf, draw_position, src_area)

        self.game_map.set_image(map_surf)
        desired_size = library.VIDEO_CONFIG.desired_window
        self.game_map.set_dimensions((desired_size.width, desired_size.height))
```
