### ISSUE TITLE
[Question] How to set the font of a UIDropDownMenu?

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#159]
I've tried adding a `font` block to the  `drop_down_menu` block in the `theme.json` but that didnt have any effect. Not sure how to increase the size without actually amending the dropdown via code. 

I hope you dont mind me asking a question this way, I wasnt sure how best to put it to you.

**Comment by MyreMylar** [comment]
Right now:

```
    "#drop_down_text_prototype":
    {
        "font":
        {
                "name": "montserrat",
                "size": "12",
                "bold": "0",
                "italic": "1",
                "regular_resource": { "package": "data.fonts", "resource": "Montserrat-Regular.ttf"},
                "bold_resource": { "package": "data.fonts", "resource": "Montserrat-Bold.ttf"},
                "italic_resource": { "package": "data.fonts", "resource": "Montserrat-Italic.ttf"},
                "bold_italic_resource": { "package": "data.fonts", "resource": "Montserrat-BoldItalic.ttf"}

        }
    },
    "drop_down_menu.button":
    {
        "prototype": "#drop_down_text_prototype"
    },
    "drop_down_menu.#drop_down_options_list.button":
    {
        "prototype": "#drop_down_text_prototype"
    }
```

Is the briefest way to change the font on all the drop down buttons, on all drop downs I believe. I think I'll probably add one of the new `@class_id_name` theming ID things at some point, like I have for the arrow buttons, to make it easier.

**Comment by Snayff** [comment]
Thanks buddy!
