### ISSUE TITLE
UIPanel Ignoring Border Colour and Size

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#160]
**Describe the bug**
UIPanel not respecting the border colour or size being given.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Create new class, inheriting from UIPanel.
2. Create the default `panel` block
3. Update the `panel`s `colours` block in `theme.json`.

**Expected behaviour**
Expected border to be white in the image below, as set in the panel's colours block.

**Screenshots**
Outer edge is around a UIPanel (this [one](https://github.com/Snayff/notquiteparadise/blob/develop/scripts/engine/ui/elements/title_screen.py))
![image](https://user-images.githubusercontent.com/23128268/95024800-5748ce80-067d-11eb-9972-c9703641dac8.png)

**Platform and software (please complete the following information):**
 - OS: Windows 10]
pygame = "2.0.0dev10"
pygame-gui = "^0.5.6"

**Comment by MyreMylar** [comment]
I suspect that's because you gave it a new `element_id` here:

`element_id="title_screen"`

If you change your theme file above to:

```
"title_screen": {
    "colours": {
        "normal_border": "#ffffff",
        "dark_bg":"#c21515"
    },
    "misc": {
        "shadow_width": 0,
        "border_width": 0
   }
},
```

I think it would work.

**Comment by Snayff** [comment]
Oh, so `panel` applies to UIPanels that have their default object I'd?

**Comment by MyreMylar** [comment]
Yep, when inheriting or making a new UIElement class you can give it a new element ID to indicate that it is a distinct thing in your design. For example if I inherited from UIButton to make a UIRadioButton I might change the `element_id` to `radio_button` so I could theme regular buttons and radio buttons differently easily across the whole UI.

If you want an inherited class to still be basically a `panel` you could just give it a custom `object_id` instead or even a new `class_id` with the `ObjectID` class. For example you could have a Class with a class_id `@menu_screen` that has an `element_id` `panel` and an `object_id` of `#title_screen`. 

```
 class TitleScreen(UIPanel):
    """
    Initial screen menu
    """

    def __init__(self, rect: Rect, manager: UIManager):

        super().__init__(rect, RenderLayer.BOTTOM, manager, object_id=ObjectID("#title_screen", "@menu_screen")

....

 class OptionsScreen(UIPanel):
    """
    Initial screen menu
    """

    def __init__(self, rect: Rect, manager: UIManager):

        super().__init__(rect, RenderLayer.BOTTOM, manager, object_id=ObjectID("#options_screen", "@menu_screen")

```

```
"panel": {
    "misc": {
        "shadow_width": 0,
        "border_width": 0
   }
},
"@menu_screen": {
    "colours": {
        "normal_border": "#ffffff",
        "dark_bg":"#c21515"
    }
},
"#title_screen": {
    "colours": {
        "normal_border": "#0000ff"
    }
},
"#options_screen": {
    "colours": {
        "normal_border": "#00ffff"
    }
}
```

The priority of the theming parameters is from most specific to least specific, so stuff under `#title_screen` will be respected first, then down to anything under `@menu_screen` and finally down to `panel` as the last resort.

**Comment by MyreMylar** [comment]
Whether you use new elements or class IDs or lots of instances IDs, its basically a judgement call for the user to decide how they think about their UI design I suppose, and what makes sense with how many of each type of thing you have.

Ideally Pygame GUI is fairly scalable up from GUIs with just a handful of buttons to things with hundreds of different UI objects.

**Comment by Snayff** [comment]
Understood! Thank you.
