### ISSUE TITLE
Item inside UIDropDownMenu should auto scroll to and selected when in expanded state

### ISSUE THREAD

**Issue by xlla** [MyreMylar/pygame_gui#161]
**Is your feature request related to a problem? Please describe.**
If UIDropDownMenu has many items, whenever I click the expand button, it just shows item start from index 0 of options_list whatever the item I have chosen.

**Describe the solution you'd like**
the UIExpandedDropDownState should find the right item of selected_option, then focus/select it, if it is not in visible area, auto scroll to right pos.

**Describe alternatives you've considered**
None

**Additional context**
can be observed on pygame_gui_examples/general_ui_test_app.py , test_drop_down_menu, expand it, choice item 28, close it , expand again, just show item1~item7

**Comment by MyreMylar** [comment]
Thanks for the idea. 
 think it makes sense for most use cases to scroll the options to include the last selected item if it's not already visible.

**Comment by xlla** [comment]
For better user experience, the last selected item in visible area should got selected automatic.
It's great if UIDropDownMenu could support select()/unselect().

Meanwhile, I am work with a tiny lcd without mouse/keyboard, only a few gpio buttons, with or without touch input, I want to emulate focus in/out effect to implement navigation GUI, I have to trace down the lowest UIButton element, and call select()/unselect() on it.
![dropdownmenu](https://user-images.githubusercontent.com/3354817/97272261-99c08e00-186c-11eb-8451-dff2fa444a8c.png)
