### ISSUE TITLE
How to make a Transparent UIElement

### ISSUE THREAD

**Issue by xlla** [MyreMylar/pygame_gui#162]
Is there any example can shows how to make a transparent UIElement?
I saw changelog v0.3.0 mentioned 

>  ... UI Elements now all support transparency

I want to make a semi-transparent GUI overlay an image or a video.

**Comment by MyreMylar** [comment]
Usually you just set the colours of the elements with an alpha colour channel (the fourth one) in whatever colour format. e.g.:

```
white_no_alpha = (255, 255, 255)
white_semi_transparent = (255, 255, 255, 128)

white_no_alpha = '#FFFFFF'
white_semi_transparent = '#FFFFFF80'
```

So in a theme file, something like this:

```
    "#my_semi_transparent_button":
    {
        "prototype": "#gui_buttons",

        "colours":
        {
            "normal_border": "#FF000080",
            "normal_bg": "#FFFFFF80",
            "normal_text": "#00000080"
        }
    }
```

**Comment by xlla** [comment]
@MyreMylar got it, Thanks a lot!
