### ISSUE TITLE
Let UIDropDown's close_button_width/open_button_width be settable in a theme file

### ISSUE THREAD

**Issue by xlla** [MyreMylar/pygame_gui#163]
I am work on a tiny LCD and use 5 gpio button for gui navigation, so the default width 20 is too large.

I have to manual change width in each state and invoke update_dimensions.
It is great if this width would available in UIDropDown's construction args.

**Comment by MyreMylar** [comment]
Yeah, this should probably be a theming parameter. I'll make this issue into a feature request.

For now, I think you should be able to set the `.menu_states['closed'].open_button_width` and `.menu_states['expanded'].close_button_width` attributes of each drop down and call `.rebuild()` on them.

**Comment by xlla** [comment]
Yes, I am just do it in that way, and consider extend UIDropDown to make life easy.

**Comment by MyreMylar** [comment]
This will make it into 0.6.0.
