### ISSUE TITLE
'UIImage' object has no attribute 'ui_container'

### ISSUE THREAD

**Issue by xlla** [MyreMylar/pygame_gui#164]
**Describe the bug**
I am work on a system without keyboard and mouse.
while try to put a UIPanel inside another UIPanel to emulate a Tabbed widget.
sudden a lot of repeat exception raised.

<pre>
3262-MainThread 2020-11-06 01:34:43,069 piCameraApp.py:143 mainloop     ERROR - 'UIImage' object has no attribute 'ui_container'
Traceback (most recent call last):
  File "piCameraApp.py", line 141, in mainloop
    self.manager.update(time_delta)
  File "/usr/lib/python3.7/site-packages/pygame_gui/ui_manager.py", line 248, in update
    element_handled_hover = ui_element.check_hover(time_delta, hover_handled)
  File "/usr/lib/python3.7/site-packages/pygame_gui/core/ui_element.py", line 508, in check_hover
    self.hover_point(mouse_x, mouse_y) and
  File "/usr/lib/python3.7/site-packages/pygame_gui/core/ui_element.py", line 572, in hover_point
    if self.ui_container is not None:
AttributeError: 'UIImage' object has no attribute 'ui_container'
</pre>

**To Reproduce**
Steps to reproduce the behaviour:
1. 
2.
3.

**Expected behaviour**
No exception raise

**Screenshots**

**Platform and software (please complete the following information):**
 - OS: [Linux]
 - Pygame GUI version [0.5.7]
 - Pygame version [2.0.0.dev12]

**Additional context**

**Comment by MyreMylar** [comment]
Hmm, this looks like a bug that maybe gets triggered when something is set as the container that is not a container type element. 

What's supposed to happen then is that `self.ui_container` defaults to None, but it looks like what actually happens is that it never gets set at all. I would check what is being passed as the `container` parameter of your `UIImage`. It needs to be something that is of type `IContainerLikeInterface`. `UIPanel` and `UIWindow` inherit from this as does `UIContainer`.

**Comment by xlla** [comment]
I have set UIImage's container to another UIPanel L01, to hidden everything, I have create L01 with visible=False.

I found two UIImage has overlap each other, after rearrange its,  exception was gone.
