### ISSUE TITLE
Error PyInstaller default theme

### ISSUE THREAD

**Issue by MauGame** [MyreMylar/pygame_gui#166]
**Describe the bug**
pygame_gui/core/ui_font_dictionary.py:116: UserWarning: Unable to load resource with path: <pygame_gui.core.utility.PackageResource object at 0x7f09ac2cc8e0>
Traceback (most recent call last):
  File "importlib/resources.py", line 131, in open_text
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIFZhSFl/pygame_gui/data/default_theme.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 198, in <module>
  File "main.py", line 156, in iniciar
  File "main.py", line 40, in configuracion_GUI
  File "pygame_gui/ui_manager.py", line 54, in __init__
  File "pygame_gui/core/ui_appearance_theme.py", line 101, in __init__
  File "pygame_gui/core/ui_appearance_theme.py", line 113, in _load_default_theme_file
  File "pygame_gui/core/ui_appearance_theme.py", line 645, in load_theme
  File "importlib/resources.py", line 169, in read_text
  File "importlib/resources.py", line 145, in open_text
FileNotFoundError: 'default_theme.json' resource not found in 'pygame_gui.data'

**To Reproduce**
Steps to reproduce the behaviour:
1. 
2.
3.

**Expected behaviour**

**Screenshots**
https://ibb.co/R6gqNyY

**Platform and software (please complete the following information):**
 - OS: Kubuntu 20.04
 - Pygame GUI version 
 - Pygame version pygame 2.0.0 (SDL 2.0.12, python 3.8.5)

**Additional context**
[Add any other context about the problem here.

**Comment by MyreMylar** [comment]
Yeah, I had this reported somewhere, but I guess it wasn't on GitHub

I think PyInstaller is probably excluding non-py files when deciding what files to copy from a package - which is unfortunate for a data package. I'll probably have to create a pyinstaller specific hook file which is mildly annoying as the whole point of using importlib is to have a standard pythonic way to import data without getting involved with a file system.

**Comment by MauGame** [comment]
> Yeah, I had this reported somewhere, but I guess it wasn't on GitHub
> 
> I think PyInstaller is probably excluding non-py files when deciding what files to copy from a package - which is unfortunate for a data package. I'll probably have to create a pyinstaller specific hook file which is mildly annoying as the whole point of using importlib is to have a standard pythonic way to import data without getting involved with a file system.

The problem is in the --onefile,
The solution I could do was, use the pyinstaller github example in its normal version, create a Data Tree, and then copy the pygame_gui.data.default_theme.json file from pip with its derivatives that are the fonts.

but unfortunately I have not yet been able to create it in 1 single file

**Comment by aefader00** [comment]
> 
> 
> > Yeah, I had this reported somewhere, but I guess it wasn't on GitHub
> > I think PyInstaller is probably excluding non-py files when deciding what files to copy from a package - which is unfortunate for a data package. I'll probably have to create a pyinstaller specific hook file which is mildly annoying as the whole point of using importlib is to have a standard pythonic way to import data without getting involved with a file system.
> 
> The problem is in the --onefile,
> The solution I could do was, use the pyinstaller github example in its normal version, create a Data Tree, and then copy the pygame_gui.data.default_theme.json file from pip with its derivatives that are the fonts.
> 
> but unfortunately I have not yet been able to create it in 1 single file
> 
> [![archivos-1](https://camo.githubusercontent.com/195e35bcfbc04ab49c2e71bc8903db6269c2793cfef1efd4c947e999e50369d1/68747470733a2f2f692e6962622e636f2f505950304b6a6d2f6172636869766f732d312e706e67)](https://ibb.co/PYP0Kjm) [![archivos-2](https://camo.githubusercontent.com/70847a99befc75c71961213ee19a0a2b8a095fa24cf4603b9e26c1e764fee218/68747470733a2f2f692e6962622e636f2f463652746370622f6172636869766f732d322e706e67)](https://ibb.co/F6Rtcpb)

Would you mind you writing down exactly how you got it to work? I've been trying to package a project of mine for a couple days and I'm ready to sacrifice putting it in a single file at this point. Thanks!

**Comment by t0a5ted** [comment]
> > Yeah, I had this reported somewhere, but I guess it wasn't on GitHub
> > I think PyInstaller is probably excluding non-py files when deciding what files to copy from a package - which is unfortunate for a data package. I'll probably have to create a pyinstaller specific hook file which is mildly annoying as the whole point of using importlib is to have a standard pythonic way to import data without getting involved with a file system.
> 
> The problem is in the --onefile,
> The solution I could do was, use the pyinstaller github example in its normal version, create a Data Tree, and then copy the pygame_gui.data.default_theme.json file from pip with its derivatives that are the fonts.
> 
> but unfortunately I have not yet been able to create it in 1 single file
> 
> [![archivos-1](https://camo.githubusercontent.com/195e35bcfbc04ab49c2e71bc8903db6269c2793cfef1efd4c947e999e50369d1/68747470733a2f2f692e6962622e636f2f505950304b6a6d2f6172636869766f732d312e706e67)](https://ibb.co/PYP0Kjm) [![archivos-2](https://camo.githubusercontent.com/70847a99befc75c71961213ee19a0a2b8a095fa24cf4603b9e26c1e764fee218/68747470733a2f2f692e6962622e636f2f463652746370622f6172636869766f732d322e706e67)](https://ibb.co/F6Rtcpb)

How did you do it? Could you list out all the steps?

**Comment by aefader00** [comment]
> 
> 
> > > Yeah, I had this reported somewhere, but I guess it wasn't on GitHub
> > > I think PyInstaller is probably excluding non-py files when deciding what files to copy from a package - which is unfortunate for a data package. I'll probably have to create a pyinstaller specific hook file which is mildly annoying as the whole point of using importlib is to have a standard pythonic way to import data without getting involved with a file system.
> > 
> > 
> > The problem is in the --onefile,
> > The solution I could do was, use the pyinstaller github example in its normal version, create a Data Tree, and then copy the pygame_gui.data.default_theme.json file from pip with its derivatives that are the fonts.
> > but unfortunately I have not yet been able to create it in 1 single file
> > [![archivos-1](https://camo.githubusercontent.com/195e35bcfbc04ab49c2e71bc8903db6269c2793cfef1efd4c947e999e50369d1/68747470733a2f2f692e6962622e636f2f505950304b6a6d2f6172636869766f732d312e706e67)](https://ibb.co/PYP0Kjm) [![archivos-2](https://camo.githubusercontent.com/70847a99befc75c71961213ee19a0a2b8a095fa24cf4603b9e26c1e764fee218/68747470733a2f2f692e6962622e636f2f463652746370622f6172636869766f732d322e706e67)](https://ibb.co/F6Rtcpb)
> 
> How did you do it? Could you list out all the steps?

I was actually able to come up with a solution and was able to get the main script into one file.

First, I copy and pasted the pygame_gui library folder found within AppData into my project's directory.

Then, I downloaded this [library](https://pypi.org/project/auto-py-to-exe/) and in the settings I selected "onefile", "windowed", and then under Additional Files I linked all of the folders/files in my project directory as well as the newly created local pygame_gui folder. Then, after it compiled, I moved the .exe back into the main project directory and it just worked! Let me know if this works for you.

**Comment by t0a5ted** [comment]
> > > > Yeah, I had this reported somewhere, but I guess it wasn't on GitHub
> > > > I think PyInstaller is probably excluding non-py files when deciding what files to copy from a package - which is unfortunate for a data package. I'll probably have to create a pyinstaller specific hook file which is mildly annoying as the whole point of using importlib is to have a standard pythonic way to import data without getting involved with a file system.
> > > 
> > > 
> > > The problem is in the --onefile,
> > > The solution I could do was, use the pyinstaller github example in its normal version, create a Data Tree, and then copy the pygame_gui.data.default_theme.json file from pip with its derivatives that are the fonts.
> > > but unfortunately I have not yet been able to create it in 1 single file
> > > [![archivos-1](https://camo.githubusercontent.com/195e35bcfbc04ab49c2e71bc8903db6269c2793cfef1efd4c947e999e50369d1/68747470733a2f2f692e6962622e636f2f505950304b6a6d2f6172636869766f732d312e706e67)](https://ibb.co/PYP0Kjm) [![archivos-2](https://camo.githubusercontent.com/70847a99befc75c71961213ee19a0a2b8a095fa24cf4603b9e26c1e764fee218/68747470733a2f2f692e6962622e636f2f463652746370622f6172636869766f732d322e706e67)](https://ibb.co/F6Rtcpb)
> > 
> > 
> > How did you do it? Could you list out all the steps?
> 
> I was actually able to come up with a solution and was able to get the main script into one file.
> 
> First, I copy and pasted the pygame_gui library folder found within AppData into my project's directory.
> 
> Then, I downloaded this [library](https://pypi.org/project/auto-py-to-exe/) and in the settings I selected "onefile", "windowed", and then under Additional Files I linked all of the folders/files in my project directory as well as the newly created local pygame_gui folder. Then, after it compiled, I moved the .exe back into the main project directory and it just worked! Let me know if this works for you.

It works! Thanks for the solution! Also would like to note that it is not neccessary to use auto-py-to-exe, you could just add the additional files with the parameter --add-data in pyinstaller  (this is because auto-py-to-exe is just generating a pyinstaller command).

Anyways, I managed to get my app working in --onefile -console and with an icon.

**Comment by glipR** [comment]
For anyone coming across this issue later on, you can fix this quite easily without needing to copy over site-packages or anything, just include the following in your `.spec` file for PyInstaller:
```
import pygame_gui
pygame_data_loc = os.path.join(os.path.dirname(pygame_gui.__file__), 'data')
a = Analysis(...
    datas=[...
        (pygame_data_loc, "pygame_gui/data")
    ...]
...)
```

**Comment by MyreMylar** [comment]
I have added a pyinstaller hook file in the next version of pygame_gui which should make this whole process a lot easier.
