### ISSUE TITLE
Trying to implement a toolbox into pygame_gui

### ISSUE THREAD

**Issue by Mohit9925** [MyreMylar/pygame_gui#167]
Hey I am Mohit, I am Trying to add a toolbar into the module but facing an error! can you explain why am i facing this usse
I am Trying to Create a class ToolBoxButton( by inheriting pygame_gui.elements.ui_button.UIButton class) but whenever I create Super().__init__ method to call the base constuctor it gives me an error

using the following code:
also the class toolbox contains data members link manger:UIManager   and tools: List of toolboxbutton objects
```
    class ToolboxButton(pygame_gui.elements.ui_button.UIButton):
        def __init__(self,pos,toolbox:Toolbox,text="None"):
            self.toolbox=toolbox
            self.toolbox.tools.append(self)
            self.relative_rect=pygame.Rect((pos[0], pos[1]), (50,50))
            print(self.toolbox.manager)
```
![error](https://user-images.githubusercontent.com/43760701/98913458-67aa5f80-24ed-11eb-8755-514b2671f46c.PNG)

        super().__init__(self,self.relative_rect.copy(),text,self.toolbox.manager)

**Comment by MyreMylar** [comment]
It looks like the parameters being passed into super().__init__() are wrong
to me. You don't pass in 'self' it is passed implicitly.
