### ISSUE TITLE
How can I stop the manager when I no long need it?

### ISSUE THREAD

**Issue by Yawn-git** [MyreMylar/pygame_gui#168]
I want to have the main menu to have pygame-gui but when I click a button to go the next part of my game, the pygame-gui stays on my screen.

I know that the solution to this is extremely easy and simple but I cant seem to find anything about stopping the manager when its no longer needed.

Anything would help, thanks.

**Comment by MyreMylar** [comment]
Set the variable you are using for the UI manager to None and stop calling
any of its methods. You could do an `if ui_manager is not None:` check
around the calls to update and draw_ui.

Alternatively, you can call .kill() on any UI elements like the buttons you
are using.

**Comment by Yawn-git** [comment]
Thank you @MyreMylar 

Respect for the amazing library!
