### ISSUE TITLE
Is there a way to detect when text effect is completed (e.g. if typing - detect if typing is finished).

### ISSUE THREAD

**Issue by kanekv** [MyreMylar/pygame_gui#169]

**Comment by MyreMylar** [comment]
I think you could probably calculate this yourself right now using the `text_progress` attribute of the typing effect class, but I expect I could make this a lot cleaner and likely consistent across all the effects so you can just call a simple function on any of them to see if they are done or not.

**Comment by kanekv** [comment]
@MyreMylar another feature would be useful: to have a callback when effect is done?

**Comment by MyreMylar** [comment]
This was added as a new UI event in 0.6.0:

https://pygame-gui.readthedocs.io/en/latest/events.html#uitextbox-ui-text-effect-finished
