### ISSUE TITLE
Is it possible to make a multi-line text entry box?

### ISSUE THREAD

**Issue by spfaul** [MyreMylar/pygame_gui#170]
Im trying to do this with the pygame_gui.elements.ui_text_entry_line module but i dont think its possible to do so yet. Does anyone know any workarounds?

**Comment by MyreMylar** [comment]
It's not going to be easy.

I'm refactoring the text submodule at the minute to try and make stuff exactly like this much easier to do but it likely won't be ready for a while as paying work is getting in the way.

You could maybe try just creating a new single text line element when the size of the text gets to be a certain width but I can forsee a host of difficulties with making that work already.

**Comment by MyreMylar** [comment]
This has gotten closer with the big text refactor. it's technically possible now to select across multiple lines, have an editing caret anywhere in a text layout and insert text arbitrarily.

I think a new UIElement called something like `UITextEntryMultiLine` is probably the next step. A multi-line text entry has elements in common with the Text entry line and a text box but will likely be different from both (limited rendering of a text line, shape more like a text box, interactions more like a line).
