### ISSUE TITLE
Self-updating components

### ISSUE THREAD

**Issue by yanickrochon** [MyreMylar/pygame_gui#171]
I have a self-updating component, an image updated from an external process, however the component is not refreshed, even when `element.dirty = 1` is set.

If this is already possible, I woulnd't know because the documentation does not give an exemple of it.

**Comment by MyreMylar** [comment]
You should be able to use `element.set_image(new_image_surf)` I believe.

**Comment by yanickrochon** [comment]
No, it does not work. :disappointed:
