### ISSUE TITLE
how to create or manage container/window 

### ISSUE THREAD

**Issue by Mohit9925** [MyreMylar/pygame_gui#172]
Hey ,
Mohit here. I have been using pygame_gui for a while now . I just created a button in pygame gui in Surface 2

there is one main root_display and 2 more surfaces.
root display is further divided into two parts surface 1 (70% of root display ) and surface 2 (rest 30% of root display) on top of root display . 
button needs to be placed in (0,0) in surface2 . but it is placing in root display (0,0) . 

I think i need to specify  container. but I don't kow how to  create one!! Please help

![issue1](https://user-images.githubusercontent.com/43760701/101239664-757b8b00-370f-11eb-9f08-2b6c0ff7b8c8.png)

**Comment by MyreMylar** [comment]
If you only want the GUI to draw on surface 2 (i.e. never on surface 1)
you'll have to make sure that the root container is in the same position
and of the same size as surface two.

So something like:

ui_manager = UIManager((surface_2_width, surface_2_height))
ui_manager.get_root_container().get_rect().top_left = (surface_2_x_pos,
surface_2_y_pos)

If you want to draw UI all over the screen then you are better off letting
the UI create the surfaces for you and just creating a UI manager the size
of the whole screen/window and then using a UIPanel to hold buttons which
will have its own surface.

Cheers,

Dan

**Comment by Mohit9925** [comment]
Thanks mate! :) I was  a  bit confused!.. pygame_gui is a amazing library. I am still exploring!
