### ISSUE TITLE
UILabel transparent background

### ISSUE THREAD

**Issue by JeremyRaven** [MyreMylar/pygame_gui#173]
Please can this feature be implemented across all elements. This means labels with text can be overlayed on images with partial or full transparent background alpha.

**Comment by MyreMylar** [comment]
This should work now, just set the background colour to have a 00 in the
4th spot (or 7th and 8th spots) of the hex colour value. E.g. #00000000

Cheers,

Dan

**Comment by JeremyRaven** [comment]
Thanks Dan,
I tried pip install pygame_gui -U but terminal reports requirement is already up to date and skips upgrade.
Adding this to my json file doesnt appear to do anything

`"label2style":
    {
        "colours":
        {
            "dark_bg": "00000000",
            "normal_text": "#c5cbd8",
            "text_shadow": "#505050"
        },
`

**Comment by MyreMylar** [comment]
Looks like you are missing the preceding #.
