### ISSUE TITLE
Theming section of the docs a little light on detail with regards to identifiers

### ISSUE THREAD

**Issue by adamc77** [MyreMylar/pygame_gui#174]
It could be that I just missed it, but a more in-depth description of how the identifiers work in the theme files would be very helpful I think, especially for beginners. I wasn't sure why my blocks weren't being applied via object_id reference, the issue turned out to be that I prefixed them with "#" in the json but not during assignment in python, because I assumed that the "#" had the functional purpose of directing pygame_gui to a list of object_ids, as opposed to being a completely arbitrary character (from what I can see).

**Comment by MyreMylar** [comment]
Yeah, I could probably add an example bit of python code to the main docs showing how to create a button with an `ObjectID` that matches a theme file that I also put in the example. 

The # for ObjectIDs and the @ for class IDs are just conventions I proposed to make it easy to remember what is a class or element ID in a theme file, but it didn't seem necessary to enforce them as people could come up with their own ID classification schemes. They are just identifier strings to the code in the end.

**Comment by adamc77** [comment]
Clarifying that it's just convention would be enough imo, other people with a web design background might get caught out like I did since in CSS you reference element ids with a mandatory "#" prefix that isn't a part of the actual id string when defined.
