### ISSUE TITLE
Confusing HTML text size definition (UITextBox)

### ISSUE THREAD

**Issue by adamc77** [MyreMylar/pygame_gui#176]
What's the reasoning behind the "font_size" dictionary restriction on HTML font sizes? Seems unnecessary, but either way it'd be helpful to be able to view the pre-defined font sizes and their point size equivalents in the docs, since the only way you can check it currently seems to be opening up the script, or triangulating via the debugger by seeing what point size font it's telling me I should pre-load.

**Comment by MyreMylar** [comment]
I think what you are asking about is already covered by the function documentation:

>To pre-load custom fonts, or to use custom fonts at all (i.e. ones that aren't the default
>'fira_code' font) you must first add the paths to the files for those fonts, then load the
>specific fonts with a list of font descriptions in a dictionary form like so:

>code:`{'name': 'fira_code', 'point_size': 12, 'style': 'bold_italic'}`

>You can specify size either in pygame.Font point sizes with `point_size`, or in HTML style
sizes with `html_size`.

So you can just preload directly with whatever html sizes you specify in the text box html.

E.g.

```
manager.preload_fonts([{'name': 'fira_code', 'html_size': 3.5, 'style': 'bold'},
                       {'name': 'fira_code', 'html_size': 3.5, 'style': 'italic'}])
``` 

the 'html sizes' relate to the html font tag used in browsers for many years (which is apparently now being dropped from html 5, but I'm an old person so it's what I know).

**Comment by zeroxer** [comment]
Add the html_size to point size map here. 

```python
class UIFontDictionary(IUIFontDictionaryInterface):
    """
    The font dictionary is used to store all the fonts that have been loaded into the UI system.
    """
    _html_font_sizes = {
        1: 8,
        1.5: 9,
        2: 10,
        2.5: 11,
        3: 12,
        3.5: 13,
        4: 14,
        4.5: 16,
        5: 18,
        5.5: 20,
        6: 24,
        6.5: 32,
        7: 48
    }
```
From source https://github.com/MyreMylar/pygame_gui/blob/aec6a544255fe35f5eb7eeafa39d30cb72d3c51b/pygame_gui/core/ui_font_dictionary.py#L51-L66
