### ISSUE TITLE
Update optionlist of UIDropDownMenu

### ISSUE THREAD

**Issue by RocketRider** [MyreMylar/pygame_gui#180]
Is there any possiblity to update the optionlist of UIDropDownMenu after creation?

I am currently doing it like this:
```
        dropdown.options_list = new_list
        dropdown.menu_states['expanded'].options_list = new_list
        dropdown.menu_states['expanded'].rebuild()
        dropdown.selected_option = new_list[0]
        dropdown.menu_states['closed'].selected_option = new_list[0]
        dropdown.menu_states['closed'].finish()
        dropdown.menu_states['closed'].start()
        dropdown.rebuild()
```

**Comment by MyreMylar** [comment]
Right now, I would likely just recreate the drop down with the new option list. 

I can probably investigate adding more post-creation adjustments to the drop down, but re-creating it seems fairly efficient as there isn't much data in a drop down apart from the options and whichever one is currently selected, both of which you can pass in at the start.
