### ISSUE TITLE
How to add element in UIWINDOW?

### ISSUE THREAD

**Issue by kuanshnlai** [MyreMylar/pygame_gui#183]
I tried to add some buttons in the new window but it did not appear.

I want add button like this
![圖片](https://user-images.githubusercontent.com/57993994/103021855-d2879580-4585-11eb-89b9-334f68d1b9dc.png)
I try use an new manager to manage the new window but if I do this, the new window will not appear, so I use old manager to manage the new window. Is this wrong?
Following is my code
```
def addNodeEvent(manager):
    windowWidth, windowHeight = 400, 400
    # manager = pygame_gui.UIManager((windowWidth, windowHeight))
    surface = pygame.Surface((windowWidth, windowHeight))
    checkWindow = pygame_gui.elements.ui_window.UIWindow(
        pygame.Rect((200, 200), (windowWidth, windowHeight)), manager=manager)

    confirmBtn = pygame_gui.elements.UIButton(relative_rect=pygame.Rect(
        (250, 500), (70, 50)), text="Confirm", manager=manager, container=checkWindow, parent_element=checkWindow)
    cancelBtn = pygame_gui.elements.UIButton(relative_rect=pygame.Rect(
        (450, 500), (70, 50)), text="Cancel", manager=manager, container=checkWindow, parent_element=checkWindow)
    manager.update(1)
    checkWindow.show()
    manager.draw_ui(surface)

```

**Comment by kuanshnlai** [comment]
Sorry the picture is this one
![圖片](https://user-images.githubusercontent.com/57993994/103022564-3199da00-4587-11eb-83a1-b9b1bd511241.png)

**Comment by kuanshnlai** [comment]
Oh I know why I was wrong. I set the button out of the window so that I can’t see them.
Sorry for asking a stupid question.

**Comment by MyreMylar** [comment]
No worries, I only just saw this anyway 👍
