### ISSUE TITLE
Hiding disabled items and then showing them will broke their look

### ISSUE THREAD

**Issue by t-cel** [MyreMylar/pygame_gui#185]
Just like in title, when you hide a disabled item like button, and then show it, it will look like enabled style but it will not react to interactions like hover etc just like disabled item.

**Comment by MyreMylar** [comment]
Thanks for reporting this.

**Comment by xirsoi** [comment]
I'd like to try fixing this, if you haven't already done so in the 0.6.0 branch that is.

**Comment by MyreMylar** [comment]
> I'd like to try fixing this, if you haven't already done so in the 0.6.0 branch that is.

Hi, feel free to give it a go. I just checked and I haven't gotten around to fixing it yet

**Comment by xirsoi** [comment]
Awesome. I spent some time (~30m) looking at the code in the 0.6.0 branch and it wasn't obvious what the problem was. I'll probably have to actually run the code to determine where the issue is. I suspect the active state is being messed with and not restored.

**Comment by xirsoi** [comment]
Actually, which branch should I work from? Would it be better to go from main or version_060 ?

**Comment by xirsoi** [comment]
Looks like we're always setting the active_state to 'normal' when we show, regardless of the state of is_enabled. Unfortunately it looks like each child of UIElement is handling it differently, so it's gonna be a bunch of small changes everywhere.
