### ISSUE TITLE
Multiline text entry

### ISSUE THREAD

**Issue by divitechstudios** [MyreMylar/pygame_gui#189]
There doesn't seem to be a multiline text entry widget which I think would be very useful if it did exist.

**Comment by void4** [comment]
I could use it right now :D

**Comment by MyreMylar** [comment]
Once the current text refactoring is done this should be a lot more possible as I am moving most of the text editing functions to be part of the shared text drawing and layout code that all elements are going to share.

Might be in 0.6.0, or more likely the update afterwards.

**Comment by arbarr3** [comment]
Is this implemented yet?  I've looked through the API documentation and I can't find anything, but I might be missing something.

**Comment by MyreMylar** [comment]
Nope it is not in yet. I started looking at it for 0.6.0 but was way too busy last year to give it a proper investment of time.

The back end text refactor is done (for now) so it's definitely more possible, just needs a lot of fiddling to make a useable UI element of out of it with a good user experience. This is on my task list to look at again for the summer.
