### ISSUE TITLE
Test Pygame GUI with PyInstaller.

### ISSUE THREAD

**Issue by MyreMylar** [MyreMylar/pygame_gui#19]
-test in -onefile mode to see if that works too.

**Comment by MyreMylar** [comment]
OK, I have a version of the library working in PyInstaller.

The main issue with making Pygame GUI into a Pyinstaller executable stem from it including data files. While there are plenty of well documented solutions for application developers to include data in their programs; for libraries the options are a little harder to puzzle out.

The solution I eventually hit on was to use the [Stringify](https://github.com/slightlynybbled/stringify) library to convert all my data files into 64 bit strings. These byte strings can then be turned back into file like objects in the code with something like:

`default_theme_file = io.BytesIO(base64.standard_b64decode(default_theme))`

The downsides are that these strings use about 1.5 times more space than the original files, but if you don't have too many data files in your library that seems to be an acceptable trade-off.

**Comment by MyreMylar** [comment]
**Remaining work**

 - Tidy up code to only include stringified data when we can't find the original data. 
 - Test out possibility of automating process/not double including data/not including license file.
 - If automating is too slow - document process for stringifiying.
 - Compile list of building, testing & documentation building dependencies for contributors.
 - Add tidy example program to build a PyInstaller application to pygame_gui_examples.

**Comment by MyreMylar** [comment]
Worth noting that you have to build the project with:

`python setup.py install`

To run  pre-setup scripts. This is actually what we want because end-users won't need stringify just to install the module. However I will have to re-learn the habit, and this should probably be noted in the contributor guide.

**Comment by WolsYang** [comment]
Hi is pygame-gui can use with pyinstaller now?

I got an error "pygame_gui/core/ui_font_dictionary.py:116: UserWarning: Unable to load resource with path: <pygame_gui.core.utility.PackageResource object at 0x7fd2d9f958b0>".

Do you have any idea?

Thank any way.

**Comment by MyreMylar** [comment]
The next version will work. Version 0.6.0. I'm still working on it right
now. Should be done by the end of the year. 🙂
