### ISSUE TITLE
Wrong Font Selected At Init

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#192]
**Describe the bug**
When starting the game, pygame gui defaulting to using some fonts contrary to specification in theme. Saving theme changes this, though only once. 

**To Reproduce**
```python
class TitleScreen(Panel):
    def __init__(self, rect: Rect, manager: UIManager):

        # complete base class init
        super().__init__(rect, RenderLayer.BOTTOM, manager, object_id=ObjectID("#title_screen", "@menu_screen"))
```
```python
    def _load_fonts(self):
        self._gui.add_font_paths("barlow", str(ASSET_PATH / "fonts/Barlow-Light.otf"))
        self._gui.add_font_paths("cozette", str(ASSET_PATH / "fonts/cozette_bitmap.ttf"))

        fonts = [
            {"name": "barlow", "point_size": 12, "style": "regular"},
            {"name": "cozette", "point_size": 12, "style": "regular"},
        ]

        self._gui.preload_fonts(fonts)
```
```json
    "@menu_screen": {
        "colours": {
            "dark_bg": "#0C0D0C"
        },
        "font": {
            "name": "barlow",
            "size": "16"
        }
    },
```

1. Set "cozette" in theme 
2. Start game -> see barlow font used. 
3. Set "barlow" in theme  and save json-> see cozette font used.
4. Set "cozette" in theme and save json -> see cozette font used. (no change) 

**Expected behaviour**
The specified font should be used.

**Screenshots**
Examples for 1 and 2 above, for 2 different "@menu_screen" gui elements. 
![image](https://user-images.githubusercontent.com/23128268/107122339-2082ff00-688f-11eb-9373-57fcb31f6072.png)
![image](https://user-images.githubusercontent.com/23128268/107122474-db130180-688f-11eb-8376-c74bcdf96016.png)

Examples for 3 above, for 2 different "@menu_screen" gui elements. 
![image](https://user-images.githubusercontent.com/23128268/107122319-fd584f80-688e-11eb-81d5-e87b6a147d23.png)
![image](https://user-images.githubusercontent.com/23128268/107122500-f67e0c80-688f-11eb-9867-2fa6ee2b23f7.png)

**Platform and software (please complete the following information):**
 - OS: Windows 10
 - Pygame GUI version: 0.5.7
 - Pygame version: 2.0.0.dev10

**Additional context**
Full theme:
```json
{
    "defaults": {
        "colours": {
            "normal_bg": "#372C47",
            "hovered_bg": "#372C47",
            "disabled_bg": "#c21515",
            "selected_bg": "#372C47",
            "active_bg": "#6B4A6B",
            "dark_bg": "#484A45",
            
            "normal_text": "#ffffff",
            "hovered_text": "#EBCA71",
            "selected_text": "#EBCA71",
            "disabled_text": "#c21515",
            "active_text": "#EBCA71",
            
            "link_text": "#7f11ad",
            "link_hover": "#2020FF",
            "link_selected": "#551A8B",
            
            "text_shadow": "#000000",
            
            "normal_border": "#372C47",
            "hovered_border": "#6B4A6B",
            "disabled_border": "#c21515",
            "selected_border": "#EBCA71",
            "active_border": "#6B4A6B"
        }
    },
    
    
    "@menu_screen": {
        "colours": {
            "dark_bg": "#0C0D0C"
        },
        "font": {
            "name": "barlow",
            "size": "16"
        }
    },
    "@gui": {
        "colours": {
            "dark_bg": "#000000"
        }
    },
    "@menu_window": {
    
    },
    
    
    "window": {
        "misc":{
            "title_bar_height": "12"
        }
    },
    
    
    "panel": {
        "misc": {
            "border_width": "0",
            "shadow_width": "0"
        }
    },
    
    
    "text_box": {
        "font": {
            "name": "cozette",
            "size": "12"
        },
        "misc": {
            "shape": "rectangle",
            "shape_corner_radius": "0",
            "border_width": "0",
            "shadow_width": "2",
            "padding": "10, 10"
        }
    },
    
    
    "drop_down_menu": {
        "misc": {
            "shape": "rectangle",
            "shape_corner_radius": "0",
            "shadow_width": "0",
            "border_width": "1"
        }
    },
    "drop_down_menu.button": {
        "prototype": "drop_down_menu",
        "font": {
            "name": "cozette",
            "size": "16"
        }
    },
    "drop_down_menu.#drop_down_options_list": {
        "prototype": "drop_down_menu"
    },
    "drop_down_menu.#drop_down_options_list.button": {
        "prototype": "drop_down_menu"
    },
    
    
    "button": {
        "font": {
            "name": "cozette",
            "size": "16"
        },
        "misc": {
            "tool_tip_delay": "1.5",
            "shadow_width": "0",
            "border_width": "2",
            "shape": "rounded_rectangle",
            "shape_corner_radius": "3"
        }
    },
    "#skill_bar.button": {
        "prototype": "button",
        "misc": {
            "text_horiz_alignment": "left",
            "text_vert_alignment": "bottom"
        }
    },
    
    
    "#screen_message": {
        "misc": {
            "padding": "1, 1"
        }
    },
    
    "vertical_scroll_bar": {
        "colours": {
            "dark_bg": "#0C0D0C"
        }
    }
}
```

**Comment by MyreMylar** [comment]
I believe this is at least partly due to ordering. The normal loading goes like this:

1. Load theme file when you create UIManager. This will load fonts whose paths you specify in the theme file.
2. Load any additional fonts you want to use dynamically (e.g. you have a text box that uses a bunch of fonts.
3. When theme file changed, reload it.

So on a first run through, if you set the font by name _without_ the file path, you will get a default font until the theme file is edited in any way, then it should pick up the preloaded fonts. Which sounds like some of the behaviour you are seeing here. I'd have thought after that it should catch up and match your edits though. 

I'll look into it a bit - but I would advise that you specify the paths for the fonts once in the theme file (you could create a dummy block just to load the two fonts, if you want to keep switching round dynamically while testing) rather than using preload fonts in this case.

**Comment by Snayff** [comment]
Spot on, as ever, mate. Adding a block to load each font worked straight away. Thank you!

To confirm, do I still need to load the fonts separately if I want to use them in e.g. a textbox?

Example block:
```json
    "dummy_load_barlow": {
        "font": {
            "name": "barlow",
            "size": "16",
            "regular_path": "assets/fonts/Barlow-Light.otf"
        }
    },
    "dummy_load_cozette": {
        "font": {
            "name": "cozette",
            "size": "16",
            "regular_path": "assets/fonts/cozette_bitmap.ttf"
        }
    },
```

**Comment by MyreMylar** [comment]
> To confirm, do I still need to load the fonts separately if I want to use them in e.g. a textbox?

It's been a while since I messed with this but I'm fairly certain that once you've loaded a font (which means a 'face' + size + style combo) it remains loaded and useable everywhere in the UI without anymore preloading required.

**Comment by steelx** [comment]
> Spot on, as ever, mate. Adding a block to load each font worked straight away. Thank you!
> 
> To confirm, do I still need to load the fonts separately if I want to use them in e.g. a textbox?
> 
> Example block:
> 
> ```json
>     "dummy_load_barlow": {
>         "font": {
>             "name": "barlow",
>             "size": "16",
>             "regular_path": "assets/fonts/Barlow-Light.otf"
>         }
>     },
>     "dummy_load_cozette": {
>         "font": {
>             "name": "cozette",
>             "size": "16",
>             "regular_path": "assets/fonts/cozette_bitmap.ttf"
>         }
>     },
> ```

thanks helped me too
