### ISSUE TITLE
Can't import pygame_gui

### ISSUE THREAD

**Issue by Taffer** [MyreMylar/pygame_gui#199]
**Describe the bug**

I'm following the "Getting Started" code in the docs, and it's failing with `AttributeError: partially initialized module 'pygame_gui' has no attribute 'UIManager' (most likely due to a circular import)` after I attempt to import `pygame_gui`.

**To Reproduce**

Steps to reproduce the behaviour:

1. `import pygame`
2. `import pygame_gui`
3. exception below happens

**Expected behaviour**

Expecting the import to work.

**Screenshots**

The traceback:

```py
$ python3 pygame_gui.py
pygame 2.0.1 (SDL 2.0.14, Python 3.9.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/chris.herborth/Downloads/pygame_gui.py", line 12, in <module>
    import pygame_gui
  File "/Users/chris.herborth/Downloads/pygame_gui.py", line 15, in <module>
    manager = pygame_gui.UIManager((800, 600))
AttributeError: partially initialized module 'pygame_gui' has no attribute 'UIManager' (most likely due to a circular import)
```

**Platform and software (please complete the following information):**

 - OS: macOS
 - Pygame GUI version: 0.5.7 I think
 - Pygame version: 2.0.1

**Comment by hicach0** [comment]
try:
$ pip install pygame
and
$ pip install pygame_gui

**Comment by MyreMylar** [comment]
You can't name a python file with the same name as a module you import.

So basically rename your file from pygame_gui.py to something else (not
pygame.py).

**Comment by Taffer** [comment]
Oh wow, do I feel dumb. Thanks!
