### ISSUE TITLE
Migrate away from using __file__ to load default font.

### ISSUE THREAD

**Issue by MyreMylar** [MyreMylar/pygame_gui#2]
As discussed here indygreg/PyOxidizer#69 __file__ is apparently being sort of deprecated for use in python modules for loading resources. Right now, support for alternatives also seems a bit patchy so there is no great rush.

I'm not certain that pygame is supported by PyOxidizer either yet.

**Comment by MyreMylar** [comment]
Look into resolving this when https://github.com/indygreg/PyOxidizer/issues/145 is resolved.

It looks like:`importlib.resource` is the current favourite to replace __File__.

**Comment by halfninja** [comment]
Looks like `importlib.resource` has been backported to a library `importlib_resources`, in case you weren't keen on requiring Python 3.7+ (though you could always have a fallback so that 3.7+ is only required if you want to use PyOxidiser).
