### ISSUE TITLE
Mouse misaligned with interaction

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#210]
**Describe the bug**
Clicking on the dropdown gets no response. Mousing over the dropdown doesnt highlight, but mousing nearby does. 

**To Reproduce**
https://gist.github.com/Snayff/4b17d63b8e72149a33d5a1ba6094533c

**Expected behaviour**
Mousing over the dropdown should interact with it. 

**Screenshots**
![3OSQlyzlSx](https://user-images.githubusercontent.com/23128268/123556036-06d04e80-d781-11eb-9c23-5098d893a156.gif)

**Platform and software (please complete the following information):**
 - OS: Windows 10
 - Pygame GUI version: 0.5.7
 - Pygame version: 2.0.0

**Additional context**
Tried changing resolution to base and scaled. Tried using different UIElements.

I am sure I am missing something obvious, but I have reread the start guide and followed along and I _think_ I am doing what is needed. I've also referred to my old project, as this happened a couple of times in that project, but I have followed that, too. Any advice would be appreciated!

Edit:
Setting the base and scaling resolutions to the same aligns the mouse, but the mouse click still fails to register with the drop down. 
The events are coming through, though...
```
<Event(1024-MouseMotion {'pos': (498, 20), 'rel': (0, 1), 'buttons': (0, 0, 0), 'window': None})>
<Event(1025-MouseButtonDown {'pos': (498, 20), 'button': 1, 'window': None})>
<Event(1026-MouseButtonUp {'pos': (498, 20), 'button': 1, 'window': None})>
<Event(32847-UserEvent {'user_type': 3, 'ui_element': <UIButton GUISprite(in 1 groups)>, 'ui_object_id': 'drop_down_menu.#expand_button'})>
```

Edit2:
Clicking in a text line seems to work just fine. I can type and make changes. Its only the drop down that wont seem to change. 
![tnkbyBYuhB](https://user-images.githubusercontent.com/23128268/123556029-01730400-d781-11eb-919b-8fcb173417d9.gif)

**Comment by MyreMylar** [comment]
**Copying comment from the gist:**

I'm guessing this is related to the scaling you are doing to the surface the UI is rendered to without also scaling the mouse events. You can handle scaling the mouse events yourself or you can have a go at using the semi-hidden/undocumented .mouse_pos_scale_factor attribute of the ui_manager. Bearing in mind that I didn't document it IIRC because this 'feature' has not really been tested or used by me for more than five minutes. No idea if it works!

The other option is to draw the UI directly onto the window surface (rather than the scaled surface) after line 36. Not sure what you are going for with the scaling, but a common technique is to scale up low resolution artwork for a 'pixel art' effect but draw the UI at the 'native' resolution. Minecraft does something similar in 3D.

**Comment by MyreMylar** [comment]
Had a test of this right now in 0.6.0 and I guess one of the changes I made to the drop down has fixed it accidentally. Hooray!

![image](https://user-images.githubusercontent.com/13382426/143495404-b9ffb1c6-ec1f-428f-9f0f-303078b0496c.png)


**Test code used (adapted from earlier gist):**

```
import pygame
import time

from pygame import Rect
from pygame_gui import UIManager
from pygame_gui.elements import UIDropDownMenu


class Game:
    def __init__(self):
        pygame.init()

        self.window: Window = Window(self)
        self._data_editor: DataEditorScene = DataEditorScene(self)

        # point this to whatever scene is active
        self.active_scene = self._data_editor

        self.clock = pygame.time.Clock()

    def update(self):
        self.active_scene.update()

    def render(self):
        self.window.render_frame()
        self.active_scene.render()

    def run(self):
        self.update()
        self.render()


class Window:
    def __init__(self, game: Game):
        self.game: Game = game

        self.base_resolution = [640, 360]
        self.scaled_resolution = [1280, 720]

        self.window = pygame.display.set_mode(self.scaled_resolution, 0, 32)
        self.display = pygame.Surface(self.base_resolution)
        self.dt = 0.1
        self.frame_start = time.time()

    def render_frame(self):
        self.window.blit(pygame.transform.scale(self.display, self.window.get_size()), (0, 0))
        pygame.display.update()
        self.display.fill((0, 0, 0))

        self.dt = time.time() - self.frame_start
        self.frame_start = time.time()


class DataEditorScene:
    """
    Handles EventScene interactions and consolidates the rendering. EventScene is used to give players a text choice.
    """

    def __init__(self, game: Game):
        self.game = game
        self.ui: DataEditorUI = DataEditorUI(game)

    def update(self):
        self.ui.update()

    def render(self):
        self.ui.render(self.game.window.display)


class DataEditorUI:
    def __init__(self, game: Game):
        self.game = game
        # init pygame gui
        resolution = self.game.window.scaled_resolution
        self._gui_manager = UIManager((resolution[0], resolution[1]))
        self._gui_manager.mouse_pos_scale_factor = (0.5, 0.5)

        self.refresh_ui()

    def update(self):
        dt = self.game.clock.tick() / 1000.0
        self._gui_manager.update(dt)

        # pass events to pygame gui
        for event in pygame.event.get():
            self._gui_manager.process_events(event)

    def render(self, surface: pygame.surface):
        self._gui_manager.draw_ui(surface)

    def refresh_ui(self):
        # positions
        start_x = 10
        start_y = 10
        option_width = 500
        option_height = 20

        # update pos
        current_x = start_x
        current_y = start_y

        # select unit
        unit_types = ["test1", "test2"]
        UIDropDownMenu(
            options_list=unit_types,
            starting_option=unit_types[0],
            relative_rect=Rect((current_x, current_y), (option_width, option_height)),
            manager=self._gui_manager,
        )


# run game
game = Game()
while True:
    game.run()

```

**Comment by jlaumonier** [comment]
I had the same problem here when i tried to downscaling 4K images ressources to render them into a more classical resolution (1080p for example) with `pygame.transform.smoothscale()`. It works fine but i have to scale the mouse position to interact with ui element. Anyway, I have tested with UITextEntryLine and i had a problem with focus with mouse. After some search, i found that the line `mouse_x, mouse_y = event.pos ` in `UIManager.process_events()` should be replaced by `                            mouse_x, mouse_y = self.calculate_scaled_mouse_position(event.pos)`. And it worked !

I am not sure this will correct every scaling problems but as I will use many widget of pygame_gui in a scaled GUI, I will test more this "functionnality" which i think would be very useful even if I think it should be handled directly by pygame with an option in `pygame.display.set_mode()`. I will make a pull request shortly (I hope) but I need to make more tests with probably a patch to general_ui_test_app.py with scaling options.

**Comment by MyreMylar** [comment]
Thanks for catching that in the manager's process events!

As I've not had any interaction with 4k hardware myself yet scaling hasn't been a personal focus, but I'll certainly correct things when they are pointed out.
