### ISSUE TITLE
How to modify theme properties directly via code? (color, font, border, etc)

### ISSUE THREAD

**Issue by haggletonpie** [MyreMylar/pygame_gui#212]
I've spent 2-3 hours reading the code, and, like most pygame coders I suspect, I'm not an expert, and I can't find where/how to simply set theme properties for UIElements directly.

In other words, how can I dynamically alter the colors, fonts, backgrounds, etc of the various elements?

Related...
https://github.com/MyreMylar/pygame_gui/issues/186

**Comment by MyreMylar** [comment]
Moved this talk to a discussion. Possibly there is some future work to do to make altering themes via code less cumbersome with helper functions - not certain as it breaks the 'live loading' from files concept if the themes in memory can differ from the data on the disc. 

Likely needs a bunch more thought put into it - is it better if you can switch button themes dynamically instead? I.e. button colours/effects defined in theme files but which them is used by a button is dynamically switch able easily?
