### ISSUE TITLE
Out of sync window_resolution in UIManager

### ISSUE THREAD

**Issue by lonelycorn** [MyreMylar/pygame_gui#215]
**Describe the bug**
in `UIManager.set_window_resolution()` ([source](https://github.com/MyreMylar/pygame_gui/blob/main/pygame_gui/ui_manager.py#L151)), only `self.window_resolution` is updated; `self.ui_window_stack` and `self.root_container` still use the window resolution passed in the `UIManager.__init__()`

**To Reproduce**
Steps to reproduce the behaviour:
1. instantiate a `UIManager` with window resolution of 1200x600, then create 2 equally-sized `UIPanel` (600x600)
2. handle events `pygame.locals.VIDEORESIZE`, where the two panels' dimensions and positions are updated to remain 50:50 split
2. resize the window, and observe that the panels were clipped by the old 1200x600 rect

**Expected behaviour**
resize the window and the two panels should split the window 50:50

**Screenshots**
the two panels clipped by the old 1200x600 rect
![Untitled](https://user-images.githubusercontent.com/4413190/140022932-f237c1e3-7421-4d01-b3ca-313333c2ab19.png)

**Platform and software (please complete the following information):**
 - OS: Ubuntu 20.04.2
 - Pygame GUI version: 0.5.7
 - Pygame version: 2.0.2

**Additional context**
should be fixed by
```
    def set_window_resolution(self, window_resolution: Tuple[int, int]):
        """
        Sets the window resolution.
        :param window_resolution: the resolution to set.
        """
        self.window_resolution = window_resolution
        self.ui_window_stack.window_resolution = window_resolution
        self.root_container.set_dimensions(window_resolution)
```

**Comment by MyreMylar** [comment]
Thanks for the report! I will look at fixing this in the next version, which should be 0.6.0.

**Comment by MyreMylar** [comment]
Made a simple test program for this showing the issue, and the fix posted by @lonelycorn above works perfectly:

**Test case:**
```
import pygame
import pygame_gui


pygame.init()


window_surf = pygame.display.set_mode((1200, 600), pygame.RESIZABLE)
window_surf.fill((0, 0, 0))

manager = pygame_gui.ui_manager.UIManager((1200, 600))

panel_1 = pygame_gui.elements.UIPanel(pygame.Rect((0, 0), (600, 600)),
                                      0,
                                      manager=manager)
panel_2 = pygame_gui.elements.UIPanel(pygame.Rect((600, 0), (600, 600)),
                                      0,
                                      manager=manager)

clock = pygame.time.Clock()
running = True

while running:
    time_delta = clock.tick(60)
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.VIDEORESIZE:
            panel_width = event.w//2
            panel_height = event.h
            panel_1.set_dimensions((panel_width, panel_height))
            panel_2.set_dimensions((panel_width, panel_height))
            panel_2.set_position((panel_width, 0))
            manager.set_window_resolution((event.w, event.h))

    manager.update(time_delta)
    window_surf.fill((0, 0, 0))
    manager.draw_ui(window_surface=window_surf)

    pygame.display.update()

```

it will now definitely be in 0.6.0. Thanks @lonelycorn !
