### ISSUE TITLE
New line in UITextButton doesn't work correctly

### ISSUE THREAD

**Issue by Grimmys** [MyreMylar/pygame_gui#217]
**Describe the bug**

On the last version (0.5.7), new lines (using br tag) in UITextButton element are only "line return" and can't produce blank lines.
It works fine on previous version.

**To Reproduce**
Simply run the text test from the examples repository (https://github.com/MyreMylar/pygame_gui_examples/blob/master/text_test.py). 

**Expected behavior**
Multiple br tags should generate blank lines. 

**Screenshots**
![no blank lines](https://user-images.githubusercontent.com/25286578/141513625-d662124f-3c0f-416b-b7ef-3176f5818f01.png)

**Platform and software (please complete the following information):**
 - OS: Windows 10
 - Pygame GUI version: 0.5.7
 - Pygame version: 2.1.0

**Comment by MyreMylar** [comment]
This should be fixed in 0.6.0 - the underlying html parsing, text rendering and layout code has changed completely anyway so there will likely be new exciting bugs.

I'll double check it though.

**Comment by MyreMylar** [comment]
Checked it out in 0.6.0 and this definitely works again now.
