### ISSUE TITLE
UIScrollingContainer scrolling with the mousewheel events

### ISSUE THREAD

**Issue by lionel42** [MyreMylar/pygame_gui#220]
It would be nice if the Scrolling container can move with the mousewheel. This would make it similar to Scrolling containers commonly used.

Basically when the mouse is in the container and the user uses the mousewheel, the container should move accordingly.

At the moment, only the selection of the scrolling bars makes the container move.

**Comment by MyreMylar** [comment]
I'll try to look into this for 0.6.1.

Thanks for the report!
