### ISSUE TITLE
Text entry background is transparent

### ISSUE THREAD

**Issue by rsa16** [MyreMylar/pygame_gui#228]
**Describe the bug**
When I click on a text entry the height occupied by the cursor becomes transparent.

**To Reproduce**
I'm not sure how to reproduce the bug, it only happens in my own script.

**Expected behaviour**
I expected that the cursor would appear and the background will remain as the themed dark_bg.

**Screenshots**
![image](https://user-images.githubusercontent.com/47797856/147856391-b372569c-1818-4545-8d73-b70def07e625.png)

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version: 0.6.0
 - Pygame version 2.1.2

**Additional context**
If it helps, I will send my menu code as well, however it's a bit long, really sorry about that.
[code](https://pastebin.com/LGLA6FAN)

**Comment by MyreMylar** [comment]
Thanks for the report! I shall look into it.

**Comment by MyreMylar** [comment]
This should now be fixed in 0.6.2. Let me know if you have any further problems.
