### ISSUE TITLE
Problem building API on readthedocs with version 0.6

### ISSUE THREAD

**Issue by lionel42** [MyreMylar/pygame_gui#229]
I noticed that the api does not show properly on readthedocs with the new version

[see example](https://pygame-gui.readthedocs.io/en/latest/pygame_gui.elements.html#pygame-gui-elements-ui-button-module )

It is probably a problem that the autodoc extension cannot import pygame_gui because of the missing 
requirements of the new library python-i18n in the  [sphinx requirements file](https://github.com/MyreMylar/pygame_gui/blob/main/docs/requirements.txt)

(happened to me once as well for another project)

**Comment by MyreMylar** [comment]
Thanks for the report, and the ideas on how to fix it. I made a few tweaks and it now seems to work OK again. You may need to CTRL+F5 in your web browser of choice to refresh the cache.
