### ISSUE TITLE
Add a 'center' point anchor

### ISSUE THREAD

**Issue by KansaiGaijin** [MyreMylar/pygame_gui#233]
**Is your feature request related to a problem? Please describe.**
Want to easily align elements to the center of another specifically for keeping things centered when changing window size.

**Describe the solution you'd like**
Having anchor: 'center' be a possibility.

**Describe alternatives you've considered**
Aligning to the center via of a rectangle using base PyGame features

**Additional context**
Discussed with you on the PyGame discord.

**Comment by MyreMylar** [comment]
Thanks for creating the issue.
