### ISSUE TITLE
Add placeholder text in user entry fields

### ISSUE THREAD

**Issue by KansaiGaijin** [MyreMylar/pygame_gui#234]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
To be able to add placeholder text such as "Enter your text here..." that disappears when a user clicks into the field.

**Describe alternatives you've considered**
Having normal text in the field that needs to be deleted (requires users to delete it and breaks immersion)
Having text that can remain and be ignored via code (such as: ">> ")

**Additional context**
PyQT5 has this functionality

**Comment by MyreMylar** [comment]
Thanks for the suggestion. I think this was also asked for in another 'combo wishlist' earlier on so it's been on my mind.
