### ISSUE TITLE
UITextBox element text input bug

### ISSUE THREAD

**Issue by KansaiGaijin** [MyreMylar/pygame_gui#235]
**Describe the bug**
Using the UITextEntryLine element, the text input shows up like the attached image. Clicking outside of the text input field updates the element and shows it correctly. It also 'updates' when adding new text but doesn't when deleting.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create the pygame_gui.elements.UITextBox in your window.
2. Run your script.
3. Click into the input field and see the | bar, static.
4. Begin typing and watch as the text is added with odd artifacts.
5. Attempt to delete (backspace) but view no change.
6. Click elsewhere in the window and see the input field update removing all issues.

**Expected behaviour**
Text will update without weird artifacting and also have the ability to backspace, all without the need for clicking out of the box.

**Screenshots**
![image](https://user-images.githubusercontent.com/83641841/148642345-36e0bb76-ef75-4c18-9966-530dcbcf8c1a.png)

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.0
 - Pygame version 2.1.2

**Additional context**
You'll need a coloured background to view the artifacting as it is white.

**Comment by KansaiGaijin** [comment]
Possibly fixed by adding a surface to the same area.

**Comment by MyreMylar** [comment]
Hey, do you have a quick script that reproduces this issue?

**Comment by KansaiGaijin** [comment]
https://pastebin.com/w2pk2qub

It includes the fix in commented out lines of code so it's likely that I had just done it wrong in the first place.

**Comment by Calert123** [comment]
Same here after an update from 5.7.0 to 6.1.0.

**Comment by MyreMylar** [comment]
This should now be fixed in 0.6.2. Let me know if you have any further problems.
