### ISSUE TITLE
Mouse down events on drop down menu result in click being re-processed by game

### ISSUE THREAD

**Issue by ConquerProgramming1** [MyreMylar/pygame_gui#238]
I have a dropdown menu above the gameplay area, and when opened the dropdown covers a portion of the gameplay area. When I select a menu item in the dropdown, ui_manager processes the mouse event, but I have no way to know that the mouse down was used by the dropdown menu, so I end up also processing the click as part of gameplay, with undesired results.

See screenshot.

I was able to solve this by changing ui_manager.process_events() to simply return the consumed_event variable, so I could skip processing the mouse event if already consumed.

I'm happy to do a pull request for this, but first wanted to make sure I'm not missing an already-supported way to avoid this problem.

<img width="1075" alt="Screen Shot 2022-01-19 at 6 56 34 AM" src="https://user-images.githubusercontent.com/44384395/150157093-8701852f-907d-4715-9e18-724dc05d53d5.png">

**Comment by MyreMylar** [comment]
I think in most my use cases so far the UI areas have just generally not overlapped the game space so this hasn't really come up, but I think it is a good idea for the UIManager's `process_events()` to return the `consumed_event` variable. I think someone even suggested it to me before somewhere but it has got lost in the shuffle.

Feel free to submit a PR and it'll probably make it into 0.6.2!
