### ISSUE TITLE
Improve text effect options

### ISSUE THREAD

**Issue by MyreMylar** [MyreMylar/pygame_gui#24]
**To Do List:**

- [x] Effect parameters to control variables.
- [x] Add a UI event generated when an effect is finished.
- [x] Add HTML tag and set_effect parameter to limit applied effects to tagged areas only.
- [x] Add ability to apply text effects to labels.
- [x] Add optional 'post-finalise' transform matrix (translate, rotate, scale) for effects usage.
- [x] create more elaborate/interactive text effect example file in examples project
- [x] Add two new effects for whole chunk transform.

**Comment by Snayff** [comment]
Some ideas for effects: https://imgur.com/f6SbSfC

**Comment by MyreMylar** [comment]
Nice ideas 👍

**Comment by Snayff** [comment]
Being able to control the speed/duration of the effect and identifying when an effect is finished would both be extremely useful.

**Comment by MyreMylar** [comment]
This is text related so I'm setting it to 0.6.0 - which is apparently going to be the text update.

**Comment by Snayff** [comment]
Another effect. "drop in" text. https://i.imgur.com/pszY7nP.gifv

**Comment by MyreMylar** [comment]
Not going to get all of this done by the end of the year, so I'll split off whatever is left into new smaller issues.

The 'drop in' effect for sure is not going to make it and I'm not sure yet if I want text effects on buttons so might leave that without an issue until I make up my mind if it is making buttons visually overly complicated with their existing effects and states.

**Comment by MyreMylar** [comment]
OK, the effects still need work. I think the underlying system is mostly there for text chunk effects but I have not had much time to work on the actual effects themselves, right now I have a basic bounce, a tilt-y thing and an expand/contract thing.

Should be possible to do a chunk shake effect as in one of the above gifs once I've had some time to do the maths and make it look OK. The bounce effect is basically the 'wave' effect above (text moves up and down). 

The drop in effect is still fairly hard with the current system as it is a letter-by-letter thing + movement, I think what I'd want to do is have 'dropping letters' as their own single letter chunks and then once they reach the correct height they merge with their normal chunk. It doesn't map well with the system I just designed which applies effects to existing chunks created in a roughly normal way via the parse markup system.

I'll probably revisit letter-by-letter effects at some later point, or somebody else is free to tackle them if they like.
