### ISSUE TITLE
Background colour issue with UITextEntryLine

### ISSUE THREAD

**Issue by MotoMoto418** [MyreMylar/pygame_gui#242]
I'm not sure if it's intended or a bug, hence the clean slate. The text box when clicked after creating it, loses it's defined dark_bg and takes up the colour of the pygame surface it's drawn on, basically making it seem as if the text box becomes transparent upon clicking on it. On a side note, can we change the text cursor colour using a theme,json file?

The text input box when not selected -
![bug-1](https://user-images.githubusercontent.com/66240313/150642920-7a4f5ebe-0c89-4da3-af53-1cb56ab3b96c.jpg)

The text box after being selected - 
![image](https://user-images.githubusercontent.com/66240313/150642958-5099d5a7-863f-43dd-b158-0cb34eb108f0.png)

The issue can be reproduced upon creating a text input box with customization (with a dark_bg key) from a theme file.

**Comment by MyreMylar** [comment]
Looks like the same issue as #228

**Comment by MyreMylar** [comment]
This should now be fixed in 0.6.2. Let me know if you have any further problems.

**Comment by MotoMoto418** [comment]
Gotcha. Thanks!
