### ISSUE TITLE
Cursor colour modification for UITextEntryLine

### ISSUE THREAD

**Issue by MotoMoto418** [MyreMylar/pygame_gui#245]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, but could cause problems in the app. As far as I'm aware (which is not a lot), the cursor colour cannot be changed upon creation of a UITextEntryLine object, and it defaults to white, which paired with a white background is not efficient at all.

**Describe the solution you'd like**
Add "dark_cursor", "selected_cursor" attributes to the text input box under the theme.json file.

**Describe alternatives you've considered**
Nothing yet, not sure how to fix it, and if I can fix it.

**Comment by MyreMylar** [comment]
I've added a commit to fix this for the next release 0.6.2.

You will be able to set the colour of the text cursor by adding a 'text_cursor' entry to the colours block of the text line theming. 

```
"text_entry_line":
    {
        "colours":
        {
            "text_cursor": "#FF0000FF"
        },
    }
```

**Comment by MyreMylar** [comment]
0.6.2 is now released so this should be available for all.

**Comment by MotoMoto418** [comment]
Works like a charm. Thank you!
