### ISSUE TITLE
Missing py.typed marker for mypy typechecks

### ISSUE THREAD

**Issue by ChrisChou-freeman** [MyreMylar/pygame_gui#247]
when trying to use a static type checker (in this case mypy)  get error

`[mypy error] [E] Skipping analyzing "pygame_gui": module is installed, but missing library stubs or py.typed marker`

if wan't enable type checker(such as mypy) need add a marker file named py.typed to package supporting typing

see this [PEP561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)

**Comment by MyreMylar** [comment]
I've added an empty `py.typed` file to the root of the repo and added it to the `MANIFEST.in` so hopefully this will enable what you were trying to do when I release the next version - 0.6.2

This also prompted me to try using mypy on the library and wheee there are lots of errors reported so another pile of work to sort out there at some point.
