### ISSUE TITLE
MessageWindow - variables in translated strings

### ISSUE THREAD

**Issue by Timo654** [MyreMylar/pygame_gui#270]
**Is your feature request related to a problem? Please describe.**
I want to be able to use variables in translated strings, so I could let the user know about things like which file they're about to overwrite.

**Describe the solution you'd like**
The solution described in this discussion would be fine: https://github.com/MyreMylar/pygame_gui/discussions/261

**Additional context**
Labels already support variables, but MessageWindows and other elements don't.

**Comment by MyreMylar** [comment]
Thanks for opening this issue.

**Comment by MyreMylar** [comment]
Hello, I ended up using a dictionary of strings to strings to implement this across the library. 

This is so I could potentially easily add new arguments to the text accepting functions in the future without worrying about a bunch of passed by value arguments on the end of each function call. 

See the connected PR for a usage example.

This should be released in the next version 0.6.5 (when I finish it).
