### ISSUE TITLE
using set_text on UITextBox does not clear appended_text 

### ISSUE THREAD

**Issue by HLT-FL** [MyreMylar/pygame_gui#272]
When using set_text method on a UITextBox, appeneded_text doesn't clear and the existing text is added back to the html_text.

Steps to reproduce the behaviour:
1.  create a UITextBox with html_text='""
2. use `UITextBox.append_html_text('<p>something here<p>')`
3. try to change text using `UITextBox.set_text('<p>something new</p>')`
4. appended text stays

**Expected behaviour**
`UITextBox.appended_text` should be cleared when using `UITextBox.set_text` method
OR
there should be a ".clear" method if appended_text usually needs to remain after .set_text is used

**Comment by MyreMylar** [comment]
I think clearing the `.appended_text` attribute when calling `set_text()` makes sense.

Probably a `clear()` method makes more sense on the console window itself which is a thing people are likely to want to clear. A text box seems less commonly clear worthy (and, as you've clearly tried, `.set_text("")` makes sense if you do need to clear one for a more unusual use case).

**Comment by MyreMylar** [comment]
This improvement will be in the 0.6.5 release on PyPI when I get some time to release it (probably in 6-8 weeks).

Or you can just grab the code from Github and build it yourself :)
