### ISSUE TITLE
Allow `UIWindow` to be resizable from code

### ISSUE THREAD

**Issue by TechStudent10** [MyreMylar/pygame_gui#295]
**Is your feature request related to a problem? Please describe.**
If you want to dynamically change the size of a `UIWindow` from the source code, it isn't possible. Even if you recreate it (not recommended), or change it using the built-in `set_dimensions()`, it won't work.

**Describe the solution you'd like**
Allow `set_dimensions()` or some other function to change the width and height of the window.

**Describe alternatives you've considered**
As said above, I've tried recreating the window, however I don't know how to destroy the previous one, plus the size doesn't even change.

**Additional context**
I am using my fork so that I cannot drag the windows (#294), so that might've broken functionality.

**Comment by MyreMylar** [comment]
Hello, `set_dimensions()` appears to be working for me locally.

What functionality of the windows are you using, by the way - if you don't want them user resizable or draggable. Is it just the facility to have a name for a panel in the title bar? Perhaps a UIPanel with a Label would work better.

**Comment by TechStudent10** [comment]
> What functionality of the windows are you using, by the way

I'm trying to add some UI to a game engine that I am working on. I want to use the windows to have them docked, but also have them drag out if the user chooses.

> Perhaps a UIPanel with a UILabel would work better.

Maybe I'll try it out later.

> Hello, `set_dimensions()` appears to be working for me locally.

Huh. Guess my fork did break something :/

**Comment by MyreMylar** [comment]
You can get rid of any UIElement (including UIWindows) from the GUI with `element.kill()` btw.

**Comment by TechStudent10** [comment]
> You can get rid of any UIElement (including UIWindows) from the GUI with `element.kill()` btw.

I wonder why that, or even `set_dimensions()` aren't in the docs?

**Comment by TechStudent10** [comment]
Oh, and thanks!

**Comment by MyreMylar** [comment]
> > You can get rid of any UIElement (including UIWindows) from the GUI with `element.kill()` btw.
> 
> I wonder why that, or even `set_dimensions()` aren't in the docs?

It is:

- [set_dimensions()](https://pygame-gui.readthedocs.io/en/latest/pygame_gui.elements.html#pygame_gui.elements.ui_window.UIWindow.set_dimensions)
- [kill()](https://pygame-gui.readthedocs.io/en/latest/pygame_gui.elements.html#pygame_gui.elements.ui_window.UIWindow.kill)

Always open to new documentation ideas though.

**Comment by TechStudent10** [comment]
> > > You can get rid of any UIElement (including UIWindows) from the GUI with `element.kill()` btw.
> > 
> > 
> > I wonder why that, or even `set_dimensions()` aren't in the docs?
> 
> It is:
> 
> * [set_dimensions()](https://pygame-gui.readthedocs.io/en/latest/pygame_gui.elements.html#pygame_gui.elements.ui_window.UIWindow.set_dimensions)
> * [kill()](https://pygame-gui.readthedocs.io/en/latest/pygame_gui.elements.html#pygame_gui.elements.ui_window.UIWindow.kill)
> 
> Always open to new documentation ideas though.

Bruh, looks like I missed them.

**Comment by TechStudent10** [comment]
Well, I guess I'll close the issue now. Thanks for the help!
