### ISSUE TITLE
UIStatusBar and subclass can't be put inside a container

### ISSUE THREAD

**Issue by Giatroo** [MyreMylar/pygame_gui#325]
**Describe the bug**
As any UIElement, the UIStatusBar accepts a `container` parameter to make it easy to insert into the layout. However, the UIStatus and all its subclasses completely ignore the `container` parameter.

**To Reproduce**
The following code is an example of what I'm saying. The second UIStatusBar object should be inside the UIPanel object, however, it's being created at the global (20, 20). 

```python
import pygame
import pygame_gui
from pygame_gui.elements.ui_panel import UIPanel
from pygame_gui.elements.ui_progress_bar import UIProgressBar
from pygame_gui.elements.ui_status_bar import UIStatusBar

pygame.init()
display_surface = pygame.display.set_mode((800, 600))
clock = pygame.time.Clock()

manager = pygame_gui.UIManager((800, 600))

panel = UIPanel(
    pygame.Rect(100, 100, 400, 300),
    starting_layer_height=0,
    manager=manager
)
world_bar = UIStatusBar(
    pygame.Rect(20, 400, 100, 25),
    manager=manager
)
container_bar = UIStatusBar(
    pygame.Rect(20, 20, 100, 25),
    manager=manager,
    container=panel,
)
world_inside_container_bar = UIStatusBar(
    pygame.Rect(120, 120, 100, 25), 
    manager=manager
)

is_running = True

while is_running:
    time_delta = clock.tick(60) / 1000.0
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            is_running = False

        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_q:
                is_running = False

        if event.type == pygame_gui.UI_BUTTON_PRESSED:
            event.ui_element.event()

        manager.process_events(event)

    manager.update(time_delta)

    manager.draw_ui(display_surface)

    pygame.display.update()
```

**Expected behaviour**
The second UIStatusBar object should be exactly where the third is (i.e. (120, 120)).

**Screenshots**
![image](https://user-images.githubusercontent.com/13424358/186048037-8964f36b-f443-46f7-af9c-85c3a4788431.png)

**Platform and software (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Pygame GUI version: 0.6.4
 - Pygame version: 2.1.2

**Additional Information**
I really think this is a problem, given the way all the other UIElements work. If it's an intended feature, please let me know (and please tell me how to do it properly, because I really want to put UIStatusBars inside UIPanels).

**Comment by MyreMylar** [comment]
Hi, this issue was fixed in a commit to main a while ago:

https://github.com/MyreMylar/pygame_gui/commit/cabd4cdee8f6b65121a741ad9fa6ec569d326dc5

So this should work properly in the 0.6.5 release - or you could download main from this page and build it yourself with a `pip install . -U` command.

**Comment by Giatroo** [comment]
Indeed, that's working now =) 

Thank you so much! You've done a really great work with this project, I appreciate it.
