### ISSUE TITLE
The `allow_existing_files_only` option of `UIFileDialog` does not do anything

### ISSUE THREAD

**Issue by ndgnuh** [MyreMylar/pygame_gui#333]
**Describe the bug**
There are actually two bugs regarding the option:
- The `allow_existing_files_only` option of `UIFileDialog` doesn't work.
- When picking a file and then pressing backspace or delete, `IndexError` is thrown. This can't be reproduced when setting `allow_existing_files_only=True` (default).

**To Reproduce**

1. Run the example source code (see the code below)
2. Input any non-existing path in the file picker
3. The OK button is still disabled
4. Pick any existing file
5. Press delete or backspace right after that

**Expected behavior**
The ok button is enabled when inputting a non-existing path (so I can create a new file). backspace will delete a character in the current file path (example usecase: delete the file extension and write a new one).

**Screenshots**
![image](https://user-images.githubusercontent.com/33273948/194338872-3a82e390-29e2-4ca8-841e-99f6f5c6f860.png)

**Platform and software (please complete the following information):**
 - OS: Linux
 - Pygame GUI version 0.6.4
 - Pygame version 2.1.2

**Additional context**

The MWE code:
```python
import pygame_gui
import pygame


def main():
    pygame.init()
    pygame.display.set_caption("Bug")
    root = pygame.display.set_mode((800, 600), pygame.RESIZABLE)
    ui_manager = pygame_gui.UIManager(root.get_size())

    picker = pygame_gui.windows.UIFileDialog(
        rect=pygame.Rect(0, 0, 400, 400),
        window_title="save",
        manager=ui_manager,
        allow_existing_files_only=False)

    clock = pygame.time.Clock()
    while True:
        time_delta = clock.tick(60) / 1000.0
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                return

            if event.type == pygame_gui.UI_FILE_DIALOG_PATH_PICKED:
                print(event)

            ui_manager.process_events(event)
        ui_manager.update(time_delta)
        background = pygame.Surface(root.get_size())
        background.fill(pygame.Color(31, 31, 31))
        root.blit(background, (0, 0))
        ui_manager.draw_ui(root)
        pygame.display.update()


if __name__ == "__main__":
    main()
```

Stacktrace of the crash:
```python
Traceback (most recent call last):
  File "/home/hung/Projects/erl-tool/bug.py", line 37, in <module>
    main()
  File "/home/hung/Projects/erl-tool/bug.py", line 27, in main
    ui_manager.process_events(event)
  File "/home/hung/.local/lib/python3.9/site-packages/pygame_gui/ui_manager.py", line 221, in process_events
    consumed_event = ui_element.process_event(event)
  File "/home/hung/.local/lib/python3.9/site-packages/pygame_gui/elements/ui_text_entry_line.py", line 380, in process_event
    elif self._process_action_key_event(event):
  File "/home/hung/.local/lib/python3.9/site-packages/pygame_gui/elements/ui_text_entry_line.py", line 485, in _process_action_key_event
    self.drawable_shape.text_box_layout.delete_selected_text()
  File "/home/hung/.local/lib/python3.9/site-packages/pygame_gui/core/text/text_box_layout.py", line 719, in delete_selected_text
    raise IndexError('No selected rows.')
IndexError: No selected rows.
```

**Comment by MyreMylar** [comment]
Thanks for the report! I shall try to roll a fix for the crash into the next version and look over that PR you have submitted also.
