### ISSUE TITLE
Fully Transparent buttons have a faint border

### ISSUE THREAD

**Issue by keyraven** [MyreMylar/pygame_gui#354]
**Describe the bug**
When using a theme that sets both the button background and border to fully transparent (#00000000), the buttons still appears to have faint gray-ish border. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a button using a theme where the background and border are fully transparent (#00000000). 
2. There will be a light gray border around the button. 

**Expected behaviour**
I would expect the button to lack the light gray border, and be fully transparent. 

**Screenshots**
![image](https://user-images.githubusercontent.com/118307471/202868530-7b085a30-bb55-4337-af5b-4a10f5d57c78.png)

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.5
 - Pygame version 2.1.2

**Comment by MyreMylar** [comment]
You need to set the shadow width to 0 as well

**Comment by keyraven** [comment]
Thanks! That got rid of the shadow!
