### ISSUE TITLE
Specfiy Line Spacing for Text Boxes

### ISSUE THREAD

**Issue by keyraven** [MyreMylar/pygame_gui#360]
**Is your feature request related to a problem? Please describe.**
Occasionally, I want to be able to control the line spacing in a text box.  However, UITextBox does not allow the user to specify line spacing.  From what I've seen, line spacing is a parameter into the text parser, but it's set at 1.25 for all text boxes.  

**Describe the solution you'd like**
Ideally, I'd like line spacing to be a theme parameter.

**Comment by MyreMylar** [comment]
Good idea, I'll look into this. Not sure if there was a reason I didn't expose it or, just ran out of time.

**Comment by Starbuck5** [comment]
I just ran into this as well, trying to update from an older version of pygame-gui (0.4 or 0.5) on one of my games.

It seems like the line spacing default has changed since then, without a way to set it back.
