### ISSUE TITLE
TextBox appending bhaves really weird

### ISSUE THREAD

**Issue by dMight-O** [MyreMylar/pygame_gui#364]
**Describe the bug**
Appending some text to the box actually appends everything that was appended before with it.

**To Reproduce**
1. Create a Textbox
2. Append some text when a key is pressed (for example) : using a variable incremented after the key is pressed help more

**Expected behaviour**

**Screenshots**

https://user-images.githubusercontent.com/108240857/205904819-e651ed97-68fd-4c17-bed2-c4acbb8f6ec9.mp4

**Platform and software (please complete the following information):**
 - OS:Ubuntu 22.04
 - Pygame GUI 0.6.5
 - Pygame version 2.1.2

**Additional context**

**Comment by MyreMylar** [comment]
Could you paste some of the code you are using?

**Comment by dMight-O** [comment]
it's not really clean sorry : https://bin.readthedocs.fr/tupele.py

**Comment by dMight-O** [comment]
Do you think it can be fixed in the next days? I would like to know if i'm still using it in the project

**Comment by dMight-O** [comment]
Thanks ! :100:
