### ISSUE TITLE
Layered Buttons Will Always Prefer The Bottom Button

### ISSUE THREAD

**Issue by scribblecrumb** [MyreMylar/pygame_gui#394]
**Describe the bug**
Our project requires buttons to be layered over top each other quite frequently, which has proven to be a challenge with pygame_gui.  It seems that the first button created is always preferred over subsequent buttons. Thus, if two buttons occupy the first space, the button "on the bottom" of the stack will be the button that responds to the user's inputs.  It doesn't matter if the bottom button is disabled or hidden. While it doesn't respond to the user's inputs anymore, the other button in the stack still will not work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create two UIButtons and place them in the same space.  
2. Run the program and attempt to click on the top button. Any part of the button that overlaps with the button button will instead activate the bottom button.

**Expected behaviour**
I would expect for the last button created in a space to be the button that is preferred for user input.  This is how pygame seems to work as default, as we didn't have this issue until implementing pygame_gui

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.7
 - Pygame version 2.1.2

**Comment by MyreMylar** [comment]
Hello,

This isn't a design type I've encountered before but I had a go at implementing it in Pygame GUI:

```
import pygame

from pygame_gui import UIManager, UI_BUTTON_PRESSED
from pygame_gui.elements import UIButton, UITextEntryLine


pygame.init()


pygame.display.set_caption('Quick Start')
window_surface = pygame.display.set_mode((800, 600))
manager = UIManager((800, 600), 'data/themes/quick_theme.json')

background = pygame.Surface((800, 600))
background.fill(manager.ui_theme.get_colour('dark_bg'))


hello_button = UIButton((350, 280), 'Hello')

hello_button_on_top = UIButton((370, 290), 'Hello on top', starting_height=2)

hello_button_on_top_of_that = UIButton((390, 300), 'Hello on top of that', starting_height=3)

clock = pygame.time.Clock()
is_running = True

while is_running:
    time_delta = clock.tick(60)/1000.0
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            is_running = False
        if event.type == UI_BUTTON_PRESSED:
            if event.ui_element == hello_button:
                print('Hello World 1!')
            if event.ui_element == hello_button_on_top:
                print('Hello World 2!')
            if event.ui_element == hello_button_on_top_of_that:
                print('Hello World 3!')
        manager.process_events(event)

    manager.update(time_delta)

    window_surface.blit(background, (0, 0))
    manager.draw_ui(window_surface)

    pygame.display.update()

```

Which seems to do pretty much what I'd expect (though I should probably be swallowing the hover while you have a button held down too).

The UI mouse interactions are done based on the layer system with higher layers tested for interaction first before falling through to lower levels.

Does this work for your use case?

**Comment by scribblecrumb** [comment]
That does work!  I'd been under the impression that someone else on our team had tried using the layer system and not had any luck, must have been a misunderstanding though.  Or perhaps the buttons were being checked for interaction in the wrong order.  Thank you for your time!
