### ISSUE TITLE
Hyperlinks don't work when wrap_to_height set to True in UITextBox

### ISSUE THREAD

**Issue by MrChuse** [MyreMylar/pygame_gui#398]
**Describe the bug**
Hyperlinks don't work when wrap_to_height is set to True in UITextBox.
When wrap_to_height is set to False they work as expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create UITextBox with a link like `UITextBox('<a href=\'target\'>Hello, world</a>', pygame.Rect((0,0), (100, 100)), manager, wrap_to_height=True)`
2. Try to use a link and it doesn't highlight nor fire events.
3. When wrap_to_height is False, it does actually change its hover state and is clickable.

**Expected behaviour**
I expected the hyperlink to be clickable

**Screenshots**
![image](https://user-images.githubusercontent.com/43815531/213763298-c8c08fe3-8ee4-4a98-b439-2076f34adfde.png)
![image](https://user-images.githubusercontent.com/43815531/213763354-6bebb381-e5f3-494a-a7f8-d0d9bfce1b88.png)
The first screenshot is taken with `wrap_to_height=True`, the second one with `wrap_to_height=False`. I hope it's clear that the second link is highlighted, I'm using the default theme.

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.8
 - Pygame version 2.1.2

**Additional context**
Sample file is attached, try launching it and it will probably reproduce 
[uitextbox_test.txt](https://github.com/MyreMylar/pygame_gui/files/10468297/uitextbox_test.txt)

I've managed to debug it to, hopefully, the root and `UITextBox.redraw_from_text_block` is the problem:
```Python
if (self.scroll_bar is None and
                (self.text_box_layout.layout_rect.height > self.text_wrap_rect[3])):
            self.rebuild()
```
This rebuild is always triggered when `text_wrap_rect[3]` equals -1 (aka when wrap_to_height is set to True, maybe elsewhen?)
Rebuild parses the text: `self.parse_html_into_style_data()`
The text is passed to HTMLParser: `self.parser.feed(feed_input)` and it calls `handle_data(data)` for each chunk
And then `HyperlinkTextChunk`s are created: `chunk = self.create_styled_text_chunk(text)`
However, these HyperlinkTextChunks are created on each update cycle because update calls it:
```Python
for chunk in self.link_hover_chunks:
                hovered_currently = False

                hover_rect = pygame.Rect((base_x + chunk.x,
                                          base_y + chunk.y),
                                         chunk.size)
                if hover_rect.collidepoint(mouse_x, mouse_y) and self.rect.collidepoint(mouse_x,
                                                                                        mouse_y):
                    hovered_currently = True
                if chunk.is_hovered and not hovered_currently:
                    chunk.on_unhovered()
                    should_redraw_from_layout = True
                elif hovered_currently and not chunk.is_hovered:
                    chunk.on_hovered()
                    should_redraw_from_layout = True
if should_redraw_from_layout:
                self.redraw_from_text_block()
```
 and therefore the on_hover property is set to True in the `UITextBox.update()` but is always reset to False when the rebuild happens.

**Comment by MyreMylar** [comment]
Thanks for the report!

Looks like I either need a better test for if the size of the text rectangle has changed, or to check chunks current hover status when rebuilding - probably both.
