### ISSUE TITLE
KeyError in UIElement when using (-1,-1) for rect width and height, and 'center': 'center' for anchor

### ISSUE THREAD

**Issue by Hamada-Gado** [MyreMylar/pygame_gui#399]
**Describe the bug**
KeyError is raised when starting the program. When using 'center': 'center' as an anchors entry, (-1,-1) as the second argument to rect
in an UIElement object instantiation. Like UILabel and UIButton.

**To Reproduce**
Steps to reproduce the behaviour:
When making a UILabel for example:
 pgg.elements.UILabel(
            relative_rect= pg.Rect((0, 10), (-1, -1)),
            text= "Title", manager= self.manager,
            object_id= "title_label",
            anchors= {
                'centerx': 'centerx',
                'top': 'top',
            } 
        )

**Expected behaviour**
The program should start without raising exceptions and a rect with text `Title`, 10 pixels down from the top of the window, and centered in the middle of the window horizontally 

**Screenshots**
![image](https://user-images.githubusercontent.com/108872265/215269844-6cd265b6-db53-4c2a-82ca-0e45423999e8.png)

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.8
 - Pygame version 2.1.2
 - Python 3.10.9

**Additional context**
# My Solution
* in C:\...\Python\Python310\site-packages\pygame_gui\elements\ui_label.py and C:\...\Python\Python310\site-packages\pygame_gui\elements\ui_button.py
## I changed in **rebuild** method lines (178, 183) for ui_label.py and (768, 773) for ui_button.py
* if self.anchors['left'] == 'right' and self.dynamic_width: to if self.anchors.get('left') == 'right' and self.dynamic_width:
* if self.anchors['top']== 'bottom' and self.dynamic_width: to if self.anchors.get('top') == 'bottom' and self.dynamic_width:

* so that if the key is not found None is returned and no KeyError is raised. This solved my problem and the code in **To Reproduce** now works.

# One Last Thing
I hope this solution will help you. But I don't know if this solution will affect other things as I am new to this module I just started using it, and the same error probably will appear in other elements, so I hope to know if there is a better solution or if this solution will cause problems. Thanks in advance.

**Comment by MyreMylar** [comment]
I'll look into this, thanks for the report.

The center anchors are pretty new so I'm not surprised they've got some issues.
