### ISSUE TITLE
Pyinstaller hook failing on MacOS GitHub runner

### ISSUE THREAD

**Issue by larkgz** [MyreMylar/pygame_gui#406]
**Describe the bug**
Pyinstaller hook failing on MacOS GitHub runner, causing the game to crash on launch.

**To Reproduce**
Steps to reproduce the behaviour:
1. Freeze a program that uses pygame-gui using Pyinstaller on the `macos-11` runner on GitHub
2. Attempt to run the program on a Mac
3. Program crashes

**Expected behaviour**
The program does not crash.

**Screenshots**
GitHub Actions log: 
<img width="860" alt="image" src="https://user-images.githubusercontent.com/63805048/219798962-8fe67075-a6ac-4606-b404-548cb66e116e.png">

Traceback:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/63805048/219799866-4d477bb2-9d3f-4db1-8e18-8b03d4164462.png">

**Platform and software (please complete the following information):**
 - OS: Mac
 - Pygame GUI version: 0.6.8
 - Pygame version 2.1.3

**Additional context**
This does not occur when I run Pyinstaller locally on my own system. In the workflow, we're using `actions/setup-python` to setup Python and installing packages using `pip`. The hook did not fail on Pygame 2.1.2.

**Comment by MyreMylar** [comment]
I wonder if this is related to a bug we had over on pygame-ce with mac runners no longer installing pkg-config by default, so freetype didn't install properly - then cascading from there?

see: [https://github.com/pygame-community/pygame-ce/pull/1888](https://github.com/pygame-community/pygame-ce/pull/1888)

**Comment by MyreMylar** [comment]
Or it is the mac font rendering bug:

https://www.reddit.com/r/pygame/comments/11505q9/pygamefontinit/
