### ISSUE TITLE
-1 Dimensions Broken on Text Boxes

### ISSUE THREAD

**Issue by scribblecrumb** [MyreMylar/pygame_gui#412]
**Describe the bug**
The documentation says that setting the dimensions of the rect to -1 will cause the text box to match the final dimension to whatever the text rendering produces.  While it does match the final dimensions correctly, it doesn't seem to draw the textbox onto the screen and so the box appears to be invisible.

I got around this by using get_relative_rect() to find the new dimensions, then creating the textbox again using the new dimensions.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new UITextBox with -1 as one or both of the dimensions.

**Expected behaviour**
I would expect the text box to adjust it's dimensions and still display on the screen without any extra input from me.

**Screenshots**

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.8
 - Pygame version 2.2.0

**Comment by iljah** [comment]
I get same behavior in Linux, pygame 2.3.0, pygame gui 0.6.8.

**Comment by scribblecrumb** [comment]
.set_dimensions() also seems to be broken, I assume these two issues might be related

**Comment by ImLvna** [comment]
Our team found it can be bypassed via this:

(not working)
```py
elem = pygame_gui.elements.UITextBox("", pygame.Rect((0, 0), (100, -1))
# stretches as it gets filled
```

(bypass)
```py
elem = pygame_gui.elements.UITextBox("", pygame.Rect((0, 0), (100, -1))
# doesnt stretch, but get_relative_rect returns the stretched value, so we recreate with that
info_rect = elem.get_relative_rect()
elem.kill()
elem = pygame_gui.elements.UITextBox("", info_rect)
```
