### ISSUE TITLE
Only English words are supported in UITextEntryBox and UITextEntryLine, instead of multiple languages.

### ISSUE THREAD

**Issue by glut410** [MyreMylar/pygame_gui#413]
**Describe the bug**
There will be no some particular displays of typing something lke mandarin, Japanese, etc.

**To Reproduce**
Steps to reproduce the behaviour:
1. typing mandarin or any other language except English, but not just copy it to the UITextEntryBox or UITextEntryLine :)

**Expected behaviour**
Nothing will show on the textbox.

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.8
 - Pygame version 2.2.0

**Additional context**
i do not have any ideas to solve this problem now, waiting for some big cheeses :)

**Comment by zeroxer** [comment]
@MyreMylar IME hide when input Chinese to UITextEntryBox.
 Normally, it should have the ime show on top of pygame window.
![image](https://github.com/MyreMylar/pygame_gui/assets/15977179/8f9a46db-1737-4bce-91cb-ce6736547644)

Here is an example which can show IME. https://stackoverflow.com/a/72667710/7057648
![image](https://github.com/MyreMylar/pygame_gui/assets/15977179/6ad81c1b-3999-4406-a362-a952ae135bb7)

[How do I enable Chinese input in pygame?](https://stackoverflow.com/questions/72666159/how-do-i-enable-chinese-input-in-pygame)

Is there any method to show IME when input to UITextEntryBox?
