### ISSUE TITLE
Html anchor tag is interpreted as <module>, breaking link

### ISSUE THREAD

**Issue by ImLvna** [MyreMylar/pygame_gui#423]
**Describe the bug**
For some reason, when i try to use `<a href=https://discord.com/invite/xxxxxx/>https://discord.com/invite/xxxxxx/</a>`, I get this error:
`<pymodules>\pygame_gui\core\text\html_parser.py:149: UserWarning: Unsupported HTML Tag <module>. Check documentation for full range of supported tags.`

We use anchor tags in another place in the same module, via `<a href=https://creativecommons.org/licenses/by-nc/4.0/legalcode>CC-BY-NC 4.0</a>` and the link works exactly as expected. Both the working and not-working are inside UITextBox-es, albeit seperate. An oddity in this is that the broken link still follows the link_text and link_hover theming...

**Expected behaviour**
Link will function as normal.

**Screenshots**
Bad link:
![image](https://user-images.githubusercontent.com/44179559/224509610-3f514515-80e0-48a5-8d3c-f2687616b494.png)
![image](https://user-images.githubusercontent.com/44179559/224509639-6d645aa6-6039-4381-b4d1-632567335962.png)
![image](https://user-images.githubusercontent.com/44179559/224509644-ccb85a09-dd9b-401c-89ac-4e8a0ba4bec4.png)

Working link:
![image](https://user-images.githubusercontent.com/44179559/224509695-89e0c4ed-cc30-45c0-b915-e672a33dd2dc.png)
![image](https://user-images.githubusercontent.com/44179559/224509725-37e982d7-243f-432e-9c66-20e89671f3f8.png)
![image](https://user-images.githubusercontent.com/44179559/224509744-5049dc36-fcc2-4087-b6ba-8e12cd249b8a.png)
![image](https://user-images.githubusercontent.com/44179559/224509754-464de9a2-d6ce-469e-85a1-e02551e144db.png)

**Platform and software (please complete the following information):**
 - OS: Windows, occurs on linux hyperv vm
 - Pygame GUI version: 0.6.8
 - Pygame version: pygame 2.1.3.dev8 (SDL 2.0.22, Python 3.10.10)

**Comment by MyreMylar** [comment]
Hmm, are you sure it is firing from that link?

The error in your screenshot is from the HTML parser which thinks it has tried to parse a tag that looks something like `<module>`.

If you do have any text that looks like `<module>` you can use `"my text " + html.escape("<module>") + " other text here"` to fix it.

**Comment by ImLvna** [comment]
Oh, sorry 😓 it appears the <module> part is from putting a raw traceback output into a textbox
![image](https://user-images.githubusercontent.com/44179559/224511208-7661f1fa-b7e7-4f3a-8513-70711154f195.png)
Sadly that still doesnt explain why nothing happens when you click the broken link. Ive tried messing around with the layering to no avail.

**Comment by ImLvna** [comment]
If it helps, heres the layering overlay: 
![image](https://user-images.githubusercontent.com/44179559/224511437-d5fa929d-2a58-4d20-b98e-5496462bcfc5.png)

**Comment by ImLvna** [comment]
Also sorry to combine two bug reports into one, but if you have a usecase where a link is accross multiple lines, only the last line will change colors on hover/click 
![image](https://user-images.githubusercontent.com/44179559/224511511-4b92ca88-2e21-4171-ad72-35c666be9ac6.png)
![image](https://user-images.githubusercontent.com/44179559/224511520-dd0a1b6f-7fd5-48c1-84ed-88efa0e7bcf2.png)

**Comment by ImLvna** [comment]
Adding a debug print to html_parser.py ln131 reveals that it _is_ detecting the correct href attribute
`print("link href: ", attributes['href'])
style["link_href"] = attributes['href']`

`link href:  https://discord.com/invite/x`

`link href:  https://www.mozilla.org/en-US/MPL/2.0/
link href:  https://creativecommons.org/licenses/by-nc/4.0/legalcode`

**Comment by ImLvna** [comment]
Hello there, i found the problem 😅 I was under the impression that pyg_gui handled opening links, and not that it was an event, I had copied the code from a different class in the module, and seem to have just glazed over UI_TEXT_BOX_LINK_CLICKED. Im so sorry for wasting your time
