### ISSUE TITLE
Enhancement: a UI_SCROLLED event

### ISSUE THREAD

**Issue by dakydaky** [MyreMylar/pygame_gui#427]
**Is your feature request related to a problem? Please describe.**
I am working with a custom extension of pygame_gui which contains a new table element that boil down to a UIScrollingContainer with a number of vertical rows that can contain various elements. However, when a row contains a UIButton, the button will remain clickable even when outside of the table's viewport (depending on the scrolling area position). If the screen is clicked at the point where a non-visible button is underneath, the button will still be triggered. See context for clarification.

**Describe the solution you'd like**
Enter the pygui.UI_SCROLLED event. In conjunction with collider rectangle, can be used to enable and disable elements which are not visible on the screen on demand, as the user scrolls up and down the table. This should in theory prevent the user from clicking on the  buttons outside of the table viewport. This event is also potentially triggered when the scrollbar is created or destroyed.

        #elif event.type == pygui.UI_SCROLLED:
        #    print("UI scrolling detected!")
        #    for row in self.TABLE_CONTAINER.rows:
        #        for element in row:
        #            if isinstance(element, pygui.elements.UIButton):
        #                if not self.TABLE_CONTAINER.get_relative_rect().colliderect(element.rect):
        #                    element.visible = False
        #                else:
        #                    element.visible = True

**Additional context**
![image](https://user-images.githubusercontent.com/32701869/225612431-020a2ef0-decb-4f3b-bfbf-db20a4bccac0.png)
As indicated in the screenshot above, if the mouse click occurs outside of the scrolling container that contains the buttons, but at the place where the button is invisible, but below, the button will trigger. Such buttons should be disabled/invisible.

**Comment by MyreMylar** [comment]
This seems like a bug to me with events travelling down when they shouldn't I will investigate.
