### ISSUE TITLE
Crash Related to Themes

### ISSUE THREAD

**Issue by scribblecrumb** [MyreMylar/pygame_gui#428]
**Describe the bug**
I'm not entirely sure what's causing this, but it seems to be related to prototypes in theme files.  

I was working on consolidating a bunch of text box themes using prototypes. I ended up "nesting" prototypes within each other, but upon attempting to run the program it just ended up crashing.  I can't find any issues with my theme blocks.  I've put the traceback from the crash below.  It seems to be having trouble finding the font name, but the font name has definitely been defined.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create text box themes using prototypes within prototypes

**Expected behaviour**
I would expect for nested theming protoypes to work without crashing.

**Screenshots**
![image](https://user-images.githubusercontent.com/115410010/227119192-9b6ad767-9518-4103-b01c-0b42f9971828.png)
Crash traceback

![image](https://user-images.githubusercontent.com/115410010/227119612-f6b024bb-9537-4695-8fcb-58c28ebc54d4.png)
A bit of my theming blocks to show how I've nested prototypes. As you can see, the font name is defined in "#text_box"

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.8
 - Pygame version 2.2.0

**Comment by wkta** [comment]
can you post a pair of files that makes it **even easier** to reproduce that bug?

Like a `.py` and a `.json` file. I'm very new to `pygame_gui` but have a lot of Xp in python/pygame. If you share the pair of files that raises your Error I may be interested in investigating the issue

**Comment by MyreMylar** [comment]
Hmm I'm actually surprised prototype nesting works at all. In my head prototypes didn't inherit other prototypes. I'll investigate this.

**Comment by scribblecrumb** [comment]
> can you post a pair of files that makes it **even easier** to reproduce that bug?
> 
> Like a `.py` and a `.json` file. I'm very new to `pygame_gui` but have a lot of Xp in python/pygame. If you share the pair of files that raises your Error I may be interested in investigating the issue

I'll see if I can whip something up when I've got free time

**Comment by scribblecrumb** [comment]
> Hmm I'm actually surprised prototype nesting works at all. In my head prototypes didn't inherit other prototypes. I'll investigate this.

Oh! I didn't realize it wasn't an intended feature.  Well, I'm glad I could unintentionally test it haha
It did seem that once "#text_box_22" had the font name, any number of consecutive nested prototypes could be made without issue.  I've got one that's 5 prototypes deep.  So it doesn't seem like it's a limit to the number of nested prototypes, rather it's a problem with the first prototype in the chain.
