### ISSUE TITLE
Hebrew language support?

### ISSUE THREAD

**Issue by gonensel** [MyreMylar/pygame_gui#429]
his I create a new file dialog but the buttons don't appear. 

this is the code that I used for the create:
manager = pygame_gui.UIManager((SCREEN_SIZE[0], SCREEN_SIZE[1]))
file_dialog = pygame_gui.windows.ui_file_dialog.UIFileDialog(rect=pygame.Rect((SCREEN_SIZE[0]//2, SCREEN_SIZE[1]//2), (SCREEN_SIZE[1] * 0.7, SCREEN_SIZE[0] * 0.7)),manager=manager)

**Platform and software (please complete the following information):**
 - OS:  Mac
 - Pygame GUI version 0.6.8 
 - Pygame version 2.3.0
<img width="603" alt="image" src="https://user-images.githubusercontent.com/65337111/228445807-b614fb1f-db1d-42a5-911b-29b18b97432a.png">

**Comment by MyreMylar** [comment]
Looks like you have your height and width values the wrong way around.

**Comment by gonensel** [comment]
> Looks like you have your height and width values the wrong way around.
> […](#)

ok thanks its working 
I have another question there is support in Hebrew fonts?

**Comment by MyreMylar** [comment]
This was added in #511 and a few other following PRs. Closing this for now in preparation for 0.6.10 release later this week.
