### ISSUE TITLE
Tooltips on UIImage, UITextbox, and UILabel

### ISSUE THREAD

**Issue by scribblecrumb** [MyreMylar/pygame_gui#430]
**Is your feature request related to a problem? Please describe.**
I frequently find that it would be convenient to link a tool tip to a piece of text or to an image, rather than to just a button. 

**Describe the solution you'd like**
I'd like them to have the same tooltip system as UIButtons do, with theming capability and the tool tip text added within the element parameters.

**Describe alternatives you've considered**
I've been using a hack-y solution of a transparent UIButton layered over the image or text, but that's not ideal and adds more elements to juggle.

**Comment by MyreMylar** [comment]
I expect I can create a function called something like `.set_tooltip_text()` for all types of UI element and move the button only functionality over to that.

**Comment by scribblecrumb** [comment]
Oh that would be lovely!
