### ISSUE TITLE
Question About Docs and another question. 

### ISSUE THREAD

**Issue by TheShadowOfHassen** [MyreMylar/pygame_gui#431]
So this module looks really cool and I'd like to try to figure out how to use it. However, I don't get consistent internet where I live. Usually I can survive by downloading the pdf of the documentation, you don't have that. Could you please add it?

Also, do you have your pypi entry linked to this repository? If so, how do you do that? I have a module that I made that I'd like to have Pypi updated whenever I pass a release with Github but I can't figure out how.

Thanks!

**Comment by MyreMylar** [comment]
Hello,

I've enabled the PDF download in the 'flyout' menu on read the docs for the 'latest' version of pygame GUI:

https://pygame-gui.readthedocs.io/en/latest/ - you may need to hard refresh the page to make it appear, or you can just navigate directly to the pdf version here:

https://pygame-gui.readthedocs.io/_/downloads/en/latest/pdf/

As to PyPI I build and upload my wheels manually using:

```
python setup.py bdist_wheel -universal
twine upload dist/*
``` 

When making a release. 

From what I understand you _can_ set it up automatically with some clever use of Github Actions and a Github secret key. I believe we have this done over on Pygame-CE, but I didn't set it up myself so no first hand experience I'm afraid.

**Comment by TheShadowOfHassen** [comment]
Thanks!
