### ISSUE TITLE
Enable Text selection & copying for UITextBox

### ISSUE THREAD

**Issue by MyreMylar** [MyreMylar/pygame_gui#433]
**Is your feature request related to a problem? Please describe.**
Should be able to select text on `UITextBox` for copy to clipboard purposes.

**Describe the solution you'd like**
Enable CTRL+C copy key combo and text selection on `UITextBox`. Refactor UITextEntryBox to account for this functionality moving up the inheritance tree. Add a function to `.disable_text_selection()` so it works like now. Text selection should be the default presumption.

**Additional context**
Being able to select un-editable text and copy it is the default state on most apps and the web.

**Comment by chavi362** [comment]
@MyreMylar  Can you guide me to do this? on which file should I work?

**Comment by MyreMylar** [comment]
> @MyreMylar Can you guide me to do this? on which file should I work?

at the minute text copying is available in:

https://github.com/MyreMylar/pygame_gui/blob/main/pygame_gui/elements/ui_text_entry_box.py

it largely uses the `.select_range` property in various places in that file and the edit cursor, in fact most of the attributes in the current text entry box `__init__()` function will probably have to move up to the text box. I basically want to move about 75% of these controls, and the property itself, from `UITextEntryBox` over to `UITextBox`. the first inherits from the second so UITextEntryBox would work the same, but the non editable text box would now allow you to select text with the mouse and keyboard.  I suspect this might be quite tricky for a python novice, but no reason you can't have a go.

The Github read-only code viewer you go to when clicking the link above is a good example of how I want it to work - you can double click on text, drag select text with the mouse and edit selections with the shift key and arrow keys - but you can't use backspace or delete to edit the text.

**Comment by chavi362** [comment]
Thanks! I will work on it!
