### ISSUE TITLE
Scrolling on UITextBox and UIScrollingContainer

### ISSUE THREAD

**Issue by scribblecrumb** [MyreMylar/pygame_gui#450]
**Describe the bug**
You can no longer scroll via mouse wheel unless mousing over the scroll bar.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a UITextBox or UIScrollingContainer with enough text inside and small enough dimensions to cause a scrollbar to appear
2. Hover over the container/box and try to scroll using your mouse wheel

**Expected behaviour**
Previously I had no trouble with getting this to work.  At times, having a UIImage behind the box/container would cause this same behavior but that was solved by disabling the UIImage, Once disabled, the scroll would work fine.  However, now this is occurring with all text boxes/scrolling containers, regardless of any background UIImages, disabled or not.

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.9
 - Pygame-ce version 2.2.1

**Additional context**
Problem began after upgrading to 0.6.9 from 0.6.8

**Comment by MyreMylar** [comment]
Well dang. 

I'll look into it. Probably have to roll out a 0.6.10. Thanks for the report!

**Comment by MyreMylar** [comment]
I can't reproduce this in my examples or with a simple test program at the minute.

Do you have an example @scribblecrumb ?

This is the test program I've been using:

```
import pygame

from pygame_gui import UIManager
from pygame_gui.elements import UIScrollingContainer, UITextBox


pygame.init()


pygame.display.set_caption('Quick Start')
window_surface = pygame.display.set_mode((800, 600))
manager = UIManager((800, 600),
                    starting_language='en',
                    translation_directory_paths=['data/translations'])

background = pygame.Surface((800, 600))
background.fill(manager.ui_theme.get_colour('dark_bg'))

scrolling_container = UIScrollingContainer(pygame.Rect(0, 0, 200, 200))
scrolling_container.set_scrollable_area_dimensions((400, 400))

text_box = UITextBox(html_text="examples.holmes_text_test",
                     relative_rect=pygame.Rect(300, 0, 200, 200))

clock = pygame.time.Clock()
is_running = True

while is_running:
    time_delta = clock.tick(60)/1000.0
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            is_running = False

        manager.process_events(event)

    manager.update(time_delta)

    window_surface.blit(background, (0, 0))
    manager.draw_ui(window_surface)

    pygame.display.update()

```

And the scrolling seems to work fine when hovering the empty scrolling container or the text box. I'm guessing it is to do with the content inside your containers or text boxes?

**Comment by keyraven** [comment]
I believe I've been having the same issue, and it indeed has to do with content inside the scrolling container. 

When mousing over elements inside a scrolling container, you are unable to use the scroll wheel to control the outer scrolling container, even if that element doesn't have any scroll bar functionality (ie, text boxes without scroll bars, images, ext).  In previous versions, disabling (element_name.disable()) the inner element would allow you to use the scroll wheel while hovering over the inner element.  I'm not sure if this was intended behavior, but it was useful for some applications. 

I've edited your test program to reproduce the issue: 

```
import pygame

from pygame_gui import UIManager
from pygame_gui.elements import UIScrollingContainer, UITextBox, UIImage


pygame.init()


pygame.display.set_caption('Quick Start')
window_surface = pygame.display.set_mode((800, 600))
manager = UIManager((800, 600),
                    starting_language='en',
                    translation_directory_paths=['data/translations'])

background = pygame.Surface((800, 600))
background.fill(manager.ui_theme.get_colour('dark_bg'))

scrolling_container = UIScrollingContainer(pygame.Rect(0, 0, 200, 200))
scrolling_container.set_scrollable_area_dimensions((400, 400))

# The text in this box is short, a scroll bar is not generated.  
text_box = UITextBox("test text, short",
                     relative_rect=pygame.Rect(0, 0, 100, 100),
                     container=scrolling_container)
# Previously, disabling a text box would allow you to scroll the 
# container while mousing over the text box. 
# With the new update, this is no longer the case. 
text_box.disable()

# The same thing occurs with other elements, like UIImage
image = UIImage(relative_rect=pygame.Rect(0, 110, 100, 100),
                   image_surface=manager.universal_empty_surface,
                   container=scrolling_container)
# Like text boxes, disabling used to allow scrolling of the 
# outer scrolling continer. 
image.disable()

clock = pygame.time.Clock()
is_running = True

while is_running:
    time_delta = clock.tick(60)/1000.0
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            is_running = False

        manager.process_events(event)

    manager.update(time_delta)

    window_surface.blit(background, (0, 0))
    manager.draw_ui(window_surface)

    pygame.display.update() ```

**Comment by MyreMylar** [comment]
Thanks for the extra details! I look into this - it should be possible to pass the scroll events up the hover chain if they aren't being used.
