### ISSUE TITLE
"RuntimeError: The FreeType 2 library hasn't been initialized" after making a TextBox

### ISSUE THREAD

**Issue by Razboinicul** [MyreMylar/pygame_gui#467]
**Describe the bug**
I created a TextBox and when I start my prorgam I get "RuntimeError: The FreeType 2 library hasn't been initialized".

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a Pygame window and a UIManager
2. Create a TextBox
3. Run the program

**Expected behaviour**
I expected the program to work

**Screenshots**

**Platform and software (please complete the following information):**
 - OS: Linux (Xubuntu 22.04)
 - Pygame GUI version lastest
 - Pygame version 2.3.0

**Additional context**
Here is my code if you need it: https://github.com/Razboinicul/GraphicsEngine

**Comment by Razboinicul** [comment]
Nobody???

**Comment by MyreMylar** [comment]
Unfortunately you have posted a link to a large repo of files. Rather than
the place you used pygame gui.

From your error it looks like you haven't initialised pygame but hard to
say without seeing the specific code.

The library generally works including the text boxes.

**Comment by Jossl123** [comment]
I have the same error when creating a UIManager : 
```
import pygame
import pygame_gui
pygame_gui.UIManager((800, 500))
```

**Comment by MyreMylar** [comment]
Again, you need to initialise pygame-ce:

```python
import pygame
import pygame_gui

pygame.init()

pygame_gui.UIManager((800, 500))
```

Here is the full code example from the quickstart guide:
```python
 import pygame
 import pygame_gui


 pygame.init()

 pygame.display.set_caption('Quick Start')
 window_surface = pygame.display.set_mode((800, 600))

 background = pygame.Surface((800, 600))
 background.fill(pygame.Color('#000000'))

 manager = pygame_gui.UIManager((800, 600))

 hello_button = pygame_gui.elements.UIButton(relative_rect=pygame.Rect((350, 275), (100, 50)),
                                             text='Say Hello',
                                             manager=manager)

 clock = pygame.time.Clock()
 is_running = True

 while is_running:
     time_delta = clock.tick(60)/1000.0
     for event in pygame.event.get():
         if event.type == pygame.QUIT:
             is_running = False

          if event.type == pygame_gui.UI_BUTTON_PRESSED:
              if event.ui_element == hello_button:
                  print('Hello World!')

         manager.process_events(event)

     manager.update(time_delta)

     window_surface.blit(background, (0, 0))
     manager.draw_ui(window_surface)

     pygame.display.update()
```

Or you can read it in the docs: [https://pygame-gui.readthedocs.io/en/v_069/quick_start.html](https://pygame-gui.readthedocs.io/en/v_069/quick_start.html)
