### ISSUE TITLE
Add text_kwargs to all UI elements

### ISSUE THREAD

**Issue by axb2035** [MyreMylar/pygame_gui#469]
**Is your feature request related to a problem? Please describe.**
Not all UI elements support text_kwargs. It is hard to associate UI elements to each other when there are multiple instances of the same UI element being displayed. e.g. a dropdown for a specific task when multiple tasks and dropdowns are listed on screen and the task list is built dynamically from a DB (see example below).

**Describe the solution you'd like**
Please consider adding text_kwargs to all UI elements.

**Describe alternatives you've considered**
1. Create a #instance in the theme file for each element using the #name to associate with the task. If the associating information (e.g. task id) is dynamic it would mean constatly poking and reloading the theme file - this does not appear to be what the theme file is designed for and feels a very broken solution.
2. Load the associated elements into a UIContainer instance. However, the UIContainer also doesn't have a way to associate extra info e.g. which task_id do the elements in this container refer to? The solve would be when a drop down is changed - search the parent container elements to find a button where the text_kwarg value can be updated. In the example below would be to find the Confirm button in that container and update a text_kwarg value. Think this would work, but again feels clunky.
3. Build my own Class that wraps UIContainer and has the relevant values updated when dropdown (or other elements without text_kwargs) are changed. Feels like an uneccessary level of absraction, when it would be easier to just have UI elements support text_kwargs.

**Additional context**
See an example situation - there are two drop down lists with different values. When the top confirm button is hit how can it work out which DD is connected with that confirm button? For cancel and confirm buttons I use text_kwargs to associate the button with a `task_id` so I know which task to update in the DB when they are pressed... 
![image](https://github.com/MyreMylar/pygame_gui/assets/3905694/6eda568c-7484-4fd9-a34d-ceb77454ca36)

**Comment by MyreMylar** [comment]
I think you are describing the ObjectIDs that buttons can have here. They probably aren't explained that well in the events dialog but it should be perfectly possible to have two buttons with the text 'Confirm' on them with different object IDs so when the UI_BUTTON_PRESSED event is fired you can tell which one was pressed.

Here is a quick example:

```python
import pygame

from pygame_gui import UIManager, UI_BUTTON_PRESSED
from pygame_gui.core import ObjectID
from pygame_gui.elements import UIButton

pygame.init()

pygame.display.set_caption('Quick Start')
window_surface = pygame.display.set_mode((800, 600))
manager = UIManager((800, 600), 'data/themes/quick_theme.json')

background = pygame.Surface((800, 600))
background.fill(manager.ui_theme.get_colour('dark_bg'))

hello_button = UIButton((250, 280), 'Hello',
                        object_id=ObjectID(class_id="@polite_buttons",
                                           object_id="#hello_button"))

grumpy_hello_button = UIButton((500, 280), 'Hello',
                               object_id=ObjectID(class_id="@polite_buttons",
                                                  object_id="#grumpy_hello_button"))

clock = pygame.time.Clock()
is_running = True

while is_running:
    time_delta = clock.tick(60) / 1000.0
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            is_running = False
        if event.type == UI_BUTTON_PRESSED:
            if event.ui_object_id == "#hello_button":
                print('Hello World!')
            if event.ui_object_id == "#grumpy_hello_button":
                print('Ugh, hello.. I guess.')
        manager.process_events(event)

    manager.update(time_delta)

    window_surface.blit(background, (0, 0))
    manager.draw_ui(window_surface)

    pygame.display.update()

```

If I've misunderstood, I apologise.

**Comment by axb2035** [comment]
Thanks! I'll give it a go at sometime in the future. In the meantime I'll close this for now so there's one less issue :)
