### ISSUE TITLE
No possibility to enter some national letters due to conflicts of shortcuts

### ISSUE THREAD

**Issue by Toma400** [MyreMylar/pygame_gui#478]
**Describe the bug**
When you want to write some nation-specific letters, it conflicts with shortcuts to "select all" or "copy" text.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try making UITextEntryBox
2. Use Polish language keyboard
3. Try entering ą (ctrl + a)

**Expected behaviour**
Appearance of "ą", but selection of all appears instead. I assume ctrl+c will also result with copying instead of "ć".

**Screenshots**

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version: 0.6.5
 - Pygame version 2.1.2

**Additional context**

**Comment by MyreMylar** [comment]
Hello, just learning about this topic today, via your issue and this [medium post](https://medium.engineering/the-curious-case-of-disappearing-polish-s-fa398313d4df).

Do you think checking if Alt is not pressed in the CTRL+ shortcuts would resolve the issue for you? So you could press "Right Alt" which is actually CTRL+ALT+A to still enter the diacritic letters. I don't have a polish keyboard myself (I'm in the UK, but slightly oddly have a US keyboard) so this would very much be a case of changing something and hoping it works.

**Comment by MyreMylar** [comment]
in 0.6.10 CTRL+ALT+A will not select all the letters. I'm not sure if this will work with Right Alt on a polish keyboard allowing you to still type ą because I do not have one.

**Comment by MyreMylar** [comment]
Closing this as nobody else has volunteered to test if it is working now. If you find it is still broken, please re-open.
