### ISSUE TITLE
String constants

### ISSUE THREAD

**Issue by halfninja** [MyreMylar/pygame_gui#48]
**Is your feature request related to a problem? Please describe.**
There are various string IDs like `ui_button_pressed` and `typing_appear` - it would be useful if these were provided by the module as constants - as well as reducing typos it would make them more discoverable by IDE autocomplete.

**Describe the solution you'd like**
`pygame_gui.UI_BUTTON_PRESSED = 'ui_button_pressed'` or similar

**Comment by MyreMylar** [comment]
played around with python's Enums to try and solve this in a fancy way but couldn't match the simplicity of simple constants at putting everything in the module namespace in a way that IDE's could understand.

Fixed in bec58cba50fd896cdfdbf19f0ef77ae1527d4baf
