### ISSUE TITLE
update_theming for different shaped element(ellipse and rounded rectangle buttons) potentially not working

### ISSUE THREAD

**Issue by ryfz081** [MyreMylar/pygame_gui#485]
I am working on an interface for a music application and would like to use circular buttons for the Play, Stop, and Pause buttons. However when I use the update_theming method, no changes are applied. 

I interpreted the json parameter in two ways.

`hello_button.update_theming('button.json')`

```
hello_button.update_theming(
'{'
    '"button":'
    '{'
        '"misc":'
        '{'
            '"shape": "rounded_rectangle",'
            '"shape_corner_radius": "10"'
        '}'
    '}'
'}')
```
If I have used the method wrong, a clear example could be demonstrated in the documentation page or in an example program, that would be much appreciated!

**Comment by MyreMylar** [comment]
If you look in the examples GitHub repository linked from the readme, you
should see lots of examples that load a theme file into the UIManager,
which is what I think you are trying to do.

The quick start example is the simplest, but several of them use theme
files.
