### ISSUE TITLE
New UIElements [I have a working implementation!]

### ISSUE THREAD

**Issue by GimLala** [MyreMylar/pygame_gui#488]
I have felt the need for a few new elements:

1. An automatically resizing container. It should resize as new elements are added or removed. Should have a minimum size rect and maximum size rect which define the maximum and minimum size the container will resize to.
2. A scrolling container which automatically sets its scrollable container size to allow all elements to be visible. Also should allow the users to only scroll in the x or y direction if requested.
3. A form sort of element. This will enable easy input from users for example, to enter their details like username, age etc.
4. A sliding button in the colour picker which can be dragged to required colour (see screenshot below).
5. A clean way to implement 4 would be to add a 2D slider.

I have the working code for 1, 2, 4 and 5 ready, along with additions to the theme files. But I think it would require your help to actually properly get it integrated and working.

**Additional context**
<img width="458" alt="image" src="https://github.com/MyreMylar/pygame_gui/assets/74864888/5b4a285c-f8eb-40e9-a6fc-337c4eab895e">

I would be glad to contribute to your project :) If you have any questions, please feel free to ask

**Comment by MyreMylar** [comment]
Hello,

I do accept and review pull requests to this repository, so feel free to have a go at creating one.

Have you made a pull request to a github repository before? And do you know how to grab the latest 'main' branch of the library's code and build it yourself?

**Comment by GimLala** [comment]
Hello!
Yes, I do know how to make pull requests. I'm just a bit new to contributing. I'll make one and commit my suggested additions.
