### ISSUE TITLE
Add option (default?) to position/create windows & panels by their border edge (excluding shadows)

### ISSUE THREAD

**Issue by LondonClass** [MyreMylar/pygame_gui#495]
Under the default theme, when I create a button, it seems that there is still room for the button, but the button cannot display full text. When I create a window, the actual window size is 30 pixels smaller than expected. This is confusing. I hope to reduce the shadowwidth of the default theme to solve this problem.

**Comment by MyreMylar** [comment]
I don't really want to change the default theming size, but I would like to add an alternative way to create a window or a panel that has a certain interior size (i.e. excluding title bars, borders, shadows. Probably a little shim class called something like `InteriorDimensions()` that you could pass in and it would take the input size and output final dimensions that worked based on the current theming.

The text rendering getting clipped too tightly is a separate bug that has needed fixing for a while.

**Comment by LondonClass** [comment]
> 我真的不想更改默认主题大小，但我想添加另一种方法来创建具有特定内部尺寸（即不包括标题栏、边框、阴影）的窗口或面板。可能有一个小的填充程序类，你可以传入类似的东西，它将采用基于当前主题工作的输入大小和输出最终尺寸。`InteriorDimensions()`
> 
> 文本呈现被剪得太紧是一个单独的错误，需要修复一段时间。

![`5(R{PQJF(OG4@8B~BW JDM](https://github.com/MyreMylar/pygame_gui/assets/43668206/2e60c03a-392b-44c1-8b34-e915b1e7e77f)
The window is smaller than the screen. Black edges appeared.

**Comment by LondonClass** [comment]
> I don't really want to change the default theming size, but I would like to add an alternative way to create a window or a panel that has a certain interior size (i.e. excluding title bars, borders, shadows. Probably a little shim class called something like `InteriorDimensions()` that you could pass in and it would take the input size and output final dimensions that worked based on the current theming.
> 
> The text rendering getting clipped too tightly is a separate bug that has needed fixing for a while.

![FV1_K)_NK2G APENHQ%OZC6](https://github.com/MyreMylar/pygame_gui/assets/43668206/0d653b6d-9299-4798-ac3b-b6a1b27f143e)

The window is smaller than the screen. Black edges appeared.

![T0E%@ASSO` FXU 7D2@~1N5](https://github.com/MyreMylar/pygame_gui/assets/43668206/67766c00-155f-4d33-bb07-08979bdc08fa)

I wanted to arrange the two windows tightly, but there was a 30px seam.

**Comment by LondonClass** [comment]
![RQ8V$B@E)B5G)8$V`BS2P%U](https://github.com/MyreMylar/pygame_gui/assets/43668206/3226f307-c26d-4395-b820-bd6da5c9f51c)

Small buttons cannot accommodate enough text

**Comment by MyreMylar** [comment]
Resolved in #579
