### ISSUE TITLE
The tutorial on anchors is not easy to understand

### ISSUE THREAD

**Issue by LondonClass** [MyreMylar/pygame_gui#496]
I know anchors are a dictionary, and each key and value of anchors is a string. But I don't know what a dictionary entry means? Especially when anchors interact with rect, I can't understand it anymore. What does a negative width rect mean?

Can you modify the anchors tutorial to make it easier to understand?

**Comment by MyreMylar** [comment]
I could certainly add more visual examples of different anchoring scenarios. 

On a related topic, I will also try to extend the getting started tutorial a bit further to add some 'next steps' with the 'hello world' button like adding a theming file.

**Comment by LondonClass** [comment]
> I could certainly add more visual examples of different anchoring scenarios.
> 
> On a related topic, I will also try to extend the getting started tutorial a bit further to add some 'next steps' with the 'hello world' button like adding a theming file.

I actually prefer to add a logical description. Tell me the principle of anchor points and how anchor point values are calculated.
