### ISSUE TITLE
No Module named stringify

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#50]
**Describe the bug**
Unable to install pygame_gui.

**To Reproduce**
Steps to reproduce the behaviour:
1.  python -m pip install pygame-gui

**Expected behaviour**
Installation of pygame_gui

**Screenshots**
None

**Platform and software (please complete the following information):**
 - OS: Windows 10 (64bit)
 - Pygame GUI version: 0.4.0
 - Pygame version: 1.9.6 / 2.0.0dev6

**Additional context**
Tried two versions of pygame. 
Google suggested possibly a Path issue. Confirmed python's Path points to the project directory. 

 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Gabriel\AppData\Local\Temp\pip-install-56tyfvta\pygame-gui\setup.py", line 2, in <module>
        from stringify import stringify_py
    ModuleNotFoundError: No module named 'stringify'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Snayff** [comment]
I installed stringify via pip and I was then able install pygame GUI. I'm not sure if pygame GUI needs me to do so but I'll close the issue.

**Comment by MyreMylar** [comment]
Thanks for the report! This is actually fixed in the master branch already, as it happens - I noticed it a few days ago when setting up continuous integration. You only need stringify if you are going to build the library from source yourself (and only really if you change the default data and are trying to make a PyInstaller executable). If you just do:

`pip install pygame_gui`

it should install for end use.

**Comment by Snayff** [comment]
Using just `pip install pygame_gui` I get an error on `module object is not callable`, which is certainly a local issue. 

Using `python -m pip install pygame-gui` gives the stringify error above. I just uninstalled them both to test. ;)

**Comment by MyreMylar** [comment]
Ah, interesting I see a lot of people are having trouble with regular pip install calls online. Well, it should vanish when I do the next release on PyPi, but I might hurry that along now I've seen a few people having the same problem.
