### ISSUE TITLE
Images in theme not loading

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#51]
**Describe the bug**
I can't seem to get my theme to load into the UIManager, let alone be applied. I've been comparing the code to the tower defence game you linked and using the same approaches. 

**To Reproduce**
Load the theme:
`gui = pygame_gui.UIManager((VisualInfo.BASE_WINDOW_WIDTH, VisualInfo.BASE_WINDOW_HEIGHT), "data/ui/themes.json")`

Configure the theme (themes.json):
```
{
     "#skill_button":
     {
         "normal_image":
         {
             "path": "assets/skills/placeholder/icon_00.png"
         },
         "hovered_image":
         {
             "path": "assets/skills/placeholder/icon_00.png"
         }
     }
 }
```

Create the button:
```
skill = pygame_gui.elements.UIButton(relative_rect=pygame.Rect((x, y), (width, height)), text=f"{skill_slot}",  manager=manager,
                                                 container=self.get_container(), object_id=f"#skill_button")
```

**Expected behaviour**
Expected button to be shown with an image.

**Platform and software (please complete the following information):**
 - OS:  Windows 10 (64 bit)
 - Pygame GUI version : 0.4.0
 - Pygame version: 2.0.0dev6

**Additional context**
Nothing is applied on screen to the buttons, and when I inspect the gui (UIManager) the theme attirbutes show a lot of data I haven't set, like "#message_window", which I assume is somewhere in the defaults. Although, I didn't even see that when I was looking into the UIAppearanceTheme.

Am I missing something obvious? I tried using an os.abs path, and setting a colour in the json. Setting a colour in a "button" block applied to all buttons, and in the "#skill_button" block also applied, but the images didnt show either way. 

P.S. I debated adding this to the thread on reddit, but assumed it would be better suited here. Let me know if you'd rather I raise it somewhere else!

**Comment by MyreMylar** [comment]
You need an 'images' sub block like this:

```
{
     "#skill_button":
     {
         "images":
         {
              "normal_image":
              {
                 "path": "assets/skills/placeholder/icon_00.png"
              },
             "hovered_image":
             {
                 "path": "assets/skills/placeholder/icon_00.png"
             }
        }
     }
 }

**Comment by Snayff** [comment]
Ah, sorry buddy. That's such a rookie error. :(

**Comment by MyreMylar** [comment]
No worries. I'm sure there are lots of bugs hidden in my code somewhere and
the only way to find them is from people finding them and reporting back.
I'd much rather a ton of easily solved bug reports like this than none at
all :)

**Comment by zhuoyizhang** [comment]
How to load an image from the theme and still do convert_alpha()?
My goal is to attach an image with transparent center.
I only find the way to attack image from theme.
If there is a way for me to attach image to a button without theme that could be a workaround for me, but I couldn't find it.

Thanks!

**Comment by MyreMylar** [comment]
At the minute all images are loaded by calling convert alpha anyway so you
should be OK.
