### ISSUE TITLE
How to get the text currently displayed in a UITextEntryBox (not by "get_text()" to get the full text)?

### ISSUE THREAD

**Issue by meteorlin** [MyreMylar/pygame_gui#519]
![image](https://github.com/MyreMylar/pygame_gui/assets/49402403/3d34b06e-c0df-4c34-a59d-e00b690e3cef)

I wish to get the text currently displayed in the UITextEntryBox ("only astronomical object known... 70.8% of"), but not use `.get_text()` to get the full text of the UITextEntryBox, how should I do this?

Thanks in advance!

**Comment by GimLala** [comment]
You can use the `.get_text()` method on your TextEntryBox to get it

**Comment by MyreMylar** [comment]
There is currently no easy way to do this as it was not a use case that I anticipated anyone wanting.

I think you would need to delve into the innards of `text_box.text_box_layout`. The height adjustment that determines where we start drawing the visible text is calculated with:

```
height_adjustment = int(text_box.scroll_bar.start_percentage * text_box.text_box_layout.layout_rect.height)
```
then you would need to compare that against the position of all the rows stored in `text_box.text_box_layout.layout_rows` and then get the text for all the text chunks in all the rows that are in the visible range.

```
# first calculate list of rows in visible range of rows (i.e positions in layout between start position from scroll bar and the 'view_rect' height)
visible_text = ""
for row in visible_range:
    for chunk in row.items:
        visible text += chunk.text
```

Something like that anyhow.

**Comment by meteorlin** [comment]
Thanks for your answer! Under your guidance I completed the following code:

```python
from pygame_gui.core.text import LineBreakLayoutRect

...

# NOTE Based on the rendering matrix range of the text input box, determine which lines appear on the screen (only vertical scroll bars are processed)
p = text_area
height_adjustment = int(
    p.scroll_bar.start_percentage * p.text_box_layout.layout_rect.height
) if p.scroll_bar else 0
drawable_area_hight = max(1, (p.rect[3] -
                                (p.padding[1] * 2) -
                                (p.border_width * 2) -
                                (p.shadow_width * 2) -
                                (2 * p.rounded_corner_offset)))
# Process each row of rectangles
visible_rows = []
for line in p.text_box_layout.layout_rows:
    # Process blank lines
    if len(line.items) == 1 and isinstance(line.items[0], LineBreakLayoutRect):
        visible_rows.append("")
        continue
    # Process text line
    for item in line.items:
        if "text" in item.__dict__ and \
            item.top >= height_adjustment and \
                item.top <= height_adjustment + drawable_area_hight:
            visible_rows.append(item.text)
        
print(visible_rows)
```
