### ISSUE TITLE
Clipboard support broken with pygame-ce-2.4.1

### ISSUE THREAD

**Issue by swanux** [MyreMylar/pygame_gui#520]
For example the text entry box crashes on copy / paste shortcuts after the February 20th release of pygame-ce-2.4.1. It works in 2.4.0.

**Comment by MyreMylar** [comment]
What platform are you using? E.g. Windows, Mac, Linux.

**Comment by swanux** [comment]
Mac, but I believe this issue should be universal as it's related to API changes in pygame.scrap (?)

**Comment by MyreMylar** [comment]
> Mac, but I believe this issue should be universal as it's related to API changes in pygame.scrap (?)

It doesn't look like the code in scrap has changed between 2.4.0 and 2.4.1 (`scrap.c` last changed 4-5 months ago and 2.4.0 came out in January.

Testing locally on Windows with latest main pygame_gui and latest main pygame-ce I can copy and paste from the text entry box and text entry line without issue.

Is there any specific error you are getting when you see the crash? It could be some dependency change that is affecting mac only perhaps, though I think pygame-ce also hasn't changed SDL versions.

**Comment by swanux** [comment]
Well. I tested it on Linux, Windows and Mac (handy to have a triple boot system) - and the weird thing is, I can't reproduce the issue. I didn't include the error messages initially, because it seemed quite straightforward that this should be just a "for your notice" bugreport. And now, it works. Even though nothing changed, just the pygame-ce versions...


With all this, I think it can be closed. If somehow I manage to reproduce the issue, I'll update this.

**Comment by MyreMylar** [comment]
OK, I will close this for now. Please re-open if you manage to figure anything out. I know that copy & paste on mac can be spicy sometimes.
