### ISSUE TITLE
text_horiz_alignment_method Doesn't Have Documentation

### ISSUE THREAD

**Issue by GimLala** [MyreMylar/pygame_gui#525]
**Is your feature request related to a problem? Please describe.**
I saw that the default theme file uses this property in vertical scroll bar's buttons and horizontal scroll bar's buttons but the UIButton documentation in readthedocs.io doesn't include those properties. Do those properties actually exist? And how does one use them?

**Describe the solution you'd like**
The documentation to be updated, describing the various options for the property in detail

**Comment by MyreMylar** [comment]
Yes, this parameter has one specific purpose - namely that arrows don't look right when you center them mathematically correctly (as I do for everything else). Instead you have to offset the centering in the direction the arrow is pointing to achieve visual normality.

Outside of that niche use case `text_horiz_alignment_method` and `text_vert_alignment_method` don't really have much general use.

**Comment by GimLala** [comment]
Oh so you mean like the triangle character in scroll bars? Yeah i can't think of any more uses for that.
