### ISSUE TITLE
Adding Required text input

### ISSUE THREAD

**Issue by GimLala** [MyreMylar/pygame_gui#526]
**Is your feature request related to a problem? Please describe.**
While I was implementing forms I thought some form of "required" fields would be a great addition, which would perhaps show an error message or something to the user when the user enters an empty value

**Describe the solution you'd like**
I would like input elements like `UITextEntryLine`, `UITextEntryBox`, `UIDropdown`, `UISelectionList` etc. to have a method where one can set whether the input is required or not. (Perhaps not all of them if you feel ilke that's too much, but atleast the first 2)

**Describe alternatives you've considered**
I thought of implementing it inside the `UIForm` class instead but I think it is probably better to have it for the input elements as that could be used for more cases.

**Comment by MyreMylar** [comment]
Of these elements only the text line has a default input I would think of as a 'submission' type event - namely pressing 'enter'.

Generally when I've seen 'required fields' on form entries the verification of the data is generally done when you submit the entire form. e.g. a Google Forms form not on individual elements. Is there any context outside of a form entry event when you would want this? If not I think it mostly lives at the UIForm level. You could perhaps do things with theming to highlight required fields & missed required fields visually (a little red pulse of the border colour or something) with a bit of tinkering.

**Comment by GimLala** [comment]
Yeah, perhaps if there is any other place where they need that verification, they can always put the element in the UIForm. Now that I think about it with a fresh mind, I have also only seen this in forms and it makes sense for it to be put in forms.
