### ISSUE TITLE
Create UIPanel element

### ISSUE THREAD

**Issue by MyreMylar** [MyreMylar/pygame_gui#54]
**Is your feature request related to a problem? Please describe.**
Sometimes you want a 'panel' with basically nothing much on it that behaves a bit like a window but stays at whatever layer of the UI it starts and contains other elements.

This is sort of a halfway house between a window and the current bare-bones Container.

**Describe the solution you'd like**
You make a Panel, it has basic theming options (shape, shadow, border, padding) a rectangle then you fill it with other elements.

**Comment by ragerin** [comment]
I'd find it a bit semantically confusing to have both a Container- and a Panel-element.
Would implementing the theming options in the Container-class be a bad idea?

**Comment by MyreMylar** [comment]
Perhaps! I haven't really gone over this area of the code recently. I have it in my mind that the Window class is fairly tightly coupled with the Container class at the minute but that there is a need for a Window-like class that isn't shuffled around in the UI layers like windows are when they're in the stack.

**Comment by MyreMylar** [comment]
In the end I kept the distinction between Container and Panel - invisible containers ended up being useful all over the place in laying out other UI elements, tidying up lots of code. They are now present in the sliders, scroll bars and selection list elements and may end up in more places still eventually.

To salve the confusion somewhat, Panels and Windows will now act like containers for most 'end usage', so when you specify a container for your element you can specify a UIContainer, a UIPanel or a UIWindow and they work in what I feel is the intuitive way - e.g. for UIWindows, the 'contained area' is the part beneath the title bar and inside the window border, much as it works for pygame windows.

Panels themselves are still fairly straightforward Container + visual background, but also have an optional parameters to let you override the default container area with fatter (or thinner) margins and a required parameter to set their fixed layer position (as opposed to windows which shuffle around depending on which window is currently focused).

I imagine for most simple usages the Window and Panel will suffice, but the Container is there for people who want to dig in and roll their own element like bits and pieces of UI. And also for me.

**Comment by MyreMylar** [comment]
Also, tests and example done.
