### ISSUE TITLE
Character not displayed on UITEXTEntryBox but is acknowledged

### ISSUE THREAD

**Issue by Nughm** [MyreMylar/pygame_gui#555]
### Discussed in https://github.com/MyreMylar/pygame_gui/discussions/477

<div type='discussions-op-text'>

<sup>Originally posted by **Nughm** October 25, 2023</sup>
When using UITextEntryBox, when a line is deleted, and something is typed into it, a whitespace is created no matter which letter in inputted and when event.text is printed, it shows that the character is inputted.

https://github.com/MyreMylar/pygame_gui/assets/90173902/bbd82f0c-17bd-491c-8f03-3d1ac2eef028

At around 10 seconds, when the blinking typing indicator goes down from the blank line to "LINE2" the character "a" was inputted. This was not reflected on the EntryBox, but was printed when I closed the pygame window (I set it so it prints the contents of the EntryBox when pygame window is closed)
```python
import pygame
import sys
import pygame_gui

pygame.init()

WIDTH, HEIGHT = 1280, 720
SCREEN = pygame.display.set_mode((WIDTH, HEIGHT))
base_font = pygame.font.Font("font/Pixeltype.ttf", 20)

CLOCK = pygame.time.Clock()
MANAGER = pygame_gui.UIManager((WIDTH, HEIGHT))



TEXT_INPUT = pygame_gui.elements.UITextEntryBox(relative_rect = pygame.Rect((350, 275), (900, 600)), manager=MANAGER, object_id='#main_text_entry')
SCREEN.fill("White")
def get_user_name():
    while True:
        UI_REFRESH_RATE = CLOCK.tick(60)/1000

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                print(Temp)
                pygame.quit()
                sys.exit()

            if event.type == pygame_gui.UI_TEXT_ENTRY_CHANGED:
                Temp = event.text
            MANAGER.process_events(event)
        MANAGER.update(UI_REFRESH_RATE)
        MANAGER.draw_ui(SCREEN)
        pygame.display.update()

get_user_name()
```</div>

**Comment by MyreMylar** [comment]
Hmm, I can't reproduce this on latest main or on 0.6.9.

Possible it was inadvertently fixed recently? I will close for now because I can't reproduce.
