### ISSUE TITLE
Sound support?

### ISSUE THREAD

**Issue by MyreMylar** [MyreMylar/pygame_gui#58]
**Is your feature request related to a problem? Please describe.**
Currently Pygame GUI is silent like most GUIs. Does it need options to tie sounds to stuff or should it just let users do that themselves via events?

**Describe the solution you'd like**
Not sure, I don't use sound much in my education uses of the library because thirty machines making the same bloop bloop sounds will drive you insane.

**Describe alternatives you've considered**
Not doing anything with sounds.

**Comment by Snayff** [comment]
Providing the event that might cause a sound is more than enough. Saves bloating the library with other dependencies or code.
