### ISSUE TITLE
Button doesnt show propper text when disabled

### ISSUE THREAD

**Issue by rubenill79** [MyreMylar/pygame_gui#586]
**Describe the bug**
When the button is disabled and the text is changed it goes back to the first text it had

**To Reproduce**
Steps to reproduce the behaviour:
1.  Create a button
2. Use set_text to change the text on runtime
3. Disable the button

**Expected behaviour**

**Screenshots**

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version: latest
 - Pygame-ce version: latest

**Additional context**

**Comment by rubenill79** [comment]
I checked and if you rebuild it before disable it works properly but that shouldnt be how to do it

**Comment by MyreMylar** [comment]
This should be fixed now in main.
