### ISSUE TITLE
cannot import name 'DIRECTION_LTR'

### ISSUE THREAD

**Issue by Suspectxyzz** [MyreMylar/pygame_gui#587]
I have a problem with `pygame_gui', nothing works for me
What have I done 

windows 10 & 11 x64

1. reinstall windows(why not)
2. trying with many versions of python [ `3.11 / 3.12/ 3.13` ]
3. trying with many versions of `pygame_gui'
4. trying on 2 different pc ()
5. https://cdn.discordapp.com/attachments/335479269033639950/1237040864287522936/image.png?ex=663a3395&is=6638e215&hm=b009fd8ced9dbf9e8aa50db9e2caa5022d6672344b1028d18a5e2e962fb18ee4&
6. https://cdn.discordapp.com/attachments/335479269033639950/1237040909279825970/Screenshot_2024-05-06_165745.png?ex=663a339f&is=6638e21f&hm=8116b90ed3ac62701ef5324b60c3891223317b8b5de84f9aae3afdd32bd003b5&

**Comment by MyreMylar** [comment]
It looks like you have pygame and pygame-ce installed to the same version of python. Pygame-ce is a direct, improved replacement for pygame and they will conflict when importing. Just uninstall pygame and re-install pygame-ce and your problems should vanish.

**Comment by Suspectxyzz** [comment]
> It looks like you have pygame and pygame-ce installed to the same version of python. Pygame-ce is a direct, improved replacement for pygame and they will conflict when importing. Just uninstall pygame and re-install pygame-ce and your problems should vanish.

OK thanks for the advice but I need [is not a solution?]
pygame
pygame_gui

**Comment by theelgass** [comment]
I've same problem. Yesterday everything was fine. On old instalation (where i've installed package earlier) everything works. On new PC this error happens even while running basic code from docs.
