### ISSUE TITLE
.set_blocking() on UIWindow should block all input

### ISSUE THREAD

**Issue by scribblecrumb** [MyreMylar/pygame_gui#590]
**Is your feature request related to a problem? Please describe.**
Currently `set_blocking()` only blocks click inputs, it does not block other inputs, such as mouse hovering.  I'm currently having issues with the buttons below the window affecting the display of hover states on buttons within the window.

**Describe the solution you'd like**
It would be more intuitive for `set_blocking()` to block *all* input, rather than only clicks.  At the very least, an added parameter to specify that all input should be blocked would be appreciated, if for some reason there's need for click-only blocking.

**Describe alternatives you've considered**
For now I'll figure something out with layer heights, but it's not a preferred solution since the buttons below the window can be a varying number and would require me to use a ridiculously high layer height for the window to ensure no conflicts.

**Comment by MyreMylar** [comment]
Could you describe an example of this or post a code example?

In my example program a single window, newly opened with `.set_blocking()` will absorb all hovering events and MOUSEBUTTONDOWN events. I'm assuming you have some different circumstances like setting blocking on a window that is not currently at the top of the window stack perhaps?

If you could confirm that I'm not missing my guess entirely I could probably add a `self.window_stack.move_window_to_front(self)` call to the `set_blocking()` function to solve this.
