### ISSUE TITLE
"Cannot import DIRECTION_LTR from Pygame"

### ISSUE THREAD

**Issue by JoaquinDelaRosa** [MyreMylar/pygame_gui#598]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
Simply import pygame_gui

**Expected behaviour**
The import should be successful.

**Screenshots**
![image](https://github.com/MyreMylar/pygame_gui/assets/80933658/6dea74fa-b5c5-4eb4-9e8a-5a6541df3ced)

**Platform and software (please complete the following information):**
- OS: Windows
- Pygame GUI version 0.6.10
- Pygame version 2.5.2

**Comment by dylanxyz** [comment]
This happened to me too, i don't know exactly why but i think the last version of pygame is incompatible with pygame_gui. What worked for me was removing pygame and only installing pygame_gui, which will install the right version of pygame.

**Comment by MyreMylar** [comment]
Pygame GUI works only with the pygame-ce version of pygame - which is the most up to date version. This has allowed us to support features from SDL like Arabic and Hebrew languages which are not supported under the version just called 'pygame' on PyPI.

Unfortunately the 'pygame' PyPI package name/account is held by one individual who doesn't get on well with others. As a result  the rest of the pygame contributors have had to continue under the pygame-ce name. I consider pygame-ce to _be_ pygame at this point, it has gained many improvements and new features as it has continued to develop over the past year.
