### ISSUE TITLE
Odd line spacing behavior

### ISSUE THREAD

**Issue by scribblecrumb** [MyreMylar/pygame_gui#601]
**Describe the bug**
When the line spacing is higher than 1, some weirdness occurs.  As you can see in this screenshot, the 2nd and 3rd lines have a visibly smaller line spacing than the other lines (this is with the default line spacing).
![image](https://github.com/MyreMylar/pygame_gui/assets/115410010/2d148670-6318-4ccb-8dbb-bd6a613391d0)

This inconsistency is not longer present when I set the line spacing to 1.
![image](https://github.com/MyreMylar/pygame_gui/assets/115410010/c6e5cd5b-3257-49e2-be35-236032fddcbd)

Nor does it seem present in line spacings below 1 (this is .60)
![image](https://github.com/MyreMylar/pygame_gui/assets/115410010/7db55c19-1434-45b0-9b4d-c860371855b4)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a text box with enough text to extend for at least 3 lines
2. Ensure text themes are set up to produce the necessary line spacing

**Expected behaviour**
I would expect line spacing to be consistent throughout the paragraph.

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.11
 - Pygame-ce version 2.4.1

**Comment by MyreMylar** [comment]
Hmm, I'm not seeing this with the default font after trying several different line spacings greater than 1.

Any chance you can share more specifics of where it breaks down?

**Comment by scribblecrumb** [comment]
Well, that's mildly concerning for my code haha

I'm seeing it in both normal text boxes and tool tip textboxes.  It also seems to only be present in paragraphs. So, for example, if I were to manually add a line break instead of having it wrap the text, then there would be no line spacing issues.

I'm also using the Notosans font and font size seems to make no difference besides making the effect more or less pronounced (the effect is still there, though.)

I'll try and do a deeper dive into our code to see if I can pinpoint a cause within our own codebase instead of pygame_gui.  This all worked perfectly fine before the 0.6.11 update (excepting the bottom cutoff that i had reported and you fixed), so I'd been convinced there was something changed with that bugfix that had caused this new issue.

**Comment by Koriiy** [comment]
![image](https://github.com/MyreMylar/pygame_gui/assets/149183405/8d303c79-6ed2-4091-8a8e-5e94e66f472a)
![image](https://github.com/MyreMylar/pygame_gui/assets/149183405/c4887c8e-1575-476a-83b8-55e5480c1f6b)
Hi! I wanted to test to see if it was just the game or a possible issue with the newest update. I set line spacing to 1.5 for testing.
First image is on py gui 0.6.10, and second is after I updated to 0.6.11. These are screenshots of text boxes.
My project is rather simple and uses default font type and sizing. I only changed color and alignment aside from the spacing.

Further info:
OS: Linux
Pygame-ce: 2.4.1

**Comment by MyreMylar** [comment]
> Well, that's mildly concerning for my code haha
> 
> I'm seeing it in both normal text boxes and tool tip textboxes. It also seems to only be present in paragraphs. So, for example, if I were to manually add a line break instead of having it wrap the text, then there would be no line spacing issues.
> 
> I'm also using the Notosans font and font size seems to make no difference besides making the effect more or less pronounced (the effect is still there, though.)
> 
> I'll try and do a deeper dive into our code to see if I can pinpoint a cause within our own codebase instead of pygame_gui. This all worked perfectly fine before the 0.6.11 update (excepting the bottom cutoff that i had reported and you fixed), so I'd been convinced there was something changed with that bugfix that had caused this new issue.

It may be some kind of rounding issue with the specific line spacing/font height combo you are using that I am not hitting in my tests. If you could post any theme file details like:

```
"text_box":
    {
        "misc":
        {
            "border_width": "0",
            "shadow_width": "0",
            "line_spacing": "1.8"
        }
    }, 
``` 
That give you this problem that would be helpful!

**Comment by scribblecrumb** [comment]
Yeah for sure!  

```
    "tool_tip.text_box": {
        "colours": {
            "normal_border": "#2F2918",
            "normal_text": "#000000",
            "dark_bg": "#AC9D72"
        },
        "font": {
            "name": "notosans",
            "size": "13"
        },
        "misc": {
            "shape": "rounded_rectangle",
            "shape_corner_radius": "8",
            "border_width": "2",
            "shadow_width": "0",
            "text_horiz_alignment": "center"
        }
    },
```
    
```
    "#text_box": {
        "colours": {
            "dark_bg": "#FFFF0000",
            "normal_text": "#000000",
            "selected_bg": "#776045",
            "selected_text": "#AC9D72",
            "link_text": "#2E8B57",
            "link_hover": "#556B2F",
            "link_selected": "#556B2F"
        },
        "font": {
            "name": "notosans",
            "size": "15"
        },
        "misc": {
            "border_width": "0",
            "shadow_width": "0"
        }
    },
```

And if it's helpful info, we do have a lot of prototyped text themes as well, though prototype or no prototype doesn't seem to make any discernible difference with this bug.

```

    "#text_box_22": {
        "prototype": "#text_box",
        "font": {
            "name": "notosans",
            "size": "11"
        }
    },
    "#text_box_22_horizcenter": {
        "prototype": "#text_box_22",
        "misc": {
            "text_horiz_alignment": "center"
        }
    },
    "#text_box_22_horizcenter_red": {
        "prototype": "#text_box_22_horizcenter",
        "colours": {
            "normal_text": "#ae1515"
        }
    },
    "#text_box_22_horizcenter_spacing_95": {
        "prototype": "#text_box_22_horizcenter",
        "misc": {
            "line_spacing": "0.95"
        }
    },
```

**Comment by MyreMylar** [comment]
OK, these should be solved in the latest version.

Let me know if you have any more issues.
