### ISSUE TITLE
UI Slider Arrow Button Size Adjustment

### ISSUE THREAD

**Issue by samin50** [MyreMylar/pygame_gui#605]
Is there a way to increase the size of the of the arrow buttons for the sliders (horizontal and vertical) without just increasing the height or width of the entire slider? It was probably done like this so the arrow buttons remain square or circular, but that means thin sliders have tiny buttons.

Is this possible?

**Comment by MyreMylar** [comment]
You can change the font size via theming:

```
"horizontal_scroll_bar.@arrow_button": 
{
    "font":
    {
        "size": 32
    }
}
```

Though from my testing this doesn't work spectacularly well with very small sliders as the font line spacing gradually slides the actual text off the screen and padding makes the usable area even smaller. I think you'd be better with setting actual images (again via theming) for the arrows for very small sliders/scrollbars:

```
"horizontal_scroll_bar.#left_button": 
{
    "images":
    {
        "normal_image": {
            "package": "data.images",
            "resource": "small_left_arrow.png"
        }
    }
}
```

I've added a PR here: #652 
to make it easier to disable the text based arrows on a scrollbar or slider buttons (or set them to some other character).
