### ISSUE TITLE
Hover over element focuses the element (for mouse wheel scroll)

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#61]
**Is your feature request related to a problem? Please describe.**
The need to click an element already hovered in order to set the selection.

**Describe the solution you'd like**
When the mouse is over an element, have that element be selected. 

**Additional context**
Whilst it is inconsistent a lot of modern applications are using that approach, meaning you can mouse over different elements and scroll without having to click each time.

**Comment by MyreMylar** [comment]
**Just leaving a note for myself here:** 
With the new (still-pondering-implications-of) split between 'selecting stuff' and 'focusing stuff' this idea likely falls under 'focusing stuff'
