### ISSUE TITLE
GUIopedia links bug out when you scroll before clicking

### ISSUE THREAD

**Issue by NFB418** [MyreMylar/pygame_gui#614]
**Describe the bug**
This is based on the guiopedia example found in the pygame_gui_examples repository here: https://github.com/MyreMylar/pygame_gui_examples/blob/master/guiopedia.py

When you start on a page with a reference link. If the page has enough text that you need to scroll down first before you can click the link, clicking that link will not take you to the linked page but instead to the top of the page you are on. Subsequent scrolling and clicking does take you to the reference page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the pygame_gui_examples repository.
2. Change the index.html file to the following, which is simply adding enough break statements to push the reference links low enough to requiring scrolling to click:

```
<font size="6"><b>Welcome to GUI-opedia!</b></font>
<br><br>
This is a little test of creating a few hyperlink connected pages that we can display to
the user to give them more information. Maybe it'll have a search bar as well? Oh, hey now it does.
<br><br>
The point is we have multiple pages of text that we load in from files, and then we can navigate between them via links
all inside of a window. Here are a few of them to try clicking on:
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
 - <a href="cats">Cats</a> - A page all about cats.<br>
 - <a href="gravel">Gravel</a> - Gravel: What is the deal.<br>
```

3. Scroll down and attempt to click the links to either Cats or Gravel. You will be taken to the top of the index page first. Scrolling again and clicking again does take you to the referenced page.

**Expected behaviour**
Scrolling should not affect behavior when links are clicked.

**Screenshots**
![guiopedia bug report](https://github.com/MyreMylar/pygame_gui/assets/85886026/5535f5c7-1aa6-4c58-8109-27333b0546bd)

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version 0.6.12
 - Pygame version 2.5.0

**Additional context**
I was planning to make pretty extensive use of the Guiopedia feature for my project, so this is a bit of a bummer. It is probably above my skill to bug fix, so any help would be greatly appreciated!!! :)

**Comment by MyreMylar** [comment]
Thanks for the report, I can reproduce this and will have a go at tracking down a fix.
