### ISSUE TITLE
Pygame_GUI 0.6.12 is incompatable with Pygame 2.6.0

### ISSUE THREAD

**Issue by JosephHabisohn** [MyreMylar/pygame_gui#625]
**Describe the bug**
Importing pygame_gui 0.6.12 with pygame 2.6.0 completely breaks. An import error gets thrown: "cannot import name 'DIRECTION_LTR' from 'pygame'" on "import pygame_gui" (see screenshot)

**To Reproduce**
1. Install both pygame 2.6.0 and pygame_gui 0.6.12

**Expected behavior**
The exception shown below to not occur.

**Screenshots**
![image](https://github.com/user-attachments/assets/c5bab20e-a7fb-4a89-ab70-c69b94c8d86b)

**Platform and software (please complete the following information):**
 - OS: Windows 10
 - Pygame GUI version: 0.6.12
 - Pygame version: 2.6.0
 - Pygame-ce version: 2.5.0

**Additional context**
I am not using a venv and all packages are in the global scope. However, neither of these have posed any issue since I started developing with pygame and pygame_gui. I'm not sure if that is a huge problem or not, it honestly could be, I wouldn't know. 
Also, I upgraded from pygame 2.5.2 (everything did work normally in this version). In other words the last know working versions are:

 - Pygame GUI version: 0.6.12
 - Pygame version: 2.5.2
 - Pygame-ce: 2.4.0

**Comment by joereynolds** [comment]
Sorry to tack on but this is also happening with me

Pygame GUI version: 0.6.10
Python: 3.12
Pygame-ce: 2.5

**Comment by MyreMylar** [comment]
This happens when you have old pygame installed. You only want a recent
version of pygame-ce in your environment. Only pygame-ce supports the
latest features of SDL that enables stuff like Arabic language text. Just
make sure to uninstall pygame and then reinstall pygame-ce and you should
be fine.

**Comment by aelydam** [comment]
Sorry I can't help you, but I'm curious. Is there a reason you have both pygame and pygame-ce?
