### ISSUE TITLE
UIForm UISelectionList bug - Items do not fully display

### ISSUE THREAD

**Issue by JosephHabisohn** [MyreMylar/pygame_gui#626]
**Describe the bug**
When a UISelectionList is used as an element of a UIForm, only the first 2 items of the UISelectionList actually display within the form. The bounding box of the UISelectionList is the proper size, but the buttons themselves don't seem to exist.

**To Reproduce**
Steps to reproduce the behavior (full code at the bottom. I'm not entirely sure what the "steps" for this case would be, so I just added the code):
```
form = pygame_gui.elements.UIForm(
    relative_rect=pygame.Rect((5, 5), (790, 590)),
    questionnaire={
        "selection": UISelectionList(item_list=["1", "2", "3", "4"], relative_rect=pygame.Rect((0, 0), (770, 570)), manager=manager)
    },
    manager=manager
)
```

**Expected behavior**
The full UISelectionList gets displayed, where all items in the UISelectionList are displayed with the within the UIForm

**Screenshots**
![image](https://github.com/user-attachments/assets/4d392683-b8db-4fe2-87ca-15543e8b3890)

**Platform and software (please complete the following information):**
 - OS: Win10
 - pygame GUI version: 0.6.12
 - pygame-ce version: 2.5.0
 - python 3.12.3

**Additional context**
Here is the full test code I was using:
```
import pygame
import pygame_gui
from pygame_gui.elements import UISelectionList

# Initialize pygame
pygame.init()

# Set up the screen
pygame.display.set_caption('UI Form Test')
window_size = (800, 600)
screen = pygame.display.set_mode(window_size)

# Set up the GUI manager
manager = pygame_gui.UIManager(window_size)

# Create UI elements
# list = UISelectionList(item_list=["1", "2", "3", "4"], relative_rect=pygame.Rect((0, 0), (770, 570)), manager=manager)
form = pygame_gui.elements.UIForm(
    relative_rect=pygame.Rect((5, 5), (790, 590)),
    questionnaire={
        "selection": UISelectionList(item_list=["1", "2", "3", "4"], relative_rect=pygame.Rect((0, 0), (770, 570)), manager=manager)
    },
    manager=manager
)

clock = pygame.time.Clock()
is_running = True

# Main loop
while is_running:
    time_delta = clock.tick(60) / 1000.0

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            is_running = False

        manager.process_events(event)

        if event.type == pygame_gui.UI_BUTTON_PRESSED:
            pass

    manager.update(time_delta)

    screen.fill((0, 0, 0))
    manager.draw_ui(screen)

    pygame.display.update()

pygame.quit()
```

**Comment by Manuellama** [comment]
Add the UISelectionList data to the UIForm after you have created the UIForm. 

form = pygame_gui.elements.UIForm(
    relative_rect=pygame.Rect((5, 5), (790, 590)),
    manager=manager
)
selection_list = pygame_gui.elements.UISelectionList(
    item_list=["1", "2", "3", "4"],
    relative_rect=pygame.Rect((10, 10), (760, 550)),
    manager=manager
)

# Add the UISelectionList to the form's questionnaire
form.questionnaire["selection"] = selection_list

![image](https://github.com/user-attachments/assets/ffb282d9-16c9-42c5-8a3d-5b45b7b14d41)

**Comment by JosephHabisohn** [comment]
That's a fair point. Thanks.
