### ISSUE TITLE
Content of all tabs of a UITabContainer become visible when showing the UIWindow that contains UITabContainer

### ISSUE THREAD

**Issue by aelydam** [MyreMylar/pygame_gui#628]
**Describe the bug**
When you call "show" on a UIWindow containing a UITabContainer, the contents of all tabs become visible.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the reproducible example below
2. Close the UIWindow object
3. Click the UIButton object to show the window again

**Expected behaviour**
I expected that only the content of the last selected tab to become visible.

**Screenshots**

**Platform and software (please complete the following information):**
 - OS: Ubuntu 24.04 LTS, Linux Kernel 6.8.0-40-generic x86_64
 - Pygame GUI version: pygame_gui        0.6.12
 - Pygame version: pygame-ce         2.5.0

Reproducible example:
```python
import pygame as pg
import pygame_gui as pgg

SHAPE = (800, 600)
pg.init()
pg.display.set_caption('Quick Start')
clock = pg.time.Clock()
manager = pgg.UIManager(SHAPE)
window_surface = pg.display.set_mode(SHAPE)
background = pg.Surface(SHAPE)
background.fill(pg.Color('#000000'))

class MyWindow(pgg.elements.UIWindow):
    def on_close_window_button_pressed(self):
        self.hide()

btn = pgg.elements.UIButton(pg.Rect(32, 32, 120, 24), 'Show window')
win = MyWindow(pg.Rect(32, 64, 320, 480), manager, 'Janela')
tabs = pgg.elements.UITabContainer(pg.Rect(0, 0, 320, 480), manager, win)
for i in range(4):
    tab = tabs.add_tab(f"Tab{i}", f"tab{i}")
    lab = pgg.elements.UILabel(
        pg.Rect(16, 16+24*i, 120, 32), f"Label for Tab {i}",
        manager, tabs.get_tab_container(tab))

is_running = True
while is_running:
    time_delta = clock.tick(60)/1000.0
    for event in pg.event.get():
        if event.type == pg.QUIT:
            is_running = False
            break
        if event.type == pgg.UI_BUTTON_PRESSED:
            win.show()
        manager.process_events(event)
    manager.update(time_delta)
    window_surface.blit(background, (0, 0))
    manager.draw_ui(window_surface)
    pg.display.flip()
pg.quit()
```

**Comment by Manuellama** [comment]
### From the source code, in _elements/ui_window.py_

 def show(self):
        """
        In addition to the base UIElement.show() - show the _window_root_container which will
        propagate and show all the children.
        """
        super().show()
        if self._window_root_container is not None:
            self._window_root_container.show()

The function show() you are calling from the UIWindow class describes in the function commentary that this function will show all the children from that container. Practically, it does what it says it does, so another function should be created for these cases.

**Comment by Manuellama** [comment]
Possible solution.
Kill the window and recreate it again.

import pygame as pg
import pygame_gui as pgg

SHAPE = (800, 600)
pg.init()
pg.display.set_caption('Quick Start')
clock = pg.time.Clock()
manager = pgg.UIManager(SHAPE)
window_surface = pg.display.set_mode(SHAPE)
background = pg.Surface(SHAPE)
background.fill(pg.Color('#000000'))

class MyWindow(pgg.elements.UIWindow):
    def on_close_window_button_pressed(self):
        self.hide()

btn = pgg.elements.UIButton(pg.Rect(32, 32, 120, 24), 'Show window')
win = MyWindow(pg.Rect(32, 64, 320, 480), manager, 'Janela')
tabs = pgg.elements.UITabContainer(pg.Rect(0, 0, 320, 480), manager, win)
for i in range(4):
    tab = tabs.add_tab(f"Tab{i}", f"tab{i}")
    lab = pgg.elements.UILabel(
        pg.Rect(16, 16+24*i, 120, 32), f"Label for Tab {i}",
        manager, tabs.get_tab_container(tab))

is_running = True
while is_running:
    time_delta = clock.tick(60)/1000.0
    for event in pg.event.get():
        if event.type == pg.QUIT:
            
            is_running = False
            break
        if event.type == pgg.UI_BUTTON_PRESSED:
            #check that we clicked the right button
            if event.ui_element == btn:
                #destroy the window
                win.kill()
                #recreate it again
                win = MyWindow(pg.Rect(32, 64, 320, 480), manager, 'Janela')
                tabs = pgg.elements.UITabContainer(pg.Rect(0, 0, 320, 480), manager, win)
                for i in range(4):
                    tab = tabs.add_tab(f"Tab{i}", f"tab{i}")
                    lab = pgg.elements.UILabel(
                        pg.Rect(16, 16+24*i, 120, 32), f"Label for Tab {i}",
                        manager, tabs.get_tab_container(tab))

        manager.process_events(event)
    manager.update(time_delta)
    window_surface.blit(background, (0, 0))
    manager.draw_ui(window_surface)
    pg.display.flip()
pg.quit()
