### ISSUE TITLE
hide() has no effect on UIButton if the button's container is currently hidden

### ISSUE THREAD

**Issue by MrAnthrope** [MyreMylar/pygame_gui#631]
**Describe the bug**
I have a UIPanel that is serving as the container for a number of UIButton's.  show() and hide() are used to make the panel visible or not visible at various points in the game.  Before making the panel visible by calling show() against it, my code determines which buttons on the panel should be visible and which should be invisible.  If a button that was previously visible on the panel should be invisible when the panel is next shown, the code calls hide() against the button. Eventually the code calls show() against the panel to make the panel visible again. The button against which hide() was called is NOT hidden when the button becomes visible.

Note:  If I reverse the order of the steps, calling show against the UIPanel and then calling hide() against the UIButton, the button is correctly hidden.  But calling hide() against the UIButton while the UIPanel is itself hidden seems to have no effect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a UIPanel
2. Create a UIButton setting the UIPanel as the button's container
3. Call hide() against the UIPanel
4. Call hide() against the UIButton
5. Call show() against the UIPanel
6. Observe that the button is NOT hidden despite the fact that hide() was called against it.

**Expected behaviour**
If hide() is called against a widget, the widget should remain hidden, regardless of changes to the visibility of the widget's container.  This should be true whether the container itself was visible or invisible when hide() was called against the widget.

**Platform and software (please complete the following information):**
 - OS: Mac (macOS Ventura 13.5.2)
 - Pygame GUI version 0.6.12
 - Pygame version: pygame-ce 2.5.1

**Comment by MyreMylar** [comment]
This is actually how the person who designed the show/hide system designed it to work. Calling show and hide on any container like element (e.g. a window or a panel) recursively calls show on all of its contents. I can see arguments for it working as it does as it makes it a lot simpler to hide a panel and it's contents with one call.  You can also work around the current behaviour by reversing the order of your calls unhiding the panel and then hiding the subparts you want to keep hidden.

Given this behaviour has been out there for a while now I think we'd have to manage this as a feature request by adding a parameter to container type hide & show methods that allows you to disable the child hiding/showing should you desire.
