### ISSUE TITLE
Passing coordinate-like to UILabel results in crash.

### ISSUE THREAD

**Issue by gbbofh** [MyreMylar/pygame_gui#657]
**Description**
Passing a Coordinate-like to `UILabel.__init__` results in an exception.

**To Reproduce**
Steps to reproduce the behaviour:
1. `my_label = pygame_gui.elements.UILabel((5,10), 'Example')`
2. Observe that this generates an exception on `ui_label.py:67`

**Expected behaviour**
A label should be created, as the parameter `relative_rect` is permitted to be either a `Rect`-like, or `Coordinate`-like.

**Platform and software (please complete the following information):**
 - OS: Windows, WSL v2 running Ubuntu
 - Pygame GUI version: pygame-gui-0.6.12
 - Pygame version: pygame-ce 2.5.2 (SDL 2.30.8, Python 3.8.10)

**Additional context**
I have already submitted a PR to fix this issue.

**Comment by MyreMylar** [comment]
Thanks for the fix!
