### ISSUE TITLE
changing colors

### ISSUE THREAD

**Issue by spookyv3030** [MyreMylar/pygame_gui#658]
hi! so i've trying to change colors in midi playground game square bounce and nothing is working I change code .py doesn't work so how do I change color and background and glowing effect etc - i saw videos on tiktok ![image](https://github.com/user-attachments/assets/9b73c4ca-6625-4cf2-ac70-bd7cfb626986)

pls help thank you

**Comment by spookyv3030** [comment]
> I've done this in the past by using `update_theming`.
> 
> 
> 
> Here's an example of updating some colours on the fly
> 
> 
> 
> ```
> 
> self.text_box.update_theming(
> 
>     {
> 
>         "colours": {"normal_border": portrait_map[self.portrait]['colour']}
> 
>     }
> 
> )
> 
> ```
> 
> 
> 
> 

heyy! Can u tell me which files to edit this ? And chat gpt well do the rest

**Comment by joereynolds** [comment]
It's whatever element you want to change. So if you have a variable called `button` that is referencing some element from pygame_gui, you'd call `button.update_theming`

**Comment by spookyv3030** [comment]
> It's whatever element you want to change. So if you have a variable called `button` that is referencing some element from pygame_gui, you'd call `button.update_theming`

I don't have pygame_gui zip files or something this is  my account on tiktok @isaac24yt pls text me there i just need to change colors and square

**Comment by MyreMylar** [comment]
Having investigated this I think this isn't really a question about pygame_gui. The repository for the Square Bounce app that went viral on TikTok is over here:

[https://github.com/quasar098/midi-playground](https://github.com/quasar098/midi-playground)

It _uses_ Pygame GUI to make it's settings menu but the whole application is a lot more complicated, and pretty cool!

I also noticed two popular videos on using the app here: https://www.youtube.com/watch?v=6XYPlVyLWfQ and here: https://www.youtube.com/watch?v=ALfkcAvf7t4 which may help you out @spookyv3030
