### ISSUE TITLE
Black radius artifacts on rounded rect

### ISSUE THREAD

**Issue by hugonun** [MyreMylar/pygame_gui#659]
**Describe the bug**
Rounded rectangle shows black artifacts where there is a radius. There are 4 outer radius artifacts, and 2 inner radius artifacts on the bottom.

**To Reproduce**
Steps to reproduce the behaviour:
1. Draw rounded rect
2. Change border color to a lighter color to make it more noticable
3. Remove shadow

**Expected behaviour**
No artifacts, solid color.

**Screenshots**
![image](https://github.com/user-attachments/assets/08a829c7-b12f-497c-9fab-a6e95aebdad3)

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version: Latest (0.6.12)
 - Pygame version: pygame-ce 2.5.2

**Additional context**
This is an issue with pygame-gui's method of replacing the color of the rectangles. Unsure if this is a new bug or if it has always been there.

**Comment by hugonun** [comment]
Changing anti-aliasing seems to reduce artifacts, but couldn't figure out the right formula.

**Comment by hugonun** [comment]
For future readers: Special flag `pygame.BLEND_PREMULTIPLIED` is required when blitting the GUI onto a surface and then the display. 

The artefacts appear because of parts of the code using `smoothscale()`, whereas the flag `pygame.BLEND_PREMULTIPLIED` becomes a requirement when dealing with roundness on transparency.

Inner border artefacts seem to be gone with border_overlap's new default value being 1.

**Comment by MyreMylar** [comment]
I should probably add a note to the Pygame GUI draw_ui function documentation somewhere about Pygame GUI using premultiplied alpha in it's drawing which makes no difference in most cases - but it does make a difference if you draw the GUI onto a transparent or semi-transparent surface and then blit that surface onto an opaque surface without setting the BLEND_PREMULTIPLED blit flag.

The wrong looking corners, or some poorly anti-aliased text are classic examples of artefacting you might see when using the straight alpha blitting formula with some pre-multiplied alpha data. 

You can read more about the visual & performances advantages of pre-multiplied alpha blending in this tutorial I wrote here:

[https://pyga.me/docs/tutorials/en/premultiplied-alpha.html](https://pyga.me/docs/tutorials/en/premultiplied-alpha.html)
