### ISSUE TITLE
Drop Down Menu Selection Event

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#66]
**Is your feature request related to a problem? Please describe.**
Need to constantly be checking to see if the value in a drop down menu has changed.

**Describe the solution you'd like**
Raise an event when the new value in the drop down is selected.

**Comment by MyreMylar** [comment]
There is an event for this already - 'pygame_gui.UI_DROP_DOWN_MENU_CHANGED', See the docs here:

https://pygame-gui.readthedocs.io/en/latest/events.html

Unless I'm misunderstanding your report?

**Comment by Snayff** [comment]
Yep, that's exactly it! Sorry mate - and thank you.
