### ISSUE TITLE
Active colours don't work

### ISSUE THREAD

**Issue by VitoR-InA** [MyreMylar/pygame_gui#661]
The active_bg, active_text, active_border settings make the corresponding part of the button black.

![theme.json](https://github.com/user-attachments/assets/e29cb019-941e-49c2-8e0c-e8cde9c22207)

https://github.com/user-attachments/assets/480efc31-02f5-402a-9586-c53635807c88

 - OS: Windows 11
 - Pygame GUI version 0.6.12
 - Pygame version 2.5.2

**Comment by MyreMylar** [comment]
Looks like you are missing a # at the start of those colours.

**Comment by VitoR-InA** [comment]
My bad
