### ISSUE TITLE
Dropdown not updating selection

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#72]
**Describe the bug**
When selecting an item in the drop down the selected item is shown in the box, however the information is not updated (i.e. dropdown.selected_option doesn't show the new data)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create dropdown
2. Click down arrow of dropdown
3. Select option
4. Inspect object

**Expected behaviour**
Select an option and have the selected option updated. 

**Screenshots**
Initial load: https://imgur.com/VskdJAA
Changed terrain collision: https://i.imgur.com/fwnE5Wc.png
Inspecting item in code: https://i.imgur.com/bCNe3n2.png 

**Platform and software (please complete the following information):**
 - OS: Windows 10 64bit
 - Pygame GUI version 0.4.0
 - Pygame version 2.0.0.6dev

**Additional context**
May be related, but the UITextEntryLine widgets aren't responding to clicks or mouse over.

Gist: https://gist.github.com/Snayff/544e478932cc06e6e9c406f4b424bee8#file-skill_editor-py-L128

**Comment by MyreMylar** [comment]
Is that last screenshot the right one? It appears to show selected_option changed to 'FIZZLE' when your report said that wasn't happening.

Regardless I'll look into it.

**Comment by Snayff** [comment]
Initial value was Fizzle, then changed to Activate. But the variable hasn't changed.
