### ISSUE TITLE
UILabel cannot use font in theme when container is set to a UIWindow

### ISSUE THREAD

**Issue by zhuoyizhang** [MyreMylar/pygame_gui#74]
**Describe the bug**
UILabel cannot use font in theme when container is set to a UIWindow

UI_mannager loads a font from theme, and it works well when container=None in a UILabel.
But when I create a UIWindow and add the UILabel into it, the font was not used correctly while using the same UI_manager.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Run the attached the code
2. Click on the button
3. See the missing font in the title of the popup window

**Expected behaviour**
The same font should be used, hence the text should be displayed correctly in the window.
**Screenshots**

The text on the button is correct
![image](https://user-images.githubusercontent.com/11303950/74614358-1be89800-50cc-11ea-9b8b-82c167d053c5.png)

The text font is not correct in the window
![image](https://user-images.githubusercontent.com/11303950/74614348-0c694f00-50cc-11ea-9411-1271392cd637.png)

**Platform and software (please complete the following information):**
OS: mac 64bit
Pygame GUI version 0.4.2
Pygame version 2.0.0.6dev

**Additional context**

The screenshot of the theme file.  
```
        self.ui_manager = pygame_gui.UIManager((400, 300), 'card/button.json')
```
![image](https://user-images.githubusercontent.com/11303950/74614487-27888e80-50cd-11ea-8d7d-c6a7c175d9b1.png)

**Comment by zhuoyizhang** [comment]
`import pygame_gui
import pygame

from pygame_gui.core.ui_window import UIWindow

from pygame_gui.elements.ui_button import UIButton


class EverythingWindow(UIWindow):
    def __init__(self, rect, ui_manager, name):

        element_ids = [name]

        super().__init__(rect, ui_manager, element_ids=element_ids)

        # create shadow
        shadow_padding = (2, 2)

        self.image = self.ui_manager.get_shadow(self.rect.size)
        self.image.fill(self.ui_manager.get_theme().get_colour(self.object_ids, self.element_ids, 'dark_bg'),
                        pygame.Rect(shadow_padding,
                                    (self.rect.width - shadow_padding[0] * 2,
                                     self.rect.height - shadow_padding[1] * 2)
                                    ))

        self.get_container().relative_rect.width = self.rect.width - shadow_padding[0] * 2
        self.get_container().relative_rect.height = self.rect.height - shadow_padding[1] * 2
        self.get_container().relative_rect.x = self.get_container().relative_rect.x + shadow_padding[0]
        self.get_container().relative_rect.y = self.get_container().relative_rect.y + shadow_padding[1]
        self.get_container().update_containing_rect_position()

        self.close_window_button = UIButton(relative_rect=pygame.Rect((self.get_container().rect.width - 20, 0),
                                                                      (20, 20)),
                                            text='╳',
                                            manager=ui_manager,
                                            container=self.get_container(),
                                            parent_element=self
                                            )
        self.menu_bar = UIButton(relative_rect=pygame.Rect((0, 0),
                                                           (self.get_container().rect.width - 20, 20)),
                                 text=name,
                                 manager=ui_manager,
                                 container=self.get_container(),
                                 parent_element=self,
                                 object_id='#message_window_title_bar'
                                 )
        self.menu_bar.set_hold_range((100, 100))

        self.grabbed_window = False
        self.starting_grab_difference = (0, 0)

        self.is_selected = False

    def select(self):
        self.is_selected = True

    def unselect(self):
        self.is_selected = False

    def process_event(self, event):
        processed_event = False
        if self.is_selected:
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_p:
                    self.test_slider.set_current_value(50)

        if event.type == pygame.MOUSEBUTTONDOWN:
            if event.button == 1:
                mouse_x, mouse_y = event.pos
                if self.rect.collidepoint(mouse_x, mouse_y):
                    processed_event = True
                    self.window_stack.move_window_to_front(self)

        return processed_event

    def update(self, time_delta):
        pass


class Options:
    def __init__(self):
        self.resolution = (800, 600)
        self.fullscreen = False


class OptionsUIApp:
    def __init__(self):
        pygame.init()
        pygame.display.set_caption("Options UI")
        self.options = Options()
        if self.options.fullscreen:
            self.window_surface = pygame.display.set_mode(self.options.resolution, pygame.FULLSCREEN)
        else:
            self.window_surface = pygame.display.set_mode(self.options.resolution)

        self.background_surface = None

        self.ui_manager = pygame_gui.UIManager((800, 600), 'card/button.json')
        self.ui_manager.preload_fonts([{'name': 'fira_code', 'point_size': 10, 'style': 'bold'},
                                       {'name': 'fira_code', 'point_size': 10, 'style': 'regular'},
                                       {'name': 'fira_code', 'point_size': 10, 'style': 'italic'},
                                       {'name': 'fira_code', 'point_size': 14, 'style': 'italic'},
                                       {'name': 'fira_code', 'point_size': 14, 'style': 'bold'}
                                       ])

        self.test_slider = None
        self.test_text_entry = None
        self.test_drop_down_menu = None
        self.recreate_ui()

        self.clock = pygame.time.Clock()

        self.button_response_timer = pygame.time.Clock()
        self.running = True

    def recreate_ui(self):
        self.ui_manager.set_window_resolution(self.options.resolution)
        self.ui_manager.clear_and_reset()

        self.background_surface = pygame.Surface(self.options.resolution)
        self.background_surface.fill(self.ui_manager.get_theme().get_colour(None, None, 'dark_bg'))

        self.test_button_1 = UIButton(pygame.Rect((int(self.options.resolution[0] / 3),
                                                   int(self.options.resolution[1] * 0.90)),
                                                  (100, 40)),
                                      '字体',
                                      self.ui_manager,
                                      object_id='#everything_button')

    def process_events(self):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                self.running = False

            self.ui_manager.process_events(event)

            if event.type == pygame.USEREVENT:
                if event.user_type == 'ui_text_entry_finished':
                    if event.ui_object_id == '#main_text_entry':
                        print(event.text)

                if event.user_type == 'ui_text_box_link_clicked':
                    if event.link_target == 'test':
                        print("clicked test link")
                    elif event.link_target == 'actually_link':
                        print("clicked actually link")

                if event.user_type == 'ui_button_pressed':

                    if event.ui_element == self.test_button_1:
                        EverythingWindow(pygame.Rect((10, 10), (640, 480)), self.ui_manager, '测试字体')

    def run(self):
        while self.running:
            time_delta = self.clock.tick(60) / 1000.0

            # check for input
            self.process_events()

            # respond to input
            self.ui_manager.update(time_delta)

            # draw graphics
            self.window_surface.blit(self.background_surface, (0, 0))
            self.ui_manager.draw_ui(self.window_surface)

            # self.window_surface.blit(self.ui_manager.ui_theme.shape_cache.cache_surfaces[0], (0, 0))

            pygame.display.update()


if __name__ == '__main__':
    app = OptionsUIApp()
    app.run()
`

**Comment by zhuoyizhang** [comment]
```
import pygame_gui
import pygame

from pygame_gui.core.ui_window import UIWindow

from pygame_gui.elements.ui_button import UIButton


class EverythingWindow(UIWindow):
    def __init__(self, rect, ui_manager, name):

        element_ids = [name]

        super().__init__(rect, ui_manager, element_ids=element_ids)

        # create shadow
        shadow_padding = (2, 2)

        self.image = self.ui_manager.get_shadow(self.rect.size)
        self.image.fill(self.ui_manager.get_theme().get_colour(self.object_ids, self.element_ids, 'dark_bg'),
                        pygame.Rect(shadow_padding,
                                    (self.rect.width - shadow_padding[0] * 2,
                                     self.rect.height - shadow_padding[1] * 2)
                                    ))

        self.get_container().relative_rect.width = self.rect.width - shadow_padding[0] * 2
        self.get_container().relative_rect.height = self.rect.height - shadow_padding[1] * 2
        self.get_container().relative_rect.x = self.get_container().relative_rect.x + shadow_padding[0]
        self.get_container().relative_rect.y = self.get_container().relative_rect.y + shadow_padding[1]
        self.get_container().update_containing_rect_position()

        self.close_window_button = UIButton(relative_rect=pygame.Rect((self.get_container().rect.width - 20, 0),
                                                                      (20, 20)),
                                            text='╳',
                                            manager=ui_manager,
                                            container=self.get_container(),
                                            parent_element=self
                                            )
        self.menu_bar = UIButton(relative_rect=pygame.Rect((0, 0),
                                                           (self.get_container().rect.width - 20, 20)),
                                 text='测试字体， test font',
                                 manager=ui_manager,
                                 container=self.get_container(),
                                 parent_element=self,
                                 object_id='#message_window_title_bar'
                                 )
        self.menu_bar.set_hold_range((100, 100))

        self.grabbed_window = False
        self.starting_grab_difference = (0, 0)

        self.is_selected = False

    def select(self):
        self.is_selected = True

    def unselect(self):
        self.is_selected = False

    def process_event(self, event):
        processed_event = False
        if self.is_selected:
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_p:
                    self.test_slider.set_current_value(50)

        if event.type == pygame.MOUSEBUTTONDOWN:
            if event.button == 1:
                mouse_x, mouse_y = event.pos
                if self.rect.collidepoint(mouse_x, mouse_y):
                    processed_event = True
                    self.window_stack.move_window_to_front(self)

        return processed_event

    def update(self, time_delta):
        pass


class Options:
    def __init__(self):
        self.resolution = (400, 300)
        self.fullscreen = False


class OptionsUIApp:
    def __init__(self):
        pygame.init()
        pygame.display.set_caption("Options UI")
        self.options = Options()
        if self.options.fullscreen:
            self.window_surface = pygame.display.set_mode(self.options.resolution, pygame.FULLSCREEN)
        else:
            self.window_surface = pygame.display.set_mode(self.options.resolution)

        self.background_surface = None

        self.ui_manager = pygame_gui.UIManager((400, 300), 'card/button.json')

        self.recreate_ui()

        self.clock = pygame.time.Clock()

        self.button_response_timer = pygame.time.Clock()
        self.running = True

    def recreate_ui(self):
        self.ui_manager.set_window_resolution(self.options.resolution)
        self.ui_manager.clear_and_reset()

        self.background_surface = pygame.Surface(self.options.resolution)
        self.background_surface.fill(self.ui_manager.get_theme().get_colour(None, None, 'dark_bg'))

        self.test_button_1 = UIButton(pygame.Rect((int(self.options.resolution[0] / 3),
                                                   int(self.options.resolution[1] * 0.70)),
                                                  (100, 40)),
                                      '字体',
                                      self.ui_manager,
                                      object_id='#everything_button')

    def process_events(self):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                self.running = False

            self.ui_manager.process_events(event)

            if event.type == pygame.USEREVENT:

                if event.user_type == 'ui_button_pressed':

                    if event.ui_element == self.test_button_1:
                        EverythingWindow(pygame.Rect((10, 10), (400, 300)), self.ui_manager, '测试字体')

    def run(self):
        while self.running:
            time_delta = self.clock.tick(60) / 1000.0

            # check for input
            self.process_events()

            # respond to input
            self.ui_manager.update(time_delta)

            # draw graphics
            self.window_surface.blit(self.background_surface, (0, 0))
            self.ui_manager.draw_ui(self.window_surface)

            # self.window_surface.blit(self.ui_manager.ui_theme.shape_cache.cache_surfaces[0], (0, 0))

            pygame.display.update()


if __name__ == '__main__':
    app = OptionsUIApp()
    app.run()

```

**Comment by zhuoyizhang** [comment]
I found the issue in my code.
If I comment the parent_element, the font is loaded correctly.
I don't know the reason why parent_element is not working, but it works for me now.
I would love to hear your feedback on whether this is an issue or not.  
It is working for me now.
```
            pygame_gui.elements.ui_label.UILabel(pygame.Rect((300, 30 + i * 30), (220, 30)),
                                                 text=skill.get_detail_text(),
                                                 manager=ui_manager,
                                                 container=window.get_container(),
                                                 #parent_element=window,
                                                 object_id='#shortkey_button')
```

**Comment by MyreMylar** [comment]
Two things.

1. If you want to change the text on the buttons, only in the window use:
```
{
    "测试字体.Button":
    {
         "colours":
         {
             ...
         }
        "font":
        {
            ...     
        }
        ...
    }
```

2. Make sure you put the font block of the theme file in with the button part. In this library a button and a label are two different things rather than two parts of the same thing. With the main difference between them being that the buttons are interactive.

Apologies, for my inability to write Chinese to explain more clearly.
