### ISSUE TITLE
Text box not scrolling to bottom consistently

### ISSUE THREAD

**Issue by tylersutton** [MyreMylar/pygame_gui#78]
**Describe the bug**
The text box scrolls by an inconsistent amount when new lines of text are added

**Expected behaviour**
Expected the text box's scroll_bar to scroll down such that every new line of text appeared at the same height in the text box.

**Screenshots**
![textbox1](https://user-images.githubusercontent.com/42106198/76787672-86522e00-6787-11ea-92a9-98e16406c4da.PNG)
![textbox2](https://user-images.githubusercontent.com/42106198/76787708-92d68680-6787-11ea-997b-79a490a612af.PNG)
![textbox3](https://user-images.githubusercontent.com/42106198/76787719-9702a400-6787-11ea-9779-8c2e2a0d611a.PNG)

**Platform and software (please complete the following information):**
 - OS: Windows
 - Pygame GUI version: 0.4.2
 - Pygame version: 1.9.6

**Additional context**
code used for auto-scrolling the scroll bar for every new line of text:

    if self.text_box.scroll_bar:
            scroll_bar = self.text_box.scroll_bar
            scroll_bar.scroll_wheel_down = False
            scroll_bar.scroll_position += (250 * 1)
            scroll_bar.scroll_position = min(scroll_bar.scroll_position,
                                           scroll_bar.bottom_limit - scroll_bar.sliding_button.rect.height)
            x_pos = scroll_bar.rect.x + scroll_bar.shadow_width + scroll_bar.border_width
            y_pos = scroll_bar.scroll_position + scroll_bar.rect.y + scroll_bar.shadow_width + \
                    scroll_bar.border_width + scroll_bar.button_height
            scroll_bar.sliding_button.set_position(pygame.math.Vector2(x_pos, y_pos))

            scroll_bar.start_percentage = scroll_bar.scroll_position / scroll_bar.scrollable_height
            if not scroll_bar.has_moved_recently:
                scroll_bar.has_moved_recently = True

**Comment by MyreMylar** [comment]
Will add this into the plans for the text refactor. 

I think I understand what you want to happen and it seems a sensible default for one of my planned features in the big text refactor. This should remind me when I come to it.

**Comment by Snayff** [comment]
I think I am actually experiencing something similar. I haven't changed the code in the GUI but the adding of new lines is not as consistent as it was, i.e. the position of the sub-surface. This seems to be happening more the quicker I kill and re-init the message log.

**Comment by cbradburne** [comment]
I'm so happy I stumbled across this snippet of code. Currently it's working great for me, once I removed the limit of (250 * 1) scroll position. I'm looking forward to the 0.6.0 update where a simple "see.end" type command could replace this code which to be honest, I'm struggling to understand, but for now it works!

Here's my edited code if anyone else needs to auto scroll to the end / bottom of a text box:
`if textBoxSerial.scroll_bar:
        scroll_bar = textBoxSerial.scroll_bar
        scroll_bar.scroll_position = (scroll_bar.bottom_limit - scroll_bar.sliding_button.rect.height)
        x_pos = scroll_bar.rect.x + scroll_bar.shadow_width + scroll_bar.border_width
        y_pos = scroll_bar.scroll_position + scroll_bar.rect.y + scroll_bar.shadow_width + \
                scroll_bar.border_width + scroll_bar.button_height
        scroll_bar.sliding_button.set_position(pygame.math.Vector2(x_pos, y_pos))

        scroll_bar.start_percentage = scroll_bar.scroll_position / scroll_bar.scrollable_height
        if not scroll_bar.has_moved_recently:
            scroll_bar.has_moved_recently = True`

Thanks again MyreMylar for the great work and continued support.

**Comment by pengzhenghao** [comment]
Hi, so how we make sure the textbox will automatically scroll to the end of the text?

**Comment by SlowHorsey** [comment]
This is still an issue for me in version 0.6.14. When appending html text to a textbox the scrollbar initially seems to roll down to the bottom as intended but then is immediately somehow "corrected" by either being reset to the top or somewhere in the middle of the text. My workaround is to reapply it externally by  using set from start percentage:
            my_text_box.append_html_text(text) 
            scroll_bar = my_text_box.scroll_bar
            scroll_bar.set_scroll_from_start_percentage(
                scroll_bar.start_percentage
                * scroll_bar.scrollable_height
            )
