### ISSUE TITLE
Multiple Language Support for GUI Text, Translation friendly

### ISSUE THREAD

**Issue by MyreMylar** [MyreMylar/pygame_gui#79]
**Is your feature request related to a problem? Please describe.**
GUI text right now (e.g. Button text, Window Titles) is mainly hard coded, or the defaults are hard coded in English. 

**Describe the solution you'd like**
I'd like to pull out all text strings like this into .json data that has English defaults but can also be overrode much like the default appearance theme can be overridden.

In this way a language selector in a pygame app could change the language used in the GUI by switching between json files for different languages.

I'd like it to be as 'industry standard' as possible because I know many small developers work with outside translation services.

**Describe alternatives you've considered**
Symbols for everything?

**To Do To Close**

- [x] Add a language selection box to the a test example that lets us switch between a couple of languages (German, Japanese, Russian). This will let us test if everything else is working.
- [x] Support loading translation files with i18n
- [x] Add a GUI wide event that elements with text can react to when the language changes (getting an appropriate translation mostly but perhaps also resorting any selection list type elements that are kept sorted (right now we don't actually have a thing to keep these sorted).
- [x] Load a new default font when switching to languages with different alphabets (e.g. japanese)
- [x] solve handling 'allowed characters' for text entry on a per language basis.
- [x] Support at least EFIGS + Japanese, Russian & Chinese in initial release. Some alphabets cannot be rendered correctly by pygame yet.
- [x] Handle locale for custom fonts. This needs testing in examples.
- [x] make sure we force i18n to json mode.
- [x] Allow setting locale at startup
- [x] translate text in translation example script.
- [x] Make window buttons dynamically sized for indonesian - make sure button is resized on locale changed and window layout updates on member size changed.

**Comment by MyreMylar** [comment]
May also need to investigate bundling more default fonts for different languages:
https://fonts.google.com/?query=noto+sans

**Comment by nthykier** [comment]
I would recommend supporting GNU PO/MO files (e.g. via polib) as it is one of the only ways I know to get proper support for all the "weird corner cases" that make up language translations.  Both for picking the right variant of a word based on the "number of items" or context based translations.

The singularity game supports translations via polib (without the counter support, sadly).  One of the hardest parts is to properly reload the text when the translation is changed.  Having built-in support for this in the GUI framework makes a world of difference in how easy this is to get right.

**Comment by nthykier** [comment]
Addendum: You will want the `gettext` variant that only supports MO files if you want to support plural translations correctly (polib does not have this).  Though PO files can be supported by "on-the-fly" rewriting them to MO files via polib (`gettext.GNUTranslations` can parse a MO file from an open file-handle without having to box with "installing" it correctly).

Built-in support for translation updates also affects things like sorting order.  E.g. if you have knowledge-base/X-pedia of in-game concepts and the concepts are sorted by name, then they need to be reordered on translation reload as all the strings change.  Sadly, locale-aware sorting is a separate pain where the built-in `locale.strxfrm` does not work reliably on Mac OS - the only reliable method I have found is ICU.  Fortunately, the sorting pain can be punted back to the consuming programmer as long as they have a suitable hook for reacting to locale changes (leaving them to decide if they want correctness + an extra dependency vs. default without the dependency).

**Comment by timewarpsgh** [comment]
Currently, the text arugument passed to a UI element only supports English. Looking forward to seeing multi-language support.

**Comment by MyreMylar** [comment]
I've had a look into using python's `gettext` library for localization support. Unfortunately, from what I can tell as a non-lawyer, that submodule is effectively licensed under the full-fat GPL - meaning it is only usable in free software (unlike pygame which is LGPL, or this library which uses the MIT license). Which is a shame as it does look pretty good. I don't want to restrict people using pygame-gui to only release free games, because I used the wrong part of the python standard library.

I have also found [python-18n](https://github.com/danhper/python-i18n) by @danhper which looks to have some of the same functionality - it is licensed under the MIT license instead. Do you think it might work for your uses cases @nthykier ?

**Comment by nthykier** [comment]
I think the library you find looks decent at a very quick glance as default translation engine given you cannot use `gettext`.  The namespace feature seems like a nice touch too and it does seem to understand + solve the number issue sufficiently well.

But to be honest, it matters less to me which built-in translation engine pygame_gui provides (as you can usually work around that if needed be) as long as it provides the relevant hook for a (custom) widget to react to a translation reload/change.  You already added a "Task" item for that feature, so I am look forward with anticipation to seeing it. :)

**Comment by nthykier** [comment]
Correction - the library you found does seem to suffer from the standard "number issue" that most "basic" translation engines suffer from.

If you want the nitty gritty details, have a look at https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html#Plural-forms which mentions languages like "Romanian" which has the plural forms:

- Singular
- Plural ending with [012][0-9].  Such as 213
- Plural (everything else).  Such as 357

Compare that with the options given by python-i18n:

- zero
- one
- few
- many

Now 213 and 357 are clearly neither "zero", "one" nor "few".  But at the same time, they cannot both be "many" either. 

(If you really want to stress test the translation engine, then check Arabic which has 6 distinct plural forms according to that source)

**Comment by danhper** [comment]
Hey! GitHub notified me of the discussion so jumping in.
I have indeed mostly used this with English, French and Japanese, so there might be quite a few cases that are not covered for other languages.
Regarding plurals, I think it should be quite easy to add per-language rules using `count` as an argument to the rule. Do you think that would be enough for cases like Romanian or Arabic? I'm unfortunately not familiar with either of these languages.

**Comment by nthykier** [comment]
I am not super well-versed in "exotic" plural rules other than what that page shows and I recommend reading the relevant part of it (I think the interesting bit comes half-way down).  But what I can tell is that it is complicated and my gut feeling is that `count` proposal seems too simple to solve it (not that I fully understand what you mean, but the examples shown in the gettext documentation are complex - and makes me glad that I only work with languages that have "simple" plural rules).

**Comment by MyreMylar** [comment]
Looks like you'd maybe need to be able to add rules something like:

`'{count}%10 >= 2 and {count}%10 <= 4' : "You have {count} new mails"`

**Comment by nthykier** [comment]
Except, you would want the translator to inject that rule, so you as a programmer does not need to know all the existing plural rules.  Related, I am pretty sure that if the programmer need to define this as input, they will end up with conflicting definitions once they add "enough" languages.

**Comment by MyreMylar** [comment]
Yes, ideally the translator would be able to pass a language specific
condition to the translation engine and on the code side it would do
something like:


```plural_string = None
for condition, index in enumerate(conditions):
    if condition (count):
        plural_string = conditional_strings[index]
if plural_string is None:
    #whatever happens now with one, zero etc
```

Where `condition` is an expression/function evaluating to a Boolean with
count as a variable.

Hopefully that makes sense writing code on a phone while walking is tricky
🙂

**Comment by danhper** [comment]
Thanks for the comments, that's more or less what I had in mind.
I think it might be slightly simpler to allow the function to return a custom key and then use it in the translation file.
For example:

```python
def romanian_rule(count):
    if count == 1:
        return "one"
    elif count == 0 or (count % 100 > 0 and count % 100 < 20):
        return "special"
    else:
        return "other"
i18n.config.plural_rules["ro"] = romanian_rule
```

and in the `pluralize`:

```python
plural_rule = i18n.config.plural_rules.get(locale)
if plural_rule:
    key = plural_rule(count)
    if key in translation:
        return translation[key]
```

I believe most of these rules could be built in the library but there is obviously the non-trivial task of adding and documenting them.
