### ISSUE TITLE
More complex menu/gui example

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#81]
**Is your feature request related to a problem? Please describe.**
I find I am trying to work out my own way to go from the examples provided to a more complex example. I am pretty new to game dev so I have made a lot of mistakes in the process.

**Describe the solution you'd like**
An example menu or screen gui that demonstrates the core functionality; buttons, labels, hover over info, progress bar. That sort of thing. This would be particularly useful to see how the theme.json would look. 

Clearly it shouldnt do more than hold lorem ipsum and fire print statements but to see a holistic game-focused example could be of benefit. And might be good to advertise with, too!

**Additional context**
Examples:
https://i.imgur.com/I3eOJz9.gifv
https://i.imgur.com/IGyP8xQ.png
https://i.imgur.com/3nYwENb.jpg

**Comment by MyreMylar** [comment]
I expect this will come naturally in time. I'm personally trying to strike a balance between adding new features to the library and working on other useful things, many of which use the library.

One of my next mini planned projects is to try and build a simple paint program (like classic Microsoft Paint) using the library to give it a bit of a road test that way. I've also been steadily adding it steadily to my various educational game projects.

I have grand plans to make bigger games at some point too.

Of course now we (in the UK) are all trapped in the house for the foreseeable, some of this work may be accelerated :)

The little GIF things are very helpful as targets though, I'm not sure the library could do all of them easily yet, which likely means there is more work to be done. (Nested tooltips via links! What a concept.)

**Comment by MyreMylar** [comment]
You can have a poke at Pygame Paint now here: https://github.com/MyreMylar/pygame_paint

It's not the cleanest, or at all commented code but it might help to have a look at.

**Comment by Snayff** [comment]
I think that is a great example, mate. I think it's pretty comprehensive and offers a whole lot of approaches that can be used as an example. I'd definitely suggest adding it to your examples!

**Comment by Snayff** [comment]
I think that is a great example, mate. I think it's pretty comprehensive and offers a whole lot of approaches that can be used as an example. I'd definitely suggest adding it to your examples!
