### ISSUE TITLE
pygame' has no attribute 'BUTTON_LEFT'

### ISSUE THREAD

**Issue by rvhu-cl** [MyreMylar/pygame_gui#86]
When running the demo general_ui_test_app.py
I get the following error

File "/home/therol6/.local/lib/python3.6/site-packages/pygame_gui/elements/ui_text_entry_line.py", line 672, in _process_mouse_button_event
    if event.type == pygame.MOUSEBUTTONDOWN and event.button == pygame.BUTTON_LEFT:
AttributeError: module 'pygame' has no attribute 'BUTTON_LEFT'

**Platform and software (please complete the following information):**
 - OS: [Linux]
 - Pygame GUI version [e.g. 0.5.0]
 - Pygame version [e.g. 1.9.3]

**Additional context**

**Comment by MyreMylar** [comment]
Damn, guess that constant got added after pygame.19.3. Thanks for the report.

If you want to fix it yourself, you can upgrade pygame to 1.9.6.

**Comment by rvhu-cl** [comment]
Oke update to 1.9.6 and is working now. Thank. Keep up the good work,

**Comment by MyreMylar** [comment]
This should now be fixed in version 0.5.1.
