### ISSUE TITLE
Window without title bar and exit button

### ISSUE THREAD

**Issue by rvhu-cl** [MyreMylar/pygame_gui#87]
In the old version you yourself can decide if you want to have a title bar and a X button for closing the window. in the 5.0 version this is not optional anymore. Can these please be a optional future.

PS the new version looks a lot cleaner.

**Comment by MyreMylar** [comment]
This is now a theming option for the windows. See:

https://pygame-gui.readthedocs.io/en/latest/theme_reference/theme_window.html


Basically you want to set

"enable_title_bar": "0"

in the "misc" block of your "window" theming block.

**Comment by rvhu-cl** [comment]
I have tried it but still there is a titlebar and exit button

this is my css

    "alarm_window":
    {
        "colours":
        {
            "dark_bg": "#000000,#000000,180",
            "normal_border": "#ffB2A5",
            "normal_bg": "#000000"
        },
        "misc":
        {
            "enable_title_bar": "0",
        "enable_close_button": "0",   
        "title_bar_height": "0",
        "shape": "rounded_rectangle",
            "border_width": "0",
            "shadow_width": "1"
        }
    },

    "alarm_window#title_bar":
    {
        "colours":
        {
            "dark_bg": "#000000,#000000,180",
            "normal_border": "#ffB2A5",
            "normal_bg": "#000000"
        },
        "misc":
        {
            "enable_title_bar": "0",
        "enable_close_button": "0",   
        "title_bar_height": "0",
        "shape": "rounded_rectangle",
            "border_width": "0",
            "shadow_width": "1"
        }
    },

and my code

class alarmWindow(UIWindow):
    def __init__(self, rect, ui_manager):

        #element_ids = ['alarm_window']

        #super().__init__(rect, ui_manager, element_ids=element_ids)
        super().__init__(rect, ui_manager,
                         window_display_title='Alarm window',
                         object_id='alarm_window',
                         resizable=True)

result:
Still a title bar and a exit button

**Comment by MyreMylar** [comment]
Ah, I think I figured out the bug. Right now the title bar elimination code only kicks in when you edit the theme live rather than on startup.

I'll patch it. in 0.5.1.

**Comment by MyreMylar** [comment]
OK this should be resolved in 0.5.1 - which is now released on PyPI.

**Comment by rvhu-cl** [comment]
Test it with 0.5.1 perfect it works. many thanks. Keep up the good work.
