### ISSUE TITLE
UIWindow: Full titlebar width when enable_close_button=0

### ISSUE THREAD

**Issue by kildirian** [MyreMylar/pygame_gui#92]
Hi,
Is it possible to enlarge the titlebar of a windows to the full width if the enable_close_button is set to 0 ?  Otherwise it is not nice.

I have to write :
        self.title_bar_button_width=0
        self.title_bar.set_dimensions((self._window_root_container.relative_rect.width -
                                                   self.title_bar_button_width,
                                                   self.title_bar_height))

**Comment by MyreMylar** [comment]
Thanks for reminding me about this bug. I'll make a note to fix this in the next version.

**Comment by MyreMylar** [comment]
This should be fixed 0.5.5.
