### ISSUE TITLE
TextBox in a window doesn't use theming block id ?

### ISSUE THREAD

**Issue by kildirian** [MyreMylar/pygame_gui#94]
Hi,
I'm starting to use the library so may be I'm wrong but when I tried to display a textBox in a window
the textBox does not use the param in the "ui_theme.json" even if I specify the object ID. However for others elements such as buton elements it works well.
I've tried with the theming block id "text_box"  or a personalized id "#MyTextBox"
Is it a bug or I'm wrong in the use of the theming id ?

ps: The theming block id works for UITextBox if I display it directly on the main without using windows.

Here is my code :
------- JSON File -------

```
    "text_box":
    {
        "misc":
        {
            "shape": "rounded_rectangle",
            "shape_corner_radius": "10"
        }
    },
   "#MyTextBox":
    {
        "misc":
        {
            "shape": "rounded_rectangle",
            "shape_corner_radius": "10"
        }
    }
```

------- Main File -------
```

class DialogueWindow(pygame_gui.elements.UIWindow):
    def __init__(self, manager):        
        super().__init__(pygame.Rect((200, 50), (420, 520)), manager,object_id='#MyWindow')
        self.textBox = UITextBox("my text..."
                         pygame.Rect(..),
                         manager=manager,
                         container=self.get_container(),
                         parent_element=self,
                         object_id="#MyTextBox"
                         )



pygame.init()

pygame.display.set_caption("Text test")
screen_size = (800, 600)
screen = pygame.display.set_mode(screen_size)  # FULLSCREEN

background_surface = pygame.Surface(screen_size)
background_surface.fill(pygame.Color("#000000"))
clock = pygame.time.Clock()
manager = UIManager(screen_size, 'data/theme1.json')

dialogueWindow=DialogueWindow(manager)

running = True

clock = pygame.time.Clock()
while running:
    time_delta = clock.tick(60)/1000.0

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        
        manager.process_events(event)

    manager.update(time_delta)

    screen.blit(background_surface, (0, 0))
    manager.draw_ui(screen)

    pygame.display.update()
    
pygame.quit()

```

**Comment by MyreMylar** [comment]
If you want to specify elements contained inside others you usually specify the parent in the ID as well like so:

    "#MyWindow.#MyTextBox":
    {
        "misc":
        {
            "shape": "rounded_rectangle",
            "shape_corner_radius": "10",
        }
    }

Though, it might look a little odd to round the corners of a text box inside of a window. You might be better off rounding the corners of the window itself:

    "#MyWindow":
    {
        "misc":
        {
            "shape": "rounded_rectangle",
            "shape_corner_radius": "10",
        }
    }

**Comment by kildirian** [comment]
I better understand how it works,
Thanks for your help.

Is there a place where I can ask question about pygame_gui library ?
I guess, here is not the good place, is it ?

**Comment by MyreMylar** [comment]
> Is there a place where I can ask question about pygame_gui library ?
> I guess, here is not the good place, is it ?

I also answer questions about pygame_gui on reddit.com/r/pygame. If the volume of queries gets really high one day I guess I could look into Discord.

Issue seems resolved otherwise.
