### ISSUE TITLE
UI_BUTTON_ON_HOVERED Event not in Constants

### ISSUE THREAD

**Issue by Snayff** [MyreMylar/pygame_gui#99]
**Expected behaviour**
The new hover events are available, as listed in the docs (on_hover, on_unhover) are not in the version on PyPI.

**Platform and software (please complete the following information):**
 - OS: Windows 10 64 bit
 - Pygame GUI version: 0.5.1
 - Pygame version: 2.0.0dev6

**Additional context**
I am told that installing directly from the repo works so I wonder if PyPI is on a different version.

**Comment by MyreMylar** [comment]
This is just because I've already documented the new event in the main
branch.

You can look at versioned docs on read the docs to see the events docs for
0.5.0.

**Comment by Snayff** [comment]
My bad, I assumed the latest docs were for the latest release. 

Unrelated, but as there's nowhere to give feedback; v0.5 is excellent. I've been using it quite a lot in the last few days and it's working well. Easier to use, more feature rich. Great work, mate.
